# OpenBind-HIPPO

- **Target: A71EV2A**
- **Cycle: 01**

## Imports

In [2]:
%load_ext autoreload
%autoreload 2
import hippo
import mrich
from mrich import print
from pathlib import Path
from os import environ
import shutil
import molparse as mp
import pandas as pd
import plotly.express as px

## Config

In [3]:
target_name = "XX01ZVNS2B"
target_dir = Path(environ["BULK"]) / "TARGETS" / target_name
cycle_name = "cycle_01"
cycle_dir = Path(cycle_name)
aligned_dir = target_dir / "aligned_files"

## Animal

In [4]:
animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")

 Creating HIPPO animal

name = XX01ZVNS2B

db_path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/XX01ZVNS2B/XX01ZVNS2B.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/XX01ZVNS2B/XX01ZVNS2B.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/XX01ZVNS2B/XX01ZVNS2B.sqlite!

 Success  Initialised animal HIPPO("XX01ZVNS2B")!

## Load chem review

In [18]:
df = pd.read_excel("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_1steps.xlsx")#, sheet_name="chem-review")
select = df[df["lisa-select"]=="Y"]
print(len(select))
ids = [int(cname[1:]) for cname in select["target-names"]]
cset = animal.compounds[ids]
cset.add_tag("openbind_xx01zvns2b_c1_scaffolds_chemok")
cset

767

Tagged {C × 767} w/ "openbind_xx01zvns2b_c1_scaffolds_chemok"

{C × 767}

In [19]:
df = pd.read_excel("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_2steps.xlsx")#, sheet_name="chem-review")
select = df[df["lisa-select"]=="Y"]
print(len(select))
ids = [int(cname[1:]) for cname in select["target-names"]]
cset = animal.compounds[ids]
cset.add_tag("openbind_xx01zvns2b_c1_scaffolds_chemok")
cset

0

Tagged {C × 0} w/ "openbind_xx01zvns2b_c1_scaffolds_chemok"

{C × 0}

## Quote reactants

In [5]:
bbdb = hippo.HIPPO("BB", Path(environ["HOME2"])/"EnamineCatalogs/enamine_bb_hippo.sqlite")

 Creating HIPPO animal

name = BB

db_path = /opt/xchem-fragalysis-2/maxwin/EnamineCatalogs/enamine_bb_hippo.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/EnamineCatalogs/enamine_bb_hippo.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/EnamineCatalogs/enamine_bb_hippo.sqlite!

 Success  Initialised animal HIPPO("BB")!

In [6]:
animal.quote_reactants(bbdb)

#compounds = 7189

Output()

Output()

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

#new quotes = 49066

#quoted_compounds = 5326

#unquoted_compounds = 1863

## In-Stock recipe

In [12]:
recipe = hippo.Recipe.from_compounds(cset, quoted_only=True)
recipe

#compounds = 767

Output()

 ERROR  Reactants not available for reaction=R895: C121572 + C121793 -> C117 via Amidation!

 ERROR  No solutions for compound=C117 (comp.reactions.ids=[895])!

 ERROR  Reactants not available for reaction=R963: C122475 + C123083 + C123097 -> C120 via
Petasis-borono_Mannich_reaction!

 ERROR  No solutions for compound=C120 (comp.reactions.ids=[963])!

 ERROR  Reactants not available for reaction=R1822: C121262 + C123008 -> C156 via Amidation!

 ERROR  No solutions for compound=C156 (comp.reactions.ids=[1822])!

 ERROR  Reactants not available for reaction=R2914: C122424 + C124196 -> C189 via Amidation!

 ERROR  No solutions for compound=C189 (comp.reactions.ids=[2914])!

 ERROR  Reactants not available for reaction=R5069: C129030 + C129201 -> C497 via Ester_amidation!

 ERROR  No solutions for compound=C497 (comp.reactions.ids=[5069])!

 ERROR  Reactants not available for reaction=R5002: C129074 + C129075 -> C698 via Amidation!

 ERROR  No solutions for compound=C698 (comp.reactions.ids=[5002])!

 ERROR  Reactants not available for reaction=R4718: C121392 + C128568 -> C834 via Ester_amidation!

 ERROR  No solutions for compound=C834 (comp.reactions.ids=[4718])!

 ERROR  Reactants not available for reaction=R5064: C129181 + C129182 -> C1055 via Ester_amidation!

 ERROR  No solutions for compound=C1055 (comp.reactions.ids=[5064])!

 ERROR  Reactants not available for reaction=R4829: C128769 + C128770 -> C1553 via Amidation!

 ERROR  No solutions for compound=C1553 (comp.reactions.ids=[4829])!

 ERROR  Reactants not available for reaction=R4876: C127972 + C128852 -> C1899 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C1899 (comp.reactions.ids=[4876])!

 ERROR  Reactants not available for reaction=R5270: C121310 + C129575 -> C1954 via
Chan-Lam_coupling_(amination)!

 ERROR  No solutions for compound=C1954 (comp.reactions.ids=[5270])!

 ERROR  Reactants not available for reaction=R4794: C128708 + C128709 -> C1996 via Amidation!

 ERROR  No solutions for compound=C1996 (comp.reactions.ids=[4794])!

 ERROR  Reactants not available for reaction=R4672: C128467 + C128468 -> C2321 via Amidation!

 ERROR  No solutions for compound=C2321 (comp.reactions.ids=[4672])!

 ERROR  Reactants not available for reaction=R5083: C127972 + C129240 -> C2390 via
Mitsunobu_aryl_ether_synthesis!

 ERROR  No solutions for compound=C2390 (comp.reactions.ids=[5083])!

 ERROR  Reactants not available for reaction=R4817: C128750 + C128751 -> C2852 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C2852 (comp.reactions.ids=[4817])!

 ERROR  Reactants not available for reaction=R5052: C65537 + C128912 -> C3045 via Amidation!

 ERROR  No solutions for compound=C3045 (comp.reactions.ids=[5052])!

 ERROR  Reactants not available for reaction=R5017: C129098 + C129099 -> C3232 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C3232 (comp.reactions.ids=[5017])!

 ERROR  Reactants not available for reaction=R5042: C128912 + C129143 -> C3381 via Amidation!

 ERROR  No solutions for compound=C3381 (comp.reactions.ids=[5042])!

 ERROR  Reactants not available for reaction=R4757: C128653 + C128654 -> C3502 via Amidation!

 ERROR  No solutions for compound=C3502 (comp.reactions.ids=[4757])!

 ERROR  Reactants not available for reaction=R4990: C129053 + C129054 -> C3506 via Amidation!

 ERROR  No solutions for compound=C3506 (comp.reactions.ids=[4990])!

 ERROR  Reactants not available for reaction=R4696: C128516 + C128517 -> C3924 via
Reductive_amination!

 ERROR  No solutions for compound=C3924 (comp.reactions.ids=[4696])!

 ERROR  Reactants not available for reaction=R4804: C128727 + C128728 -> C4264 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C4264 (comp.reactions.ids=[4804])!

 ERROR  Reactants not available for reaction=R5410: C129101 + C129813 -> C4308 via Amidation!

 ERROR  No solutions for compound=C4308 (comp.reactions.ids=[5410])!

 ERROR  Reactants not available for reaction=R5065: C129183 + C129184 -> C4500 via Amidation!

 ERROR  No solutions for compound=C4500 (comp.reactions.ids=[5065])!

 ERROR  Reactants not available for reaction=R4890: C128876 + C128877 -> C4958 via Amidation!

 ERROR  No solutions for compound=C4958 (comp.reactions.ids=[4890])!

 ERROR  Reactants not available for reaction=R4887: C128722 + C128869 -> C5045 via Amidation!

 ERROR  No solutions for compound=C5045 (comp.reactions.ids=[4887])!

 ERROR  Reactants not available for reaction=R5449: C128870 + C129877 -> C5185 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C5185 (comp.reactions.ids=[5449])!

 ERROR  Reactants not available for reaction=R5334: C129615 + C129673 -> C5230 via Amidation!

 ERROR  No solutions for compound=C5230 (comp.reactions.ids=[5334])!

 ERROR  Reactants not available for reaction=R4927: C121276 + C128948 -> C5381 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C5381 (comp.reactions.ids=[4927])!

 ERROR  Reactants not available for reaction=R5477: C129923 -> C5440 via N-Boc_deprotection!

 ERROR  No solutions for compound=C5440 (comp.reactions.ids=[5477])!

 ERROR  Reactants not available for reaction=R5035: C128482 + C128515 -> C5682 via Amidation!

 ERROR  No solutions for compound=C5682 (comp.reactions.ids=[5035])!

 ERROR  Reactants not available for reaction=R5030: C128602 + C129122 -> C6047 via Amidation!

 ERROR  No solutions for compound=C6047 (comp.reactions.ids=[5030])!

 ERROR  Reactants not available for reaction=R4683: C59938 + C128491 -> C6094 via Amidation!

 ERROR  No solutions for compound=C6094 (comp.reactions.ids=[4683])!

 ERROR  Reactants not available for reaction=R4776: C128687 + C128688 -> C6452 via Amidation!

 ERROR  No solutions for compound=C6452 (comp.reactions.ids=[4776])!

 ERROR  Reactants not available for reaction=R4678: C128482 + C128483 -> C6762 via Amidation!

 ERROR  No solutions for compound=C6762 (comp.reactions.ids=[4678])!

 ERROR  Reactants not available for reaction=R4758: C128655 + C128656 -> C6950 via Amidation!

 ERROR  No solutions for compound=C6950 (comp.reactions.ids=[4758])!

 ERROR  Reactants not available for reaction=R5045: C128468 + C128898 -> C6960 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C6960 (comp.reactions.ids=[5045])!

 ERROR  Reactants not available for reaction=R4715: C128562 + C128563 -> C7144 via Ester_amidation!

 ERROR  No solutions for compound=C7144 (comp.reactions.ids=[4715])!

 ERROR  Reactants not available for reaction=R5046: C63998 + C129149 -> C7211 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C7211 (comp.reactions.ids=[5046])!

 ERROR  Reactants not available for reaction=R5090: C128573 + C129264 -> C7474 via Amidation!

 ERROR  No solutions for compound=C7474 (comp.reactions.ids=[5090])!

 ERROR  Reactants not available for reaction=R4885: C121388 + C128868 -> C7556 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C7556 (comp.reactions.ids=[4885])!

 ERROR  Reactants not available for reaction=R4742: C128623 + C128624 -> C7561 via Ester_amidation!

 ERROR  No solutions for compound=C7561 (comp.reactions.ids=[4742])!

 ERROR  Reactants not available for reaction=R4893: C128881 + C128882 -> C7584 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C7584 (comp.reactions.ids=[4893])!

 ERROR  Reactants not available for reaction=R4740: C128573 + C128619 -> C7846 via Ester_amidation!

 ERROR  No solutions for compound=C7846 (comp.reactions.ids=[4740])!

 ERROR  Reactants not available for reaction=R4968: C129018 + C129019 -> C8017 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C8017 (comp.reactions.ids=[4968])!

 ERROR  Reactants not available for reaction=R4999: C121476 + C129070 -> C8033 via Amidation!

 ERROR  No solutions for compound=C8033 (comp.reactions.ids=[4999])!

 ERROR  Reactants not available for reaction=R4741: C128621 + C128622 -> C8072 via Ester_amidation!

 ERROR  No solutions for compound=C8072 (comp.reactions.ids=[4741])!

 ERROR  Reactants not available for reaction=R4795: C125326 + C128710 -> C8147 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C8147 (comp.reactions.ids=[4795])!

 ERROR  Reactants not available for reaction=R4713: C128558 + C128559 -> C8170 via Amidation!

 ERROR  No solutions for compound=C8170 (comp.reactions.ids=[4713])!

 ERROR  Reactants not available for reaction=R5481: C129932 + C129933 -> C8188 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C8188 (comp.reactions.ids=[5481])!

 ERROR  Reactants not available for reaction=R5061: C128666 + C129178 -> C8333 via Amidation!

 ERROR  No solutions for compound=C8333 (comp.reactions.ids=[5061])!

 ERROR  Reactants not available for reaction=R4681: C128487 + C128488 -> C8707 via Amidation!

 ERROR  No solutions for compound=C8707 (comp.reactions.ids=[4681])!

 ERROR  Reactants not available for reaction=R4734: C128605 + C128606 -> C9452 via Amidation!

 ERROR  No solutions for compound=C9452 (comp.reactions.ids=[4734])!

 ERROR  Reactants not available for reaction=R4839: C128605 + C128793 -> C9460 via Amidation!

 ERROR  No solutions for compound=C9460 (comp.reactions.ids=[4839])!

 ERROR  Reactants not available for reaction=R4954: C128605 + C128994 -> C9461 via Amidation!

 ERROR  No solutions for compound=C9461 (comp.reactions.ids=[4954])!

 ERROR  Reactants not available for reaction=R4859: C128822 + C128823 -> C9562 via Amidation!

 ERROR  No solutions for compound=C9562 (comp.reactions.ids=[4859])!

 ERROR  Reactants not available for reaction=R4812: C50 + C128741 -> C9601 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C9601 (comp.reactions.ids=[4812])!

 ERROR  Reactants not available for reaction=R5087: C129250 + C129251 -> C9739 via Amidation!

 ERROR  No solutions for compound=C9739 (comp.reactions.ids=[5087])!

 ERROR  Reactants not available for reaction=R4854: C121783 + C128813 -> C9815 via Amidation!

 ERROR  No solutions for compound=C9815 (comp.reactions.ids=[4854])!

 ERROR  Reactants not available for reaction=R5141: C128706 + C129350 -> C9994 via Amidation!

 ERROR  No solutions for compound=C9994 (comp.reactions.ids=[5141])!

 ERROR  Reactants not available for reaction=R5209: C129475 + C129476 -> C9996 via
Buchwald-Hartwig_amination!

 ERROR  No solutions for compound=C9996 (comp.reactions.ids=[5209])!

 ERROR  Reactants not available for reaction=R5041: C129141 + C129142 -> C9997 via
Buchwald-Hartwig_amination!

 ERROR  No solutions for compound=C9997 (comp.reactions.ids=[5041])!

 ERROR  Reactants not available for reaction=R4934: C128954 + C128955 -> C10022 via Amidation!

 ERROR  No solutions for compound=C10022 (comp.reactions.ids=[4934])!

 ERROR  Reactants not available for reaction=R5084: C123002 + C129241 -> C10247 via
Mitsunobu_aryl_ether_synthesis!

 ERROR  No solutions for compound=C10247 (comp.reactions.ids=[5084])!

 ERROR  Reactants not available for reaction=R4977: C129034 + C129035 -> C10394 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C10394 (comp.reactions.ids=[4977])!

 ERROR  Reactants not available for reaction=R5113: C129301 + C129302 -> C10430 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C10430 (comp.reactions.ids=[5113])!

 ERROR  Reactants not available for reaction=R4747: C128636 + C128637 -> C10581 via Amidation!

 ERROR  No solutions for compound=C10581 (comp.reactions.ids=[4747])!

 ERROR  Reactants not available for reaction=R4731: C124934 + C128599 -> C10765 via
Buchwald-Hartwig_amination_with_aromatic_nh_intermolecular!

 ERROR  No solutions for compound=C10765 (comp.reactions.ids=[4731])!

 ERROR  Reactants not available for reaction=R4698: C128522 + C128523 -> C11118 via Amidation!

 ERROR  No solutions for compound=C11118 (comp.reactions.ids=[4698])!

 ERROR  Reactants not available for reaction=R4948: C128985 + C128986 -> C11245 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C11245 (comp.reactions.ids=[4948])!

 ERROR  Reactants not available for reaction=R4800: C128720 + C128721 -> C11558 via Amidation!

 ERROR  No solutions for compound=C11558 (comp.reactions.ids=[4800])!

 ERROR  Reactants not available for reaction=R4679: C128484 + C128485 -> C12461 via Amidation!

 ERROR  No solutions for compound=C12461 (comp.reactions.ids=[4679])!

 ERROR  Reactants not available for reaction=R4972: C129024 + C129025 -> C12612 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C12612 (comp.reactions.ids=[4972])!

 ERROR  Reactants not available for reaction=R5266: C129015 + C129570 -> C12771 via Amidation!

 ERROR  No solutions for compound=C12771 (comp.reactions.ids=[5266])!

 ERROR  Reactants not available for reaction=R5401: C121388 + C129798 -> C64060 via
Reductive_amination!

 ERROR  No solutions for compound=C13018 (comp.reactions.ids=[4743])!

 ERROR  Reactants not available for reaction=R5059: C128614 + C129176 -> C13096 via Amidation!

 ERROR  No solutions for compound=C13096 (comp.reactions.ids=[5059])!

 ERROR  Reactants not available for reaction=R4969: C129020 + C129021 -> C13322 via Amidation!

 ERROR  No solutions for compound=C13322 (comp.reactions.ids=[4969])!

 ERROR  Reactants not available for reaction=R4840: C128794 + C128795 -> C13551 via Amidation!

 ERROR  No solutions for compound=C13551 (comp.reactions.ids=[4840])!

 ERROR  Reactants not available for reaction=R4888: C128870 + C128871 + C128872 -> C13857 via
Petasis-borono_Mannich_reaction!

 ERROR  No solutions for compound=C13857 (comp.reactions.ids=[4888])!

 ERROR  Reactants not available for reaction=R5051: C129156 + C129157 -> C13957 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C13957 (comp.reactions.ids=[5051])!

 ERROR  Reactants not available for reaction=R4709: C128550 + C128551 -> C14109 via Amidation!

 ERROR  No solutions for compound=C14109 (comp.reactions.ids=[4709])!

 ERROR  Reactants not available for reaction=R4900: C128898 + C128899 -> C14145 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C14145 (comp.reactions.ids=[4900])!

 ERROR  Reactants not available for reaction=R4806: C128731 + C128732 -> C14550 via Amidation!

 ERROR  No solutions for compound=C14550 (comp.reactions.ids=[4806])!

 ERROR  Reactants not available for reaction=R4720: C128571 + C128572 -> C14573 via Amidation!

 ERROR  No solutions for compound=C14573 (comp.reactions.ids=[4720])!

 ERROR  Reactants not available for reaction=R4695: C128514 + C128515 -> C14910 via Amidation!

 ERROR  No solutions for compound=C14910 (comp.reactions.ids=[4695])!

 ERROR  Reactants not available for reaction=R4964: C129012 + C129013 -> C15347 via Amidation!

 ERROR  No solutions for compound=C15347 (comp.reactions.ids=[4964])!

 ERROR  Reactants not available for reaction=R5010: C15672 + C129090 -> C15684 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C15684 (comp.reactions.ids=[5010])!

 ERROR  Reactants not available for reaction=R4974: C129015 + C129029 -> C15701 via Amidation!

 ERROR  No solutions for compound=C15701 (comp.reactions.ids=[4974])!

 ERROR  Reactants not available for reaction=R4988: C129015 + C129052 -> C15706 via Amidation!

 ERROR  No solutions for compound=C15706 (comp.reactions.ids=[4988])!

 ERROR  Reactants not available for reaction=R4997: C129066 + C129067 -> C15765 via Amidation!

 ERROR  No solutions for compound=C15765 (comp.reactions.ids=[4997])!

 ERROR  Reactants not available for reaction=R4807: C16112 + C128733 -> C16128 via Amidation!

 ERROR  No solutions for compound=C16128 (comp.reactions.ids=[4807])!

 ERROR  Reactants not available for reaction=R4837: C128789 + C128790 -> C16930 via
Chan-Lam_coupling_(amination)!

 ERROR  No solutions for compound=C16930 (comp.reactions.ids=[4837])!

 ERROR  Reactants not available for reaction=R5186: C128814 + C129439 -> C17711 via Amidation!

 ERROR  No solutions for compound=C17711 (comp.reactions.ids=[5186])!

 ERROR  Reactants not available for reaction=R1991: C121617 + C124811 -> C18500 via Amidation!

 ERROR  No solutions for compound=C18500 (comp.reactions.ids=[1991])!

 ERROR  Reactants not available for reaction=R2019: C121262 + C124844 -> C18589 via Amidation!

 ERROR  No solutions for compound=C18589 (comp.reactions.ids=[2019])!

 ERROR  Reactants not available for reaction=R2067: C61484 + C124912 -> C18621 via Amidation!

 ERROR  No solutions for compound=C18621 (comp.reactions.ids=[2067])!

 ERROR  Reactants not available for reaction=R2075: C61484 + C124927 -> C18677 via Amidation!

 ERROR  No solutions for compound=C18677 (comp.reactions.ids=[2075])!

 ERROR  Reactants not available for reaction=R2423: C61484 + C125414 -> C20460 via Amidation!

 ERROR  No solutions for compound=C20460 (comp.reactions.ids=[2423])!

 ERROR  Reactants not available for reaction=R2467: C61484 + C125485 -> C20734 via Amidation!

 ERROR  No solutions for compound=C20734 (comp.reactions.ids=[2467])!

 ERROR  Reactants not available for reaction=R4053: C61484 + C127612 -> C20741 via Amidation!

 ERROR  No solutions for compound=C20741 (comp.reactions.ids=[4053])!

 ERROR  Reactants not available for reaction=R2484: C61484 + C125511 -> C20766 via Amidation!

 ERROR  No solutions for compound=C20766 (comp.reactions.ids=[2484])!

 ERROR  Reactants not available for reaction=R2487: C61484 + C125521 -> C20772 via Amidation!

 ERROR  Reactants not available for reaction=R2489: C121258 + C131230 -> C20772 via
Reductive_amination!

 ERROR  No solutions for compound=C20772 (comp.reactions.ids=[2487, 2489])!

 ERROR  Reactants not available for reaction=R2501: C121920 + C125556 -> C20813 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C20813 (comp.reactions.ids=[2501])!

 ERROR  Reactants not available for reaction=R4473: C125606 + C125775 -> C21293 via Amidation!

 ERROR  No solutions for compound=C21293 (comp.reactions.ids=[4473])!

 ERROR  Reactants not available for reaction=R2640: C121392 + C125775 -> C22615 via Amidation!

 ERROR  No solutions for compound=C22615 (comp.reactions.ids=[2640])!

 ERROR  Reactants not available for reaction=R2670: C121392 + C125828 -> C22669 via Amidation!

 ERROR  No solutions for compound=C22669 (comp.reactions.ids=[2670])!

 ERROR  Reactants not available for reaction=R2791: C122061 + C126013 -> C23312 via Amidation!

 ERROR  No solutions for compound=C23312 (comp.reactions.ids=[2791])!

 ERROR  Reactants not available for reaction=R2792: C122061 + C125278 -> C23314 via Amidation!

 ERROR  No solutions for compound=C23314 (comp.reactions.ids=[2792])!

 ERROR  Reactants not available for reaction=R2745: C61484 + C125947 -> C23730 via Amidation!

 ERROR  No solutions for compound=C23730 (comp.reactions.ids=[2745])!

 ERROR  Reactants not available for reaction=R2950: C122424 + C125278 -> C24585 via Amidation!

 ERROR  No solutions for compound=C24585 (comp.reactions.ids=[2950])!

 ERROR  Reactants not available for reaction=R2951: C122424 + C125300 -> C24675 via Amidation!

 ERROR  No solutions for compound=C24675 (comp.reactions.ids=[2951])!

 ERROR  Reactants not available for reaction=R3013: C126252 + C126253 -> C25106 via Ester_amidation!

 ERROR  No solutions for compound=C25106 (comp.reactions.ids=[3013])!

 ERROR  Reactants not available for reaction=R3049: C61484 + C126303 -> C25624 via Amidation!

 ERROR  No solutions for compound=C25624 (comp.reactions.ids=[3049])!

 ERROR  Reactants not available for reaction=R3060: C61484 + C126316 -> C25711 via Amidation!

 ERROR  No solutions for compound=C25711 (comp.reactions.ids=[3060])!

 ERROR  Reactants not available for reaction=R3072: C121572 + C125278 -> C25838 via Amidation!

 ERROR  No solutions for compound=C25838 (comp.reactions.ids=[3072])!

 ERROR  Reactants not available for reaction=R3073: C121572 + C126337 -> C25919 via Ester_amidation!

 ERROR  No solutions for compound=C25919 (comp.reactions.ids=[3073])!

 ERROR  Reactants not available for reaction=R2700: C121535 + C125876 -> C27384 via Amidation!

 ERROR  No solutions for compound=C27384 (comp.reactions.ids=[2700])!

 ERROR  Reactants not available for reaction=R4662: C121535 + C128455 -> C27587 via Amidation!

 ERROR  No solutions for compound=C27587 (comp.reactions.ids=[4662])!

 ERROR  No solutions for compound=C28494 (comp.reactions.ids=[3377])!

 ERROR  Reactants not available for reaction=R3037: C124268 + C126293 -> C29014 via Amidation!

 ERROR  No solutions for compound=C29014 (comp.reactions.ids=[3037])!

 ERROR  Reactants not available for reaction=R3414: C121603 + C126751 -> C30267 via
Reductive_amination!

 ERROR  No solutions for compound=C30267 (comp.reactions.ids=[3414])!

 ERROR  Reactants not available for reaction=R2210: C61484 + C125108 -> C30679 via Amidation!

 ERROR  No solutions for compound=C30679 (comp.reactions.ids=[2210])!

 ERROR  Reactants not available for reaction=R3504: C121262 + C126870 -> C30694 via Amidation!

 ERROR  No solutions for compound=C30694 (comp.reactions.ids=[3504])!

 ERROR  Reactants not available for reaction=R3734: C127158 + C127159 -> C32722 via Ester_amidation!

 ERROR  No solutions for compound=C32722 (comp.reactions.ids=[3734])!

 ERROR  Reactants not available for reaction=R4056: C121941 + C127616 -> C37012 via Amidation!

 ERROR  No solutions for compound=C37012 (comp.reactions.ids=[4056])!

 ERROR  Reactants not available for reaction=R4185: C121941 + C127780 -> C37554 via Amidation!

 ERROR  No solutions for compound=C37554 (comp.reactions.ids=[4185])!

 ERROR  Reactants not available for reaction=R1395: C61484 + C123895 -> C39542 via Amidation!

 ERROR  No solutions for compound=C39542 (comp.reactions.ids=[1395])!

 ERROR  Reactants not available for reaction=R2513: C125580 + C125581 -> C40283 via Amidation!

 ERROR  No solutions for compound=C40283 (comp.reactions.ids=[2513])!

 ERROR  No solutions for compound=C40445 (comp.reactions.ids=[4452])!

 ERROR  Reactants not available for reaction=R3467: C61484 + C126832 -> C41633 via Amidation!

 ERROR  No solutions for compound=C41633 (comp.reactions.ids=[3467])!

 ERROR  Reactants not available for reaction=R4558: C121262 + C128316 -> C41702 via Amidation!

 ERROR  No solutions for compound=C41702 (comp.reactions.ids=[4558])!

 ERROR  Reactants not available for reaction=R4565: C123714 + C128316 -> C41731 via Amidation!

 ERROR  No solutions for compound=C41731 (comp.reactions.ids=[4565])!

 ERROR  Reactants not available for reaction=R4638: C125580 + C128420 -> C42562 via Amidation!

 ERROR  No solutions for compound=C42562 (comp.reactions.ids=[4638])!

 ERROR  Reactants not available for reaction=R5344: C129593 + C129695 -> C47391 via Ester_amidation!

 ERROR  No solutions for compound=C47391 (comp.reactions.ids=[5344])!

 ERROR  Reactants not available for reaction=R5296: C124547 + C129100 -> C47569 via
Chan-Lam_coupling_(amination)!

 ERROR  No solutions for compound=C47569 (comp.reactions.ids=[5296])!

 ERROR  Reactants not available for reaction=R4793: C128706 + C128707 -> C47575 via Amidation!

 ERROR  No solutions for compound=C47575 (comp.reactions.ids=[4793])!

 ERROR  Reactants not available for reaction=R4729: C128596 + C128597 -> C47615 via
Formation_of_urea_from_two_amines!

 ERROR  No solutions for compound=C47615 (comp.reactions.ids=[4729])!

 ERROR  Reactants not available for reaction=R5018: C129101 + C129102 -> C47682 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C47682 (comp.reactions.ids=[5018])!

 ERROR  Reactants not available for reaction=R4780: C124261 + C128692 -> C47891 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C47891 (comp.reactions.ids=[4780])!

 ERROR  Reactants not available for reaction=R4704: C128535 + C128536 -> C48202 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C48202 (comp.reactions.ids=[4704])!

 ERROR  Reactants not available for reaction=R4819: C128614 + C128754 -> C48411 via Amidation!

 ERROR  No solutions for compound=C48411 (comp.reactions.ids=[4819])!

 ERROR  Reactants not available for reaction=R5322: C129654 + C129655 -> C48535 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C48535 (comp.reactions.ids=[5322])!

 ERROR  Reactants not available for reaction=R4828: C128467 + C128768 -> C48727 via Amidation!

 ERROR  No solutions for compound=C48727 (comp.reactions.ids=[4828])!

 ERROR  Reactants not available for reaction=R4865: C121715 + C128837 -> C48815 via Amidation!

 ERROR  No solutions for compound=C48815 (comp.reactions.ids=[4865])!

 ERROR  Reactants not available for reaction=R5097: C129014 + C129274 -> C49235 via Amidation!

 ERROR  No solutions for compound=C49235 (comp.reactions.ids=[5097])!

 ERROR  Reactants not available for reaction=R4699: C121715 + C128524 -> C49318 via Amidation!

 ERROR  No solutions for compound=C49318 (comp.reactions.ids=[4699])!

 ERROR  Reactants not available for reaction=R4909: C128573 + C128914 -> C49351 via Ester_amidation!

 ERROR  No solutions for compound=C49351 (comp.reactions.ids=[4909])!

 ERROR  Reactants not available for reaction=R4944: C128563 + C128977 -> C49548 via Ester_amidation!

 ERROR  No solutions for compound=C49548 (comp.reactions.ids=[4944])!

 ERROR  Reactants not available for reaction=R4877: C121388 + C128853 + C128854 -> C49916 via
Petasis-borono_Mannich_reaction!

 ERROR  No solutions for compound=C49916 (comp.reactions.ids=[4877])!

 ERROR  Reactants not available for reaction=R4745: C128565 + C128627 -> C50069 via
Chan-Lam_coupling_(amination)!

 ERROR  No solutions for compound=C50069 (comp.reactions.ids=[4745])!

 ERROR  Reactants not available for reaction=R4970: C128682 + C129022 -> C50342 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C50342 (comp.reactions.ids=[4970])!

 ERROR  Reactants not available for reaction=R4773: C128682 + C128683 -> C50347 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C50347 (comp.reactions.ids=[4773])!

 ERROR  Reactants not available for reaction=R4765: C128666 + C128667 -> C50700 via Amidation!

 ERROR  No solutions for compound=C50700 (comp.reactions.ids=[4765])!

 ERROR  Reactants not available for reaction=R4755: C128649 + C128650 -> C50822 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C50822 (comp.reactions.ids=[4755])!

 ERROR  Reactants not available for reaction=R4929: C128563 + C128950 -> C50975 via Ester_amidation!

 ERROR  No solutions for compound=C50975 (comp.reactions.ids=[4929])!

 ERROR  Reactants not available for reaction=R4735: C51329 + C128607 -> C51334 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C51334 (comp.reactions.ids=[4735])!

 ERROR  Reactants not available for reaction=R4693: C124467 + C128511 -> C51629 via
Reductive_amination!

 ERROR  No solutions for compound=C51629 (comp.reactions.ids=[4693])!

 ERROR  Reactants not available for reaction=R4911: C128918 + C128919 -> C52810 via Amidation!

 ERROR  No solutions for compound=C52810 (comp.reactions.ids=[4911])!

 ERROR  Reactants not available for reaction=R4732: C128602 + C128603 -> C52864 via Amidation!

 ERROR  No solutions for compound=C52864 (comp.reactions.ids=[4732])!

 ERROR  Reactants not available for reaction=R4849: C128706 + C128806 -> C52886 via Amidation!

 ERROR  No solutions for compound=C52886 (comp.reactions.ids=[4849])!

 ERROR  Reactants not available for reaction=R4851: C128706 + C128809 -> C52892 via Amidation!

 ERROR  No solutions for compound=C52892 (comp.reactions.ids=[4851])!

 ERROR  Reactants not available for reaction=R4708: C128488 + C128549 -> C53672 via Amidation!

 ERROR  No solutions for compound=C53672 (comp.reactions.ids=[4708])!

 ERROR  Reactants not available for reaction=R4857: C52463 + C128819 -> C54372 via Ester_amidation!

 ERROR  No solutions for compound=C54372 (comp.reactions.ids=[4857])!

 ERROR  Reactants not available for reaction=R5102: C121476 + C128993 -> C55265 via Amidation!

 ERROR  No solutions for compound=C55265 (comp.reactions.ids=[5102])!

 ERROR  Reactants not available for reaction=R4953: C128992 + C128993 -> C55296 via Amidation!

 ERROR  No solutions for compound=C55296 (comp.reactions.ids=[4953])!

 ERROR  Reactants not available for reaction=R4815: C121239 + C128745 + C128746 -> C55341 via
Passerini_reaction!

 ERROR  No solutions for compound=C55341 (comp.reactions.ids=[4815])!

 ERROR  Reactants not available for reaction=R4966: C129015 + C129016 -> C56096 via Amidation!

 ERROR  No solutions for compound=C56096 (comp.reactions.ids=[4966])!

 ERROR  Reactants not available for reaction=R4892: C128794 + C128880 -> C56123 via Amidation!

 ERROR  No solutions for compound=C56123 (comp.reactions.ids=[4892])!

 ERROR  Reactants not available for reaction=R4940: C56431 + C128972 -> C56453 via Amidation!

 ERROR  No solutions for compound=C56453 (comp.reactions.ids=[4940])!

 ERROR  Reactants not available for reaction=R5441: C128763 + C129864 -> C56485 via Amidation!

 ERROR  No solutions for compound=C56485 (comp.reactions.ids=[5441])!

 ERROR  Reactants not available for reaction=R4883: C128864 + C128865 -> C57127 via Amidation!

 ERROR  No solutions for compound=C57127 (comp.reactions.ids=[4883])!

 ERROR  Reactants not available for reaction=R5130: C129332 + C129333 -> C57814 via Amidation!

 ERROR  No solutions for compound=C57814 (comp.reactions.ids=[5130])!

 ERROR  Reactants not available for reaction=R5386: C129716 + C129760 -> C58230 via Amidation!

 ERROR  No solutions for compound=C58230 (comp.reactions.ids=[5386])!

 ERROR  Reactants not available for reaction=R5385: C129758 + C129759 -> C58323 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C58323 (comp.reactions.ids=[5385])!

 ERROR  Reactants not available for reaction=R5403: C129801 + C129802 -> C58383 via Amidation!

 ERROR  No solutions for compound=C58383 (comp.reactions.ids=[5403])!

 ERROR  Reactants not available for reaction=R5199: C128751 + C129460 -> C58418 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C58418 (comp.reactions.ids=[5199])!

 ERROR  Reactants not available for reaction=R5390: C121276 + C129772 -> C58510 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C58510 (comp.reactions.ids=[5390])!

 ERROR  Reactants not available for reaction=R5459: C128631 + C129887 -> C58566 via Ester_amidation!

 ERROR  No solutions for compound=C58566 (comp.reactions.ids=[5459])!

 ERROR  Reactants not available for reaction=R5159: C121388 + C125675 + C129378 -> C58664 via
Petasis-borono_Mannich_reaction!

 ERROR  No solutions for compound=C58664 (comp.reactions.ids=[5159])!

 ERROR  Reactants not available for reaction=R5095: C128682 + C129271 -> C58699 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C58699 (comp.reactions.ids=[5095])!

 ERROR  Reactants not available for reaction=R5215: C121388 + C129485 -> C58915 via
Reductive_amination!

 ERROR  No solutions for compound=C58915 (comp.reactions.ids=[5215])!

 ERROR  Reactants not available for reaction=R5125: C121388 + C129325 -> C58940 via
Reductive_amination!

 ERROR  No solutions for compound=C58940 (comp.reactions.ids=[5125])!

 ERROR  Reactants not available for reaction=R5181: C129430 + C129431 -> C59118 via Amidation!

 ERROR  No solutions for compound=C59118 (comp.reactions.ids=[5181])!

 ERROR  Reactants not available for reaction=R5305: C129626 + C129627 -> C59553 via Amidation!

 ERROR  No solutions for compound=C59553 (comp.reactions.ids=[5305])!

 ERROR  Reactants not available for reaction=R5107: C128544 + C129291 -> C59678 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C59678 (comp.reactions.ids=[5107])!

 ERROR  Reactants not available for reaction=R5177: C128870 + C129420 -> C59685 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C59685 (comp.reactions.ids=[5177])!

 ERROR  Reactants not available for reaction=R5241: C128539 + C129527 -> C59758 via Ester_amidation!

 ERROR  No solutions for compound=C59758 (comp.reactions.ids=[5241])!

 ERROR  No solutions for compound=C60075 (comp.reactions.ids=[5343])!

 ERROR  Reactants not available for reaction=R5232: C129516 + C129517 -> C60173 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C60173 (comp.reactions.ids=[5232])!

 ERROR  Reactants not available for reaction=R5243: C128835 + C129530 -> C60189 via Amidation!

 ERROR  No solutions for compound=C60189 (comp.reactions.ids=[5243])!

 ERROR  Reactants not available for reaction=R5153: C129301 + C129369 -> C60256 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C60256 (comp.reactions.ids=[5153])!

 ERROR  Reactants not available for reaction=R5136: C129301 + C129341 -> C60262 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C60262 (comp.reactions.ids=[5136])!

 ERROR  Reactants not available for reaction=R5373: C128848 + C129742 -> C60466 via Amidation!

 ERROR  No solutions for compound=C60466 (comp.reactions.ids=[5373])!

 ERROR  Reactants not available for reaction=R5306: C128751 + C129628 -> C60900 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C60900 (comp.reactions.ids=[5306])!

 ERROR  Reactants not available for reaction=R5144: C128830 + C129177 -> C61043 via
Buchwald-Hartwig_amination_with_aromatic_nh_intermolecular!

 ERROR  No solutions for compound=C61043 (comp.reactions.ids=[5144])!

 ERROR  Reactants not available for reaction=R5362: C129730 + C129731 -> C61214 via
Reductive_amination!

 ERROR  No solutions for compound=C61214 (comp.reactions.ids=[5362])!

 ERROR  Reactants not available for reaction=R5123: C121388 + C129320 -> C61429 via
Chan-Lam_coupling_(amination)!

 ERROR  No solutions for compound=C61429 (comp.reactions.ids=[5123])!

 ERROR  Reactants not available for reaction=R5096: C129272 + C129273 -> C61728 via Amidation!

 ERROR  No solutions for compound=C61728 (comp.reactions.ids=[5096])!

 ERROR  Reactants not available for reaction=R5127: C129326 + C129327 -> C61879 via
Chan-Lam_coupling_(amination)!

 ERROR  No solutions for compound=C61879 (comp.reactions.ids=[5127])!

 ERROR  Reactants not available for reaction=R5140: C129348 + C129349 -> C62049 via Amidation!

 ERROR  No solutions for compound=C62049 (comp.reactions.ids=[5140])!

 ERROR  Reactants not available for reaction=R5254: C129551 + C129552 -> C62079 via Ester_amidation!

 ERROR  No solutions for compound=C62079 (comp.reactions.ids=[5254])!

 ERROR  Reactants not available for reaction=R5150: C129364 + C129365 -> C62271 via Amidation!

 ERROR  No solutions for compound=C62271 (comp.reactions.ids=[5150])!

 ERROR  Reactants not available for reaction=R5189: C129442 + C129443 -> C63135 via
Reductive_amination!

 ERROR  No solutions for compound=C63135 (comp.reactions.ids=[5189])!

 ERROR  Reactants not available for reaction=R5210: C128794 + C129442 -> C63144 via Amidation!

 ERROR  No solutions for compound=C63144 (comp.reactions.ids=[5210])!

 ERROR  Reactants not available for reaction=R5128: C128790 + C129330 -> C63451 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C63451 (comp.reactions.ids=[5128])!

 ERROR  Reactants not available for reaction=R5145: C129357 -> C63995 via N-Boc_deprotection!

 ERROR  No solutions for compound=C63995 (comp.reactions.ids=[5145])!

 ERROR  Reactants not available for reaction=R5401: C121388 + C129798 -> C64060 via
Reductive_amination!

 ERROR  No solutions for compound=C64060 (comp.reactions.ids=[5401])!

 ERROR  Reactants not available for reaction=R5180: C129428 + C129429 -> C64185 via Amidation!

 ERROR  No solutions for compound=C64185 (comp.reactions.ids=[5180])!

 ERROR  Reactants not available for reaction=R5135: C128468 + C129340 -> C64246 via Amidation!

 ERROR  No solutions for compound=C64246 (comp.reactions.ids=[5135])!

 ERROR  Reactants not available for reaction=R5218: C128923 + C129492 -> C64917 via Amidation!

 ERROR  No solutions for compound=C64917 (comp.reactions.ids=[5218])!

 ERROR  Reactants not available for reaction=R5478: C128684 + C129924 -> C65201 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C65201 (comp.reactions.ids=[5478])!

 ERROR  Reactants not available for reaction=R5293: C129613 + C129614 -> C65501 via Amidation!

 ERROR  No solutions for compound=C65501 (comp.reactions.ids=[5293])!

 ERROR  Reactants not available for reaction=R5335: C124547 + C129674 -> C65583 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C65583 (comp.reactions.ids=[5335])!

 ERROR  Reactants not available for reaction=R5253: C129401 + C129550 -> C65748 via Amidation!

 ERROR  No solutions for compound=C65748 (comp.reactions.ids=[5253])!

 ERROR  Reactants not available for reaction=R5239: C121388 + C129525 -> C66102 via
Reductive_amination!

 ERROR  No solutions for compound=C66102 (comp.reactions.ids=[5239])!

 ERROR  Reactants not available for reaction=R5331: C129442 + C129669 -> C66486 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C66486 (comp.reactions.ids=[5331])!

 ERROR  Reactants not available for reaction=R5482: C129934 + C129935 -> C66713 via Amidation!

 ERROR  No solutions for compound=C66713 (comp.reactions.ids=[5482])!

 ERROR  Reactants not available for reaction=R5201: C59986 + C129466 -> C66767 via Ester_amidation!

 ERROR  No solutions for compound=C66767 (comp.reactions.ids=[5201])!

 ERROR  Reactants not available for reaction=R5244: C122378 + C128787 + C129378 -> C67052 via
Petasis-borono_Mannich_reaction!

 ERROR  No solutions for compound=C67052 (comp.reactions.ids=[5244])!

 ERROR  Reactants not available for reaction=R5437: C129858 + C129859 -> C67561 via Amidation!

 ERROR  No solutions for compound=C67561 (comp.reactions.ids=[5437])!

 ERROR  Reactants not available for reaction=R5433: C121783 + C129851 -> C67787 via Amidation!

 ERROR  No solutions for compound=C67787 (comp.reactions.ids=[5433])!

 ERROR  Reactants not available for reaction=R5195: C128513 + C129454 -> C67819 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C67819 (comp.reactions.ids=[5195])!

 ERROR  Reactants not available for reaction=R5435: C129855 + C129856 -> C68006 via Amidation!

 ERROR  No solutions for compound=C68006 (comp.reactions.ids=[5435])!

 ERROR  Reactants not available for reaction=R5133: C129336 + C129337 -> C68038 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C68038 (comp.reactions.ids=[5133])!

 ERROR  Reactants not available for reaction=R5463: C129891 + C129892 -> C68401 via Amidation!

 ERROR  No solutions for compound=C68401 (comp.reactions.ids=[5463])!

 ERROR  Reactants not available for reaction=R5237: C124467 + C129523 -> C68584 via
Reductive_amination!

 ERROR  No solutions for compound=C68584 (comp.reactions.ids=[5237])!

 ERROR  Reactants not available for reaction=R5228: C129327 + C129506 -> C68669 via
Chan-Lam_coupling_(amination)!

 ERROR  No solutions for compound=C68669 (comp.reactions.ids=[5228])!

 ERROR  Reactants not available for reaction=R5111: C121388 + C129296 + C129297 -> C69102 via
Petasis-borono_Mannich_reaction!

 ERROR  No solutions for compound=C69102 (comp.reactions.ids=[5111])!

 ERROR  Reactants not available for reaction=R5278: C129591 + C129592 -> C69798 via Amidation!

 ERROR  No solutions for compound=C69798 (comp.reactions.ids=[5278])!

 ERROR  Reactants not available for reaction=R5154: C124831 + C129371 -> C69897 via Amidation!

 ERROR  No solutions for compound=C69897 (comp.reactions.ids=[5154])!

 ERROR  Reactants not available for reaction=R5222: C129497 + C129498 -> C69989 via Amidation!

 ERROR  No solutions for compound=C69989 (comp.reactions.ids=[5222])!

 ERROR  Reactants not available for reaction=R583: C121993 + C122396 -> C70544 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C70544 (comp.reactions.ids=[583])!

 ERROR  Reactants not available for reaction=R175: C121610 + C121611 -> C71678 via Ester_amidation!

 ERROR  No solutions for compound=C71678 (comp.reactions.ids=[175])!

 ERROR  Reactants not available for reaction=R1840: C121697 + C124611 -> C71961 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C71961 (comp.reactions.ids=[1840])!

 ERROR  Reactants not available for reaction=R76: C121392 + C121393 -> C72111 via Ester_amidation!

 ERROR  No solutions for compound=C72111 (comp.reactions.ids=[76])!

 ERROR  Reactants not available for reaction=R254: C121799 + C121800 -> C72456 via
Buchwald-Hartwig_amination!

 ERROR  No solutions for compound=C72456 (comp.reactions.ids=[254])!

 ERROR  Reactants not available for reaction=R468: C121388 + C122217 -> C72742 via
Reductive_amination!

 ERROR  No solutions for compound=C72742 (comp.reactions.ids=[468])!

 ERROR  Reactants not available for reaction=R828: C122172 + C122834 -> C73774 via Amidation!

 ERROR  No solutions for compound=C73774 (comp.reactions.ids=[828])!

 ERROR  Reactants not available for reaction=R1258: C123625 + C123626 -> C74044 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C74044 (comp.reactions.ids=[1258])!

 ERROR  Reactants not available for reaction=R438: C122159 + C122160 -> C74379 via
Buchwald-Hartwig_amination!

 ERROR  No solutions for compound=C74379 (comp.reactions.ids=[438])!

 ERROR  Reactants not available for reaction=R1162: C123465 + C123466 -> C74668 via Amidation!

 ERROR  No solutions for compound=C74668 (comp.reactions.ids=[1162])!

 ERROR  Reactants not available for reaction=R1262: C61484 + C123633 -> C76312 via
Formation_of_urea_from_two_amines!

 ERROR  No solutions for compound=C76312 (comp.reactions.ids=[1262])!

 ERROR  Reactants not available for reaction=R850: C121258 + C122887 -> C76702 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C76702 (comp.reactions.ids=[850])!

 ERROR  Reactants not available for reaction=R1452: C61484 + C123994 -> C76842 via Amidation!

 ERROR  No solutions for compound=C76842 (comp.reactions.ids=[1452])!

 ERROR  Reactants not available for reaction=R758: C122713 + C122714 -> C77734 via
Chan-Lam_coupling_(amination)!

 ERROR  No solutions for compound=C77734 (comp.reactions.ids=[758])!

 ERROR  Reactants not available for reaction=R1364: C122061 + C123821 -> C77891 via Ester_amidation!

 ERROR  Reactants not available for reaction=R368: C122007 + C122008 -> C78518 via Amidation!

 ERROR  No solutions for compound=C78518 (comp.reactions.ids=[368])!

 ERROR  Reactants not available for reaction=R1631: C121296 + C124314 -> C79798 via
Buchwald-Hartwig_amination!

 ERROR  No solutions for compound=C79798 (comp.reactions.ids=[1631])!

 ERROR  Reactants not available for reaction=R436: C122156 + C122157 -> C82390 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C82390 (comp.reactions.ids=[436])!

 ERROR  Reactants not available for reaction=R478: C122156 + C122233 -> C82392 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C82392 (comp.reactions.ids=[478])!

 ERROR  Reactants not available for reaction=R437: C122156 + C122158 -> C82396 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C82396 (comp.reactions.ids=[437])!

 ERROR  Reactants not available for reaction=R945: C123061 + C123062 -> C83823 via Amidation!

 ERROR  No solutions for compound=C83823 (comp.reactions.ids=[945])!

 ERROR  Reactants not available for reaction=R1596: C122073 + C124260 -> C84470 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C84470 (comp.reactions.ids=[1596])!

 ERROR  Reactants not available for reaction=R443: C122171 + C122172 -> C85428 via Amidation!

 ERROR  No solutions for compound=C85428 (comp.reactions.ids=[443])!

 ERROR  Reactants not available for reaction=R499: C122258 + C122259 -> C86577 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C86577 (comp.reactions.ids=[499])!

 ERROR  Reactants not available for reaction=R1267: C123647 + C123648 -> C87280 via
Sp2-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C87280 (comp.reactions.ids=[1267])!

 ERROR  Reactants not available for reaction=R330: C121941 + C121942 -> C88951 via Amidation!

 ERROR  No solutions for compound=C88951 (comp.reactions.ids=[330])!

 ERROR  Reactants not available for reaction=R1473: C121262 + C124035 -> C89368 via Amidation!

 ERROR  No solutions for compound=C89368 (comp.reactions.ids=[1473])!

 ERROR  Reactants not available for reaction=R1017: C79 + C123170 -> C90238 via Amidation!

 ERROR  No solutions for compound=C90238 (comp.reactions.ids=[1017])!

 ERROR  Reactants not available for reaction=R1828: C121572 + C124594 -> C92187 via Amidation!

 ERROR  No solutions for compound=C92187 (comp.reactions.ids=[1828])!

 ERROR  Reactants not available for reaction=R1304: C123247 + C123723 -> C94869 via Amidation!

 ERROR  No solutions for compound=C94869 (comp.reactions.ids=[1304])!

 ERROR  Reactants not available for reaction=R835: C121953 + C122847 -> C97926 via Amidation!

 ERROR  No solutions for compound=C97926 (comp.reactions.ids=[835])!

 ERROR  Reactants not available for reaction=R838: C61484 + C122475 + C122859 -> C98782 via
Petasis-borono_Mannich_reaction!

 ERROR  No solutions for compound=C98782 (comp.reactions.ids=[838])!

 ERROR  Reactants not available for reaction=R1567: C61484 + C124208 -> C104657 via Amidation!

 ERROR  No solutions for compound=C104657 (comp.reactions.ids=[1567])!

 ERROR  Reactants not available for reaction=R1637: C124332 + C124333 -> C104986 via Amidation!

 ERROR  No solutions for compound=C104986 (comp.reactions.ids=[1637])!

 ERROR  Reactants not available for reaction=R834: C61484 + C122845 -> C106834 via Amidation!

 ERROR  No solutions for compound=C106834 (comp.reactions.ids=[834])!

 ERROR  Reactants not available for reaction=R5258: C129557 + C129558 -> C107300 via Amidation!

 ERROR  No solutions for compound=C107300 (comp.reactions.ids=[5258])!

 ERROR  Reactants not available for reaction=R5448: C129551 + C129876 -> C107312 via
Reductive_amination!

 ERROR  No solutions for compound=C107312 (comp.reactions.ids=[5448])!

 ERROR  Reactants not available for reaction=R5251: C129063 + C129544 -> C107415 via
Nucleophilic_substitution_with_thiol!

 ERROR  No solutions for compound=C107415 (comp.reactions.ids=[5251])!

 ERROR  Reactants not available for reaction=R5354: C121783 + C129715 -> C107637 via Amidation!

 ERROR  No solutions for compound=C107637 (comp.reactions.ids=[5354])!

 ERROR  Reactants not available for reaction=R5363: C129512 + C129732 -> C107730 via Amidation!

 ERROR  No solutions for compound=C107730 (comp.reactions.ids=[5363])!

 ERROR  Reactants not available for reaction=R5368: C129512 + C129736 -> C107736 via Amidation!

 ERROR  No solutions for compound=C107736 (comp.reactions.ids=[5368])!

 ERROR  Reactants not available for reaction=R5264: C129354 + C129568 -> C107948 via Amidation!

 ERROR  No solutions for compound=C107948 (comp.reactions.ids=[5264])!

 ERROR  Reactants not available for reaction=R5263: C129566 + C129567 -> C107987 via
Reductive_amination!

 ERROR  No solutions for compound=C107987 (comp.reactions.ids=[5263])!

 ERROR  Reactants not available for reaction=R5355: C129716 + C129717 -> C108362 via Amidation!

 ERROR  No solutions for compound=C108362 (comp.reactions.ids=[5355])!

 ERROR  Reactants not available for reaction=R5280: C129594 + C129595 -> C108558 via Amidation!

 ERROR  No solutions for compound=C108558 (comp.reactions.ids=[5280])!

 ERROR  Reactants not available for reaction=R5350: C124169 + C129706 -> C108668 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C108668 (comp.reactions.ids=[5350])!

 ERROR  Reactants not available for reaction=R5325: C129660 + C129661 -> C108810 via
Reductive_amination!

 ERROR  No solutions for compound=C108810 (comp.reactions.ids=[5325])!

 ERROR  Reactants not available for reaction=R5494: C121276 + C129962 -> C108830 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C108830 (comp.reactions.ids=[5494])!

 ERROR  Reactants not available for reaction=R5299: C129620 + C129621 -> C109564 via Amidation!

 ERROR  No solutions for compound=C109564 (comp.reactions.ids=[5299])!

 ERROR  Reactants not available for reaction=R5371: C128912 + C129740 -> C110092 via Amidation!

 ERROR  No solutions for compound=C110092 (comp.reactions.ids=[5371])!

 ERROR  Reactants not available for reaction=R5359: C129720 + C129721 -> C110236 via
Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

 ERROR  No solutions for compound=C110236 (comp.reactions.ids=[5359])!

 ERROR  Reactants not available for reaction=R5378: C122863 + C129748 -> C110691 via Amidation!

 ERROR  No solutions for compound=C110691 (comp.reactions.ids=[5378])!

 ERROR  Reactants not available for reaction=R4918: C128928 + C128929 -> C111176 via Amidation!

 ERROR  No solutions for compound=C111176 (comp.reactions.ids=[4918])!

 ERROR  Reactants not available for reaction=R5367: C122004 + C123296 + C128870 -> C111500 via
Petasis-borono_Mannich_reaction!

 ERROR  No solutions for compound=C111500 (comp.reactions.ids=[5367])!

 ERROR  Reactants not available for reaction=R5291: C128890 + C129611 -> C112324 via Amidation!

 ERROR  No solutions for compound=C112324 (comp.reactions.ids=[5291])!

 ERROR  Reactants not available for reaction=R5318: C128488 + C129649 -> C112643 via Amidation!

 ERROR  No solutions for compound=C112643 (comp.reactions.ids=[5318])!

 ERROR  Reactants not available for reaction=R4995: C122279 + C129062 -> C113623 via
S-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C113623 (comp.reactions.ids=[4995])!

 ERROR  Reactants not available for reaction=R4899: C114110 + C128897 -> C114112 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C114112 (comp.reactions.ids=[4899])!

 ERROR  Reactants not available for reaction=R4961: C129007 + C129008 -> C114416 via Amidation!

 ERROR  No solutions for compound=C114416 (comp.reactions.ids=[4961])!

 ERROR  Reactants not available for reaction=R4965: C128689 + C129014 -> C116358 via Amidation!

 ERROR  No solutions for compound=C116358 (comp.reactions.ids=[4965])!

 ERROR  Reactants not available for reaction=R5442: C122472 + C129865 -> C116405 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C116405 (comp.reactions.ids=[5442])!

 ERROR  Reactants not available for reaction=R4986: C128504 + C129049 -> C116793 via Amidation!

 ERROR  No solutions for compound=C116793 (comp.reactions.ids=[4986])!

 ERROR  Reactants not available for reaction=R4952: C128504 + C128991 -> C116809 via Amidation!

 ERROR  No solutions for compound=C116809 (comp.reactions.ids=[4952])!

 ERROR  Reactants not available for reaction=R4878: C128856 + C128857 -> C117036 via Ester_amidation!

 ERROR  No solutions for compound=C117036 (comp.reactions.ids=[4878])!

 ERROR  Reactants not available for reaction=R4987: C129050 + C129051 -> C117836 via Amidation!

 ERROR  No solutions for compound=C117836 (comp.reactions.ids=[4987])!

 ERROR  Reactants not available for reaction=R4923: C121715 + C128942 -> C117950 via Amidation!

 ERROR  No solutions for compound=C117950 (comp.reactions.ids=[4923])!

 ERROR  Reactants not available for reaction=R5413: C122004 + C129817 -> C119034 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C119034 (comp.reactions.ids=[5413])!

 ERROR  Reactants not available for reaction=R5414: C122004 + C129818 -> C119036 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C119036 (comp.reactions.ids=[5414])!

 ERROR  Reactants not available for reaction=R5424: C121603 + C129837 -> C119115 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C119115 (comp.reactions.ids=[5424])!

 ERROR  Reactants not available for reaction=R5427: C107788 + C129842 -> C119131 via
Reductive_amination!

 ERROR  No solutions for compound=C119131 (comp.reactions.ids=[5427])!

 ERROR  Reactants not available for reaction=R5430: C129838 + C129842 -> C119147 via
Reductive_amination!

 ERROR  No solutions for compound=C119147 (comp.reactions.ids=[5430])!

 ERROR  Reactants not available for reaction=R5431: C129842 + C129844 -> C119150 via
Reductive_amination!

 ERROR  No solutions for compound=C119150 (comp.reactions.ids=[5431])!

 ERROR  Reactants not available for reaction=R5438: C129860 + C129861 -> C119198 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C119198 (comp.reactions.ids=[5438])!

 ERROR  Reactants not available for reaction=R5440: C129860 + C129863 -> C119200 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C119200 (comp.reactions.ids=[5440])!

 ERROR  Reactants not available for reaction=R5456: C129323 + C129775 -> C119693 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C119693 (comp.reactions.ids=[5456])!

 ERROR  Reactants not available for reaction=R5426: C129282 + C129841 -> C119788 via Amidation!

 ERROR  No solutions for compound=C119788 (comp.reactions.ids=[5426])!

 ERROR  Reactants not available for reaction=R5475: C129919 + C129920 -> C120410 via
Williamson_ether_synthesis!

 ERROR  No solutions for compound=C120410 (comp.reactions.ids=[5475])!

Solving recipe combinations...

Output()

DEBUG: Calculating prices...

Picking cheapest from 1 options

Recipe({Ingredient × 740} --> {Ingredient × 2} --> {Ingredient × 459} via {R × 459})

In [7]:
# recipe.write_json("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_bbok.json")
recipe = hippo.Recipe.from_json(animal.db, "cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_bbok.json")

 DISK  Reading cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_bbok.json...

Recipe was generated at: 2025-10-01 15:55:52.866532

reactants = {Ingredient × 740}

intermediates = {Ingredient × 2}

products = {Ingredient × 459}

reactions = {R × 459}

compounds = {Ingredient × 0}

In [14]:
recipe.write_CAR_csv("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_bbok.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chem
ok_bbok_1steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chem
ok_bbok.csv...

,target-names,no-steps,concentration-required-mM,amount-required-uL,batch-tag,reactant-1-1,reactant-2-1,reaction-product-smiles-1,reaction-name-1,reaction-recipe-1,reaction-groupby-column-1,reactant-3-1
0,C62668,1,None,None,None,Cc1ccc(N)c2cccnc12,O=C(O)c1cccc2scnc12,Cc1ccc(NC(=O)c2cccc3scnc23)c2cccnc12,Amidation,None,None,<NA>
1,C61598,1,None,None,None,O=Cc1ccc2c(c1)CNC2,CCCCN,CCCCNCc1ccc2c(c1)CNC2,Reductive_amination,None,None,<NA>
2,C67555,1,None,None,None,O=C1CC(C(=O)O)CCN1,Nc1nnc(C2CCNC2)[nH]1,O=C1CC(C(=O)Nc2nnc(C3CCNC3)[nH]2)CCN1,Amidation,None,None,<NA>
3,C59954,1,None,None,None,CC(=O)O,NCC12CCCN1CCC2,CC(=O)NCC12CCCN1CCC2,Amidation,None,None,<NA>
4,C69956,1,None,None,None,NC1Cc2cscc2C1,COC(=O)c1cnc2c(C=O)cccn12,COC(=O)c1cnc2c(CNC3Cc4cscc4C3)cccn12,Reductive_amination,None,None,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...
454,C15530,1,None,None,None,CC(=O)O,NCC1CCNC(=O)C1,CC(=O)NCC1CCNC(=O)C1,Amidation,None,None,<NA>
455,C14578,1,None,None,None,Clc1ccc2c(c1)CNC2,O=C(O)c1ccncn1,O=C(c1ccncn1)N1Cc2ccc(Cl)cc2C1,Amidation,None,None,<NA>
456,C5939,1,None,None,None,CCNCc1cccnc1,COc1ccn2c(C(=O)O)cnc2c1,CCN(Cc1cccnc1)C(=O)c1cnc2cc(OC)ccn12,Amidation,None,None,<NA>
457,C64802,1,None,None,None,O=C(O)c1cccc2cn[nH]c12,Nc1nc(-c2cnco2)cs1,O=C(Nc1nc(-c2cnco2)cs1)c1cccc2cn[nH]c12,Amidation,None,None,<NA>
458,C65714,1,None,None,None,O=C(O)c1csc2nccn12,CCOC(C)c1nc(CNC)cs1,CCOC(C)c1nc(CN(C)C(=O)c2csc3nccn23)cs1,Amidation,None,None,<NA>

In [16]:
df = recipe.write_reactant_csv("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_bbok_reactants.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

 DISK  Writing cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_bbok_reactants.csv...

In [17]:
recipe.write_product_csv("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_bbok_products.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

Output()

Output()

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 recipe.write_product_csv("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_b     │
│   2                                                                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ aligned_dir = PosixPath('/opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/XX01ZVNS2B/aligned… │ │
│ │      animal = HIPPO("XX01ZVNS2B")                                                            │ │
│ │        bbdb = HIPPO("BB")                                                                    │ │
│ │        cset = {C × 767}                                                                      │ │
│ │   cycle_dir = PosixPath('cycle_01')                                                          │ │
│ │  cycle_name = 'cycle_01'                                                                     │ │
│ │          df = None                                                                           │ │
│ │     environ = environ({                                                                      │ │
│ │               │   'HYDRA_LAUNCHER_EXTRA_ARGS': '--external-launcher',                        │ │
│ │               │   'PRECURSOR': '/opt/xchem-fragalysis-2/maxwin/2A_Precursor_FFF',            │ │
│ │               │   'MAMBA_ALWAYS_YES': 'yes',                                                 │ │
│ │               │   'CONDA_SHLVL': '1',                                                        │ │
│ │               │   'LD_LIBRARY_PATH':                                                         │ │
│ │               '/usr/local/cuda/compat:/opt/xchem-fragalysis-2/maxwin/conda/lib:/dls_sw/epic… │ │
│ │               │   'LS_COLORS':                                                               │ │
│ │               'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;… │ │
│ │               │   'CONDA_EXE': '/opt/xchem-fragalysis-2/maxwin/conda/bin/conda',             │ │
│ │               │   'SLURM_NODEID': '0',                                                       │ │
│ │               │   'SLURM_TASK_PID': '157145',                                                │ │
│ │               │   'SSH_CONNECTION': '172.23.162.11 43788 172.23.176.6 22',                   │ │
│ │               │   ... +131                                                                   │ │
│ │               })                                                                             │ │
│ │        exit = <IPython.core.autocall.ZMQExitAutocall object at 0x7f811ccbf920>               │ │
│ │ get_ipython = <bound method InteractiveShell.get_ipython of                                  │ │
│ │               <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f811ceeda30>>             │ │
│ │       hippo = <module 'hippo' from                                                           │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages… │ │
│ │         ids = [                                                                              │ │
│ │               │   62668,                                                                     │ │
│ │               │   55265,                                                                     │ │
│ │               │   67555,                                                                     │ │
│ │               │   59954,                                                                     │ │
│ │               │   56722,                                                                     │ │
│ │               │   64151,                                                                     │ │
│ │               │   63174,                                                                     │ │
│ │               │   58144,                                                                     │ │
│ │               │   61950,                                                                     │ │
│ │               │   7770,                                                                      │ │
│ │               │   ... +757                                                                   │ │
│ │               ]                                                                              │ │
│ │          In = [                                                                              │ │
│ │               │   '',                                                                        │ │
│ │               │   'target_name = "XX01ZVNS2B"\ntarget_dir = Path(environ["BULK"]) /          │ │
│ │               "TARGETS" / targ'+103,                                                         │ │
│ │               │   "get_ipython().run_line_magic('load_ext',                                  │ │
│ │               'autoreload')\nget_ipython().run_line_ma"+204,                                 │ │
│ │               │   'target_name = "XX01ZVNS2B"\ntarget_dir = Path(environ["BULK"]) /          │ │
│ │               "TARGETS" / targ'+103,                                                         │ │
│ │               │   'animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")', │ │
│ │               │   'df =                                                                      │ │
│ │               pd.read_excel("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_1steps'+… │ │
│ │               │   'df =                                                                      │ │
│ │               pd.read_excel("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_1steps'+… │ │
│ │               │   'df.iloc[0]',                                                              │ │
│ │               │   'select = df[df["lisa-select"]=="Y"]\nlen(select)',                        │ │
│ │               │   'ids = [int(cname[1:]) for cname in select["target-names"]]\ncset =        │ │
│ │               animal.compoun'+68,                                                            │ │
│ │               │   ... +8                                                                     │ │
│ │               ]                                                                              │ │
│ │          mp = <module 'molparse' from                                                        │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages… │ │
│ │       mrich = <module 'mrich' from                                                           │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages… │ │
│ │         Out = {                                                                              │ │
│ │               │   7: target-names                                                            │ │
│ │               C109749                                                                        │ │
│ │               no-steps                                                                     1 │ │
│ │               concentration-required-mM                                                  NaN │ │
│ │               amount-required-uL                                                         NaN │ │
│ │               batch-tag                                                                  NaN │ │
│ │               reactant-1-1                                                             NC=NO │ │
│ │               reactant-2-1                                              COC(=O)c1cnn2c1CNCC2 │ │
│ │               reaction-product-smiles-1                              c1noc(-c2cnn3c2CNCC3)n1 │ │
│ │               reaction-name-1              1,2,4-Oxadiazole_synthesis_(amidoxime_+_carbox... │ │
│ │               reaction-recipe-1                                                          NaN │ │
│ │               reaction-groupby-column-1                                                  NaN │ │
│ │               reactant-3-1                                                               NaN │ │
│ │               reactant-4-1                                                               NaN │ │
│ │               warren-select                                                              NaN │ │
│ │               lisa-select                                                                  N │ │
│ │               Unnamed: 15                                                                NaN │ │
│ │               Name: 0, dtype: object,                                                        │ │
│ │               │   8: 767,                                                                    │ │
│ │               │   9: {C × 767},                                                              │ │
│ │               │   12: Recipe({Ingredient × 740} --> {Ingredient × 2} --> {Ingredient × 459}  │ │
│ │               via {R × 459}),                                                                │ │
│ │               │   14:     target-names  no-steps concentration-required-mM                   │ │
│ │               amount-required-uL  \                                                          │ │
│ │               0         C62668         1                      None               None        │ │
│ │               1         C61598         1                      None               None        │ │
│ │               2         C67555         1                      None               None        │ │
│ │               3         C59954         1                      None               None        │ │
│ │               4         C69956         1                      None               None        │ │
│ │               ..           ...       ...                       ...                ...        │ │
│ │               454       C15530         1                      None               None        │ │
│ │               455       C14578         1                      None               None        │ │
│ │               456        C5939         1                      None               None        │ │
│ │               457       C64802         1                      None               None        │ │
│ │               458       C65714         1                      None               None        │ │
│ │               │                                                                              │ │
│ │               │   batch-tag            reactant-1-1               reactant-2-1  \            │ │
│ │               0        None      Cc1ccc(N)c2cccnc12        O=C(O)c1cccc2scnc12               │ │
│ │               1        None      O=Cc1ccc2c(c1)CNC2                      CCCCN               │ │
│ │               2        None      O=C1CC(C(=O)O)CCN1       Nc1nnc(C2CCNC2)[nH]1               │ │
│ │               3        None                 CC(=O)O             NCC12CCCN1CCC2               │ │
│ │               4        None           NC1Cc2cscc2C1  COC(=O)c1cnc2c(C=O)cccn12               │ │
│ │               ..        ...                     ...                        ...               │ │
│ │               454      None                 CC(=O)O             NCC1CCNC(=O)C1               │ │
│ │               455      None       Clc1ccc2c(c1)CNC2             O=C(O)c1ccncn1               │ │
│ │               456      None            CCNCc1cccnc1    COc1ccn2c(C(=O)O)cnc2c1               │ │
│ │               457      None  O=C(O)c1cccc2cn[nH]c12         Nc1nc(-c2cnco2)cs1               │ │
│ │               458      None      O=C(O)c1csc2nccn12        CCOC(C)c1nc(CNC)cs1               │ │
│ │               │   │   │   │                                                                  │ │
│ │               │   │   │   │      reaction-product-smiles-1      reaction-name-1  \           │ │
│ │               0       Cc1ccc(NC(=O)c2cccc3scnc23)c2cccnc12            Amidation              │ │
│ │               1                      CCCCNCc1ccc2c(c1)CNC2  Reductive_amination              │ │
│ │               2      O=C1CC(C(=O)Nc2nnc(C3CCNC3)[nH]2)CCN1            Amidation              │ │
│ │               3                       CC(=O)NCC12CCCN1CCC2            Amidation              │ │
│ │               4       COC(=O)c1cnc2c(CNC3Cc4cscc4C3)cccn12  Reductive_amination              │ │
│ │               ..                                       ...                  ...              │ │
│ │               454                     CC(=O)NCC1CCNC(=O)C1            Amidation              │ │
│ │               455           O=C(c1ccncn1)N1Cc2ccc(Cl)cc2C1            Amidation              │ │
│ │               456     CCN(Cc1cccnc1)C(=O)c1cnc2cc(OC)ccn12            Amidation              │ │
│ │               457  O=C(Nc1nc(-c2cnco2)cs1)c1cccc2cn[nH]c12            Amidation              │ │
│ │               458   CCOC(C)c1nc(CN(C)C(=O)c2csc3nccn23)cs1            Amidation              │ │
│ │               │                                                                              │ │
│ │               │   reaction-recipe-1 reaction-groupby-column-1 reactant-3-1                   │ │
│ │               0                None                      None         <NA>                   │ │
│ │               1                None                      None         <NA>                   │ │
│ │               2                None                      None         <NA>                   │ │
│ │               3                None                      None         <NA>                   │ │
│ │               4                None                      None         <NA>                   │ │
│ │               ..                ...                       ...          ...                   │ │
│ │               454              None                      None         <NA>                   │ │
│ │               455              None                      None         <NA>                   │ │
│ │               456              None                      None         <NA>                   │ │
│ │               457              None                      None         <NA>                   │ │
│ │               458              None                      None         <NA>                   │ │
│ │                                                                                              │ │
│ │               [459 rows x 12 columns]                                                        │ │
│ │               }                                                                              │ │
│ │          pd = <module 'pandas' from                                                          │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/lib/python3.12/site-packages/pandas/__i… │ │
│ │          px = <module 'plotly.express' from                                                  │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages… │ │
│ │        quit = <IPython.core.autocall.ZMQExitAutocall object at 0x7f811ccbf920>               │ │
│ │      recipe = Recipe({Ingredient × 740} --> {Ingredient × 2} --> {Ingredient × 459} via {R × │ │
│ │               459})                                                                          │ │
│ │      select = │   target-names  no-steps  concentration-required-mM  amount-required-uL  \   │ │
│ │               19        C62668         1                        NaN                 NaN      │ │
│ │               20        C55265         1                        NaN                 NaN      │ │
│ │               21        C67555         1                        NaN                 NaN      │ │
│ │               22        C59954         1                        NaN                 NaN      │ │
│ │               23        C56722         1                        NaN                 NaN      │ │
│ │               ..           ...       ...                        ...                 ...      │ │
│ │               899        C3980         1                        NaN                 NaN      │ │
│ │               900        C5811         1                        NaN                 NaN      │ │
│ │               901        C3197         1                        NaN                 NaN      │ │
│ │               905       C70416         1                        NaN                 NaN      │ │
│ │               906      C120410         1                        NaN                 NaN      │ │
│ │               │                                                                              │ │
│ │               │    batch-tag                 reactant-1-1  \                                 │ │
│ │               19         NaN           Cc1ccc(N)c2cccnc12                                    │ │
│ │               20         NaN                     O=C(O)CO                                    │ │
│ │               21         NaN           O=C1CC(C(=O)O)CCN1                                    │ │
│ │               22         NaN                      CC(=O)O                                    │ │
│ │               23         NaN                  CC(O)C(=O)O                                    │ │
│ │               ..         ...                          ...                                    │ │
│ │               899        NaN   O=S(=O)(Cl)Cc1cccc2cccnc12                                    │ │
│ │               900        NaN           COc1ccc2cccnc2c1CN                                    │ │
│ │               901        NaN  O=[N+]([O-])c1ccc2c(c1)CNC2                                    │ │
│ │               905        NaN           Cc1nc2cc(O)ccc2n1C                                    │ │
│ │               906        NaN                 OCc1ccn[nH]1                                    │ │
│ │               │   │   │   │   │   │                                                          │ │
│ │               │   │   │   │   │   │      reactant-2-1  \                                     │ │
│ │               19                  O=C(O)c1cccc2scnc12                                        │ │
│ │               20   CC(N)C1CCCCN1C(=O)c1cccc2[nH]cnc12                                        │ │
│ │               21                 Nc1nnc(C2CCNC2)[nH]1                                        │ │
│ │               22                       NCC12CCCN1CCC2                                        │ │
│ │               23                             Nc1nccs1                                        │ │
│ │               ..                                  ...                                        │ │
│ │               899                         CNCc1scnc1C                                        │ │
│ │               900                 O=S(=O)(Cl)c1ccccn1                                        │ │
│ │               901                 O=S(=O)(Cl)Cc1cscn1                                        │ │
│ │               905                    CC(C)CCNC(=O)CCl                                        │ │
│ │               906                        O=C1CCNCC1Br                                        │ │
│ │               │   │   │   │   │   │                                                          │ │
│ │               │   │   │   │   │   │     reaction-product-smiles-1  \                         │ │
│ │               19             Cc1ccc(NC(=O)c2cccc3scnc23)c2cccnc12                            │ │
│ │               20        CC(NC(=O)CO)C1CCCCN1C(=O)c1cccc2[nH]cnc12                            │ │
│ │               21            O=C1CC(C(=O)Nc2nnc(C3CCNC3)[nH]2)CCN1                            │ │

## Adjust recipe to quote

In [17]:
cset = recipe.product_compounds
cset

products of Recipe: {C × 459}

In [ ]:
animal.add_enamine_quote(
        path = "cycle_01/enamine/Q2103090_EUR_xx01zvns2b_c1_scaffolds.xlsx",
        orig_name_col = 'Customer ID',
        entry_col = "Catalog ID",
        orig_name_is_hippo_id = True,
        overwrite_existing_quotes = True,
)

Output()

 Warning  Deleting 'Enamine' quotes for C3704 "ARRFOXUKDPWVLK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C9828 "NAPZUNQCBHIRPL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C119036 "XCVZGODKCMUNAW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C113775 "ZSKRPIHLDOVWJV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C90516 "JFMRJEILBGYUAQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59573 "FUHXPNDCMONPKK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C55804 "AOOQBDNCKQBUCV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C108810 "PPDIMXJEBMYPTH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C50104 "JDXDOGRTSMSHQM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C114112 "HJXSPPNNOFQPBR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C60849 "DGGHJVRDXKKTJG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C9562 "GFOXOCSROBMKHG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C3291 "PPKMWKRMHCXNFG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C10523 "KVWQXXISWMUKTC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C17132 "JYDITVTUGASXHF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C65943 "DFYPNMWDFSAPNK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C69989 "MUMVNMUCHURAAO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C3506 "GZBNTRYJDBCHOB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30267 "QVTSZFHGHGFIQG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C47569 "OLASSUAKDLYHHS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C118458 "LVKLKYYOOQHENY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C8326 "VSKZGHVPGOMFAV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C61503 "SFQSDWUKOWQCPC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C107817 "MHNHXXDHQTVCBW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C107866 "BKOXWQQDKDZJBL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C107312 "XOHTWQXKVGQMAZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59020 "HKGPXKKPGUKDKZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59684 "FAWKTAUBPNRVDS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C61450 "YDYQRPXCINJZCL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C6746 "CHDWRFSPHQSJIW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C61750 "MMOYNOVVZMWGSB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C14573 "HEUOYJDCAULSSE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C626 "QCRQWROCTYVPLG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C56919 "DAYCWWYRTUMGON-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C50342 "RSWGQICJEZWFAK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C74617 "SUNGCYDMHSJMKM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30724 "GJEHOASEJCCAPR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C67555 "KJFFAXCABFDIQL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29014 "VXTHLTZUMGZYJF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42930 "KFRQQHKCAAYRIQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C48749 "XYOFFROFSMOCNR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C48944 "BVYVEUDQHBUNQG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C52423 "FNKZZTCAOJDNKB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C90307 "LQEHWZPIDXWLPQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18052 "TYDNSYHYVMCUOX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19055 "GKAUMNZATPDVHS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20158 "GPLJMDMYZCMRCG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21528 "GEVZCSAWDOHYLB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23024 "KKPUOEAHHZGJFV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24260 "SXXMQNHIBCGDQG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25614 "RRWRSSRXUJFXRE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27323 "KYHPNYLXOLFKTH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29550 "LNSUTYDCFRSLPH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31624 "YKOSRQSWAICXPZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33082 "GQHAZXGWQQMAIL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34889 "ADGZVADNSSUAGK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36738 "RNPVISUASCAWBG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37403 "OVCLBNQEVQXDTP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38791 "PHCDQWZFJDGHNH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41125 "QFAKIMAPEIWQSG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42698 "WUVCUBOQEWEPNR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71612 "VAPJXIZHWUNPEE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C74716 "VVIQUAPDAKTCIK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C79587 "LQUBJHVXTYJOSP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C84025 "WQZLXTMOATUVDM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C87620 "HAXDRZZTJPLCQY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C91675 "RIIUGQAOPGSFJS-UHFFFAOYSA-O"!

 Warning  Deleting 'Enamine' quotes for C95075 "NJIXTUXVVAUFHI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C99819 "LRRXLZQVPVVSBU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C103272 "SBWSSYDTQTWLJX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C106063 "QNLQVKVPPIWIJI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C62695 "DJDBCDKBTQCNTO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C64917 "MBTBHVMVVGWRDZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C67611 "WOFQUGUOWDLCQY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C68259 "UGFIGTZTUJNRDR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C56508 "DTRGKYDONNPFAX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C14536 "VDUXJDKQPXGOQY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C4958 "SFFGTUWFWSMHCZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C9739 "TZPGJCRKXCVWJW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C14548 "FMCJOZPRLVUXJB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C52810 "HAFNKRRKELEHKA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C52886 "HNNBCZCRFMNSIP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C56123 "GQDRHLMPTNGJGA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C112324 "JDGBBORGRFXTJC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C47653 "ZHIVUAXWJHYVJQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C118843 "SNKXIENPXGZURO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C108669 "QIJMCQLDEVOUOI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C51629 "XGMUYUWJAQFZKN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C4305 "VTLIUSHGRJAXSK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C110260 "WBRVEYVJNBBESA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59260 "GEKOOXNRCYJUMJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C7420 "SGFUMUYBGPAJPY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C107415 "FTQNISICHUKXSQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C64060 "ARIBPNACTHQUIK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59124 "YOYKFUJSSXMYOD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C5440 "UGHMAQBZWONQLH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70478 "UMTKULONWPJCOZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C107290 "QFKFMGJMIZTFDN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C107274 "ULHUHMIJEUORHB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C107279 "XHSJYGGVMWCNOS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C118995 "JRCRPUGDMKLCQO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59808 "ZFEZBINVSXMQST-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C89721 "UWAJJKJNFPOWKJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C65217 "VRADJHFOQVKIBY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C48044 "ZHANAJIUUIAQKB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C119048 "BONVFUQVDRFJAL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C11823 "SGEUOMSGSCTGMA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C58664 "KJHBNMPPZGCARH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C108806 "BZIPVVILBPAWCF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70364 "TVKBRMMOPCQDOT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C61815 "FDYDGTDZUXFSHV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C61598 "HIUAAHJQXHUFBW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C66102 "CCCBUROPFUHOJP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C55674 "AJYXWVFXJSQKFI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C359 "LPJGXSNANGMUHE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C2852 "BBSVLOOZYCBDPW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C69254 "RDSLFWXGEZYMRJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C119115 "AXEFTCTYVXWSFI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C2648 "HIFXZHKWHHGBQM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C7556 "ULYDAMBPGPFUNZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C60466 "WKXKBLINEJKBIV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C51334 "IEDYRQDMLQQEPF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C72742 "UHFDIJIKGBDNFW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18645 "IUVZMVXGFAOWKY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19684 "FPOWIVCDQRNFAO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20962 "ZULVXUCHQSNFII-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22626 "OGQRRHGNKQNFSE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23503 "XAMKNXFIWQPDEG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24931 "KERKRUPGXVPAQM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26950 "UUCYBDWWYLBZPL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28504 "YELJAZGYCPJSAD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30669 "DADDILTUKIVOIO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32396 "FZQCEHZWBDYBSO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33905 "RLDYYEMISNZDBJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35533 "CJLQVEFFBCSGBE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37054 "CXOUXDGZMIEMAJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37985 "MXJFFQVQURWVLK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40129 "IHKWOSOGDRIGGK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41797 "RXDSTYKMTIZDDZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71197 "PYMFSXVDTCLIMA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C73807 "AGZHZNUQNVNHQR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C78588 "PLQGNVTWRSVNLO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C83066 "MSADLZHBZVORBF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C86825 "FQEUSXBBEGLWEN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C90779 "GYKIBNJFRQBKLE-UHFFFAOYSA-O"!

 Warning  Deleting 'Enamine' quotes for C93945 "WIDJTPHUKXUIQS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C98843 "VLHJFFXOKKXHIW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C102521 "HUGPCRXFFAETQM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C105193 "RRTWQMLBDYFHQH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19221 "XATBKAQHYZAGIN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20547 "AGYOOHJCOXDSGO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23025 "HGADZAHGRRCGMD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24690 "FWIMKSYILJBGGS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27227 "KSCJUMODTOECTF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29564 "WAUJWCYXYJTGHO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31721 "AHRVJMRCBWTGRF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33288 "GBIKHWLGUOIPIK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33697 "NMVDLTXXDUXRMH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36212 "VGAFFEGIJSBQEA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37019 "SRVWTHLIRXJFNL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42000 "MBTVRRIHUJSQRH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42554 "HKLVCWKWNBMABS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43150 "GKRCRPXNRJFSIF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C74564 "JSWJFJDGJZDXIN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C75516 "LSOXJIZLKHKDEJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C79737 "ALQHLCFXWCGWIZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C86939 "QKHNFMBKLCSWGS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C88542 "HWEHHFPTYJERRQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C99711 "NPOCZCRWVRDMGE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C60616 "MSOXWHJHAGZIKH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C10247 "UFUUUCAFSXJZMO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C13046 "JIEBUYZANCZJSB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C68038 "METBTRUTPQWJGO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C105003 "AASZMVHCFNUTCF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C69445 "QHZGYBQPBOYXJU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C58501 "HTQIISKWOQQLMV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C58192 "YSIPXVMEADCIFY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59269 "BLYZKEFWCYBBHC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59027 "MMJDLLILUUJJBM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C58684 "PLXATFVWKFIJDB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C63909 "LOQCBSBWYHSUKK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C107286 "GXMCWDUCTUMFBA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C119110 "LNADTMGWCJSRIP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C66681 "WXXDZQWIJVIEAB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C119693 "MYRFHAYSTUWDNB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C58940 "DDLMIMVHZLFBIV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59006 "OMIPCJKDKQMRLY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C58915 "OXVIOBPBNGFJJG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C2823 "FJGXRTVVBLKVFN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59454 "BRWPSDCOLBHWIR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C51683 "BRDAOGJAUHHEEL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C119151 "DANFNYKHKSMNFE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C12612 "PVTBTFNUMGXPKS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C2006 "RYSYUMJDZXAFBL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C111861 "JZLGLNFKHZQSCU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C355 "AMVABLYBMIDGRH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C58422 "OWKFDRLCOMKSAF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C60900 "ZOFWRTBLLKQRNN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C115462 "URGZMZUBRWCPPQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C5622 "CCTBDQQIIMCABW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C68932 "KAWATXBRPQPNJQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C58143 "XJWZZWIUMUDVFB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59118 "IVDVPCUQHVXHTQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C116405 "GBKLQEOFQYIHPA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C109218 "PERFJFZKSNQGTG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C13732 "OSNKQWBJRSQFOE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C108828 "MDHIDMWPVSUSIH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C49928 "ZGUYBYADFRSMCR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C58528 "VLNJIWBFHXRPOX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C11833 "GYGOFUBOUMZHLV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C13764 "QLVSAJOLERJXDY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C47444 "SNCAGJUHUDMPFE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C48209 "KASXZJNQBUCDCD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C15872 "KZPCSVCJQGWDBQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C48202 "SMMLUJAXGRAQIT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C9996 "BMYSZWRSVQNPKZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C69815 "UDAWGCOOVDDRSC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C49916 "JTMMYTMJQJLIHZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C1906 "GCFMQBUVZFHEMU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C4396 "FOTPABJHLRFZDV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59126 "NXJYTRXEEROFOS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C109749 "YBNXWYMUEQZBNG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C108386 "MFSFSVIIXKYHLU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C114282 "VFEKVCCASPPGTR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C108381 "FQPYZRHCGIEGGC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C58671 "BSWBHJYSKIPNIH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C47891 "DJFBDOUCMHBZBP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C120410 "QCNRXBDZXBKQJE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C113385 "GQVTWVZGZGZHRG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59685 "YKRCQAIUNIVNKN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59678 "MZLCRBBQISVYAT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C65201 "VVBDNRMYDOKXAP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C60764 "DWYNAYVGMKFHNU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C59127 "MFCSZHFHYGGNEA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C66691 "DZBJXIDRGQNHBA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C119039 "PWMLJRPLKPGGBU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C15241 "YIXWKRLOGGAWRB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C60001 "OGNBYYUMCGRJAQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C48189 "RTTMDCFPBRDTFG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C120385 "QMMJHLCPTPBXJT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C63995 "KIWHRBIJBOKCHL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C60509 "PGPVCGFJUVEWMX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18098 "RWQBLNKDDLDZAH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C15347 "WRMURXDWWMUBKI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C79027 "FSAPLYDRDZPJGQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30253 "LWXCJZXZNRSZOU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28393 "QXWHSIUPKUDZSM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C108668 "OPPMBSHXLITOSB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C780 "BDQFEXAAQFEPNQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C816 "VJFZNUGDNOTAQS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C1103 "NMYZMXLPNNPYHC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C5682 "FDBANKMXTCJRQY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C7584 "BJMZMZLIAXGYMA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C8147 "DXYZEBCHUORQJL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C8170 "HCFOJUVFUFYAEU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C8671 "BCEHPRCRZJBUSQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C10022 "SBJXLUHXAPANFE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C10351 "AOGXNCGBEHSVMC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C12461 "AJORIAVLFBOMLA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C12771 "NTSVAWSXRCGLIM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C14145 "XWNZKTSTELJFTK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C14910 "NYVMWOPWLRUMMH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18011 "GFZOTSOZMQYOOB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18030 "CLJQVLFIRBDKLD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18031 "SHSOKTVLUHUISJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18041 "JVEJBJTVGZSPNA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18056 "WNMIUXACIAGSSF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18063 "AOOKYXQZMCVCHC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18079 "NOTRMCDWIGMMGD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18080 "ANUWQMSHWKPXRK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18090 "KYKVRFVIYVTTNS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18091 "WWNLNEJKINNTMN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18109 "CCUCUEFINDEPSV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18111 "QOSCPEKGZIPEDK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18112 "CKZAXQHEQNZHBO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18114 "RYZFBPOFDXXTCY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18120 "VJNPBHUBBULPMP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18124 "GFWSAXIDECSWAE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18125 "WRNZPNZTYPVUFB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18129 "HYXWIMXBBPCKIS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18132 "JNNPZPOSGWCIPN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18133 "VKZCGEBMGKVMML-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18134 "AZOHVIVAPASBLC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18136 "QHKHINVFIPHZHN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18143 "PHNGUFDOVRDQLN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18148 "MMMURWXLRPHNQC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18158 "CNLILXDEVGGAKC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18159 "BASQSKKWKWHFSI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18162 "LFNHZUUUSTWNQW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18166 "MONPXLKYTKHEHC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18169 "BWNLUJXIDNILOQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18176 "IYBJSZMWUFVBDE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18179 "DBDHSWUZPQGZND-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18181 "BZIVVDYHODAOFI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18184 "BXBBOTPJLWNCRK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18187 "RTJUISKPTNTZLZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18188 "LCAGCZYMEXNBSV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18191 "FECNRXLBSBFZDO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18192 "NQNFGSIKYACVIR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18193 "FURFZXBRQWVWTD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18194 "WWTRDLFXHKTWPV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18197 "IXAYYKVZQBSDRV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18200 "SJEMKEXSVOQQMU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18204 "ONZHBVOHMJASLX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18209 "HGLRUVFDNQDKCW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18222 "RITBSOYCRVFODO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18245 "BHOCOKSTLLGKRE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18257 "GKOBYQOSAFENIF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18260 "YFOOFDJNYDUSFQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18273 "AKXYBXUGJNRYPT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18401 "OBWRJVUCTCMFQV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18493 "MVZJODLAOBLCAT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18499 "UEBRJXIBFRNERG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18500 "LYYFSPGAOYTAEA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18507 "VHPDNHZKPKIXFP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18508 "GCBSBQFYTZRXFL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18509 "MLIFFQFSCKZXIZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18538 "PPGXTQVKLVSAGH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18544 "VALBWZNNVWWFQQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18545 "FVDADDPUPURNJU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18549 "CHDXHRSTAOAQQE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18560 "MPNRWBNVZAZJTH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18570 "PKXWRFMYUVXMBR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18572 "NSHKDQIKQGUFLZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18588 "XMWXOPBQRVKXDU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18589 "BZFLESUJFSGUHN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18598 "ODPMOIWSZSGSFO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18603 "HCXXPNYJARGNPI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18610 "QJJIDSRZXQIPQI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18618 "INODJFWMHZDKIL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18621 "WRFIPADNDKERDN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18626 "WMNBAJIVDBBPND-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18640 "OUQDLIWACPBGGV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18644 "WYSOANXTDNOONN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18647 "RADGVWRQZIHZSL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18649 "ZORNLLODVNZSDD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18652 "QGYHWCDDLIQLQP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18653 "YZDPSEUPWKUIAR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18656 "CDTMPAKLVNXYNA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18657 "UTJXIVLNXCYGPX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18661 "RRVWLEUXNGMOIU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18672 "AACMWCFDDBWCGJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18674 "VKGAIGWHRDEBQO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18677 "MDRLCUWLBMWNSF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18681 "XKRRUJOUMPPWKO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18717 "WFRHSEBMWPSOSD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18735 "COIXDSWWEWGKMA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18782 "IULZIRHXRUDLOK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18784 "LBCMNNUVTYYDNK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18786 "UVEQRLQMPOVXPR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18844 "GGAFUEWXMOTASM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18897 "KBTJNNUCMXLQBH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18937 "DDKLVBXQKWMZBH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18950 "CFKXESHBENHZSJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18953 "CBJYKCYSPGHIBJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18958 "JNRXETOKGVKYRS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18961 "FVTNQDFRIQDWEE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C18983 "VDZNPDAWUWUANR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19010 "GJIIIESBNKHNGR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19014 "FIYSQGQKOQCXAK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19020 "QQXVXXAHQDUTBY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19033 "YNXFVHWZVIWIIJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19044 "HSGFTJXZLHDXNF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19045 "KEWUVLYRVXVQNZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19057 "WYFKOBYMLZIVOU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19061 "DUSBMIPXNKLNSD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19066 "SKPPWOQVDOGEDA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19095 "SAMBNNZEBURVGW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19100 "VERRNBAEGUGNQH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19102 "QDMGEZQPKIRNAN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19106 "YZJWCUBFJGAUOD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19107 "AJGWKPFMBCGASE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19119 "GFOGEKYWHVEGSM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19124 "NFJISSXABHXOOR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19125 "ZEIUNKBBTYXVCK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19131 "NYOKVXTUYQHVEJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19133 "RCGFFHHQYXKUSA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19142 "HRRIRGFLISVUHC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19150 "PQIDBBXVZRPWFV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19153 "NOSAXJRTBIRUMA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19158 "MEPJPWMUORNASJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19159 "BXOMASCUJMKFAA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19214 "OQWWVPWQMQOOGF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19215 "RCAXGXSOYIGJMU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19216 "YXXOKFOKTOGSAH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19223 "RXPZMFPMJTWGAG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19224 "MKJCHLBLIHHNRV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19226 "NANWOTPUXREXFZ-UHFFFAOYSA-M"!

 Warning  Deleting 'Enamine' quotes for C19228 "YROYEXGEAMKZRY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19242 "GIQCSPMKBZJFGD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19249 "MEXYPYOYGXXEMB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19252 "AHROQKIDTBRPJK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19254 "CXZOQQXDZPDDMX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19264 "VYBCAKQJRPASLE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19275 "QFIHSZDBCHWNPD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19279 "WYNXYJNHBQPOCQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19283 "WHFBKTSJZDZPIM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19287 "GFSMGAJVNJBCFK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19288 "OGXMPFBDABYYAC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19289 "RMQJKWNBVSOSHO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19302 "WWAJBBYYUSBZLW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19307 "RNFRUBWEQXEHMA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19317 "NNXDYSUULDOARB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19325 "IEMRKJXKIGDLOG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19336 "XXNWCLSCAJZHQA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19337 "MFWLKTFZRVXFCQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19338 "UADZCLOGYWFTNO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19346 "KSFUUZGDCXKVDV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19347 "CZOLIGBXSKTLRP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19351 "USBPYHNNISWGFP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19428 "PBOQBIXZAYNIKD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19446 "CTSHADRFJHNIHM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19461 "PQHUCBYNBNVMRW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19495 "AMUYIBPMXDPHGN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19497 "CTIOECLROTWXRJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19498 "QYGPAJWPDHYFLP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19516 "XVFGCYYFPXNIEY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19526 "WYSUEYDZZODQEN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19536 "LKBXFIWGAXKARA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19560 "NMNKWWRIYAQFKO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19577 "DESGJAXZCHCNIY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19579 "IJUGQUAIKMLGIM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19614 "OJPGIHUEWOZYPD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19640 "BDONDXPYZICNIZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19647 "UFYMDXPJOHZZBC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19657 "MMWWWFQPWJSRTK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19669 "KWFBUIVQDMJPTN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19672 "DXRMMAJEGGKHIZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19676 "GTRVSAOTNFNSOK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19682 "OKPSXQAQPSNBCK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19685 "UMHSNQFWHDGLFH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19705 "YDKUPAXSODHNGN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19707 "WIBZCOWSGTVCFF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19708 "CWZSWMHXROPZLQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19714 "RHBYNJLIGMJWTB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19717 "SMXGEHKLOASONW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19718 "VWGQDLLXKGNSLD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19728 "IFTDDQCGVOHHMN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19730 "MARNFAZJHJZYHY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19759 "WHGASIASLUMMOS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19761 "DLCQMZVCFOJDLV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19765 "CSRFJBKHCFFLFN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19783 "MNZHGASRAJNLPA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19785 "ZWHLJTLNOOODOL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19786 "GVHWYRZMTAEPDI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19791 "DCERVIRPXXXNIH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19793 "WGDOBPNBZLAQOF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19794 "KOAKCAZSOYQHAA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19836 "QFGXWJHBOMRRNY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19837 "YYMXPUNHEKZUFM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19854 "VDJJPRAVDLHCHX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19858 "NOBAOQDLHPSYQM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19866 "CRRGHUCAYBUQLY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C19986 "WHSDZHDCMZBWQW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20017 "DMICLLIEWXZIGN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20040 "LZTYPFXTZGYTIP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20051 "LQCSMSXCOFQPQB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20071 "OZVGUFPXCMEQGJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20108 "OIYYJFZWHULVLG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20112 "RFZWVEFXMGFGAF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20129 "QNPSEMWHKKAJJL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20204 "CIVSINIHSMXZBO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20213 "NJQLXDPBOWHNGA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20239 "CIKJUBSBNKBESN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20244 "PMXJNHHMDODVDT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20252 "DOIURHHHTXBOBD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20256 "QGYHAFSJMUVHLM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20261 "HMBDTZVOLYHBGM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20276 "UMDYPELTGKYTSZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20280 "LRKDXKVKIZWMIE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20288 "JUIUBXCQBHPMOG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20291 "NDZCNNVWQUUYOG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20314 "DUCPKMHHYRVHRJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20324 "ZNYBMWJDCBETJF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20326 "NEXLDOUYRFITDP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20335 "IEPDGPCPZKETDF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20341 "JTHFBQUUGGKNOX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20359 "UUIJBEFZHQZDRV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20360 "FNJDQGWFKBLKTM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20402 "WIDXKILAEBCWPM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20442 "ULNCGVLHEBFFBH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20460 "SUVRQPFJSQFQFB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20504 "NIWBCNMRPCKVAQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20505 "GUKLPLARBXXOQE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20508 "WWMGFHWCEKIIGQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20514 "QDNVXTVLZPFQCC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20548 "RJKYYZCKKKXKEY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20552 "GZAPUZQJVWXFKG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20559 "MLYALUCWIZCHMV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20604 "KRFHITCBRGRMAK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20615 "SXWQUIJPMLGARZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20704 "TZMFCEPHDNHAOM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20708 "GUJCCBMPCSVXLH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20712 "OWRZMJGBJUBENM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20724 "NTMLAIPZCRPEMP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20726 "FEXRLFSQMKEJES-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20730 "PTDOJHHSYKXDBN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20734 "KNPPQLPLZBZIAH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20737 "XFCCLJSTSUJYCE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20741 "HIFGYACEWNPVPD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20749 "LSYMJORTYQOGOX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20754 "XFCXJPMWVFCQJJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20757 "ZLAVQBYZXJSRJJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20761 "VYYXLNYSXVGCNO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20766 "UYLLXAYZKPIQKF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20770 "FWVKWPKPXVIGBX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20772 "CUZXMFOKOAWAHT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20778 "NEYXADAMJPZMSQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20781 "OXJSBYVAHRLMCE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20785 "QBAHJHRLLPEXQO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20790 "CMIPRQMYSUVHEC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20798 "SRGWHDHJNIHJSV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20803 "DXEYMFXKFZMTFG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20812 "NHDGGVMHCDJZEA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20813 "SRGHSPJNCBTSMW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20845 "SSYIBFASXRACKS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20849 "XVLDTRBSPPSAJD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20871 "KPERNJQGCSTHRL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20885 "PJQAFUBGUHLQCZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20901 "YITDJZNYLBICLK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20917 "MYAFPJUPHZFPDI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20941 "RAOWMCLKXDIMPF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20952 "LUKLFSKBDCSFEM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20957 "CIZWFICHNGVBGR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20960 "WNDRNCWESVVFKK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C20987 "BVCBLTGZSBXLQM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21001 "RNWCODSXUKFRIG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21002 "DVGFYGCPFOHOHB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21022 "GVGQSJOENXUDDE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21036 "VFJFSVSNHZQQRN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21049 "LRIHUJUCEWYXNP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21057 "UPDSNJKTZOWHBT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21098 "JWCAJSYLFSKYKR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21174 "DYKVHFPMVBYPSX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21176 "CMBMAMBPROTYDA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21184 "LZRGBCFOUKMTQL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21246 "COZNLVWNRMILNC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21248 "OHIGDAUMRBTGNV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21249 "XCVSOVQYEUPFLM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21251 "SUGQQXKANLNLOG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21253 "YFAKMSFSTURCPY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21264 "AGANTASUJLFHKD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21289 "JCCWMOPMMDAQRE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21293 "QPYWLRZWLBFCIK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21314 "KALJJZTWBLLYTK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21320 "UXWAEBOEZKKVMO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21364 "HWTJIMFKHHGRQQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21417 "ACNJMKFQIZKURE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21426 "MKKCJCXUCWORFV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21443 "XTKMGNIPKHJZAN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21447 "RDENYPZDSKRRJZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21452 "ONBKQRMGTWUDIS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21463 "UUOOUBHEFMHWRX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21479 "PIFFLSVPQUDODW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21487 "XUEVGXHNDLAAMH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21491 "DIIWANSCDJAHCE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21494 "VMZSLIVHGBDGEF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21495 "ZMWMUPKIBISPGX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21511 "RJFMNDKAKXASFD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21527 "GJDMFLGXWOIWSW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21533 "QPXRIAKEPAJDGT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21538 "GQDZQMRYJVZBSX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21551 "CEGQJIMHNXLWAY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21553 "ASENFTKBKASXEU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21585 "HZXUXJGVDQXCHB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21602 "QDQWNVMYGWAHIX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21639 "NCNSRNMQCXLHCY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21642 "QDPDISRMIJEWNO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21643 "YSDRLJQCPXRTLF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21657 "FTMPVUPOCIMBHZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21705 "RMMPDFXJAHFBQE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21710 "KUFSNXGMTLPSMF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21714 "WKYTZOYTFTWAMR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21737 "RFENSWNNTCZZEP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21741 "WBMJPMNUVYTTPT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21744 "UMLMRUOGYWTMGS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21746 "WKYBZIFBFIQSEG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21749 "DGIQPCFXJNOJRM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21822 "KLUVYKYRVCWKDA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21870 "GNKILSANWVVMMA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21914 "XEEPQSVERQUIEH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21916 "XNSFTLKLYNFGOI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21937 "HAVYRUMYJJPLLJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21938 "DAPNGQSPWZKGJH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21947 "OLLMXNLPCMJKQT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21953 "JQRIGIHMJDQEFG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21960 "ZSGBPGFOLFCBHX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21975 "RVWVPSCWCHYUSM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21977 "PEGDATDGFXFNKR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21980 "BYEUVQXGGBNWLT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21984 "IYRXOKRTUHJJIM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21988 "YUNHXPOGOAYHDS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21989 "KUXWLOLVMXOAOV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C21990 "HUPPILIMAHRSJO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22033 "NTKACNNGQCNXNF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22034 "YKMZDYPGMXUQGK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22053 "IHLDZTMOIPNDOU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22061 "WATHLFABWOUFIW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22094 "FCDYHGUIOLXPDJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22105 "AGVICOOGNULVLC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22173 "XVWSYUBONCROOD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22181 "PXKBRHIWRCKUJC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22196 "VQRGPKHBDZKUDH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22217 "SCKWYYOWCKKFDF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22244 "QJOSBMZWHIFYDS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22347 "MURVHGCLORQQCZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22351 "JJOHXTYQQFQANG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22354 "TXSQKJBIEPOGTM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22387 "MHCWQVCZBVBTBB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22408 "RUHRATOWMMAGQJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22435 "RGLNEIFHKMWSDW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22436 "ZJRRELMQKOWTGT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22437 "PKMBTGWSMHCVPP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22441 "JEQGWNBYQMKAEG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22442 "CAGFGCMKTNIUMU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22443 "XDYQPZAOBOYKED-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22450 "RGSATGGPFXKDNA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22451 "FRABAORTOGAZGP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22467 "ZYQAGVMMYAHOTR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22512 "UAEHSCHMOFZHRV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22615 "MLDKOCQZFVYUDV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22620 "XRBOVGIESMKHLP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22636 "UGPRSXASOPMQNI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22638 "PXDIQALWEOIVTA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22647 "MALSQHGNNOXZLC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22651 "AOQYTADPWIMDHE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22653 "HTNVZEYLQPHJCN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22654 "QJPNHCVIGAYBEK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22661 "WPPZSDQHSOCVEZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22664 "IRLJMHZZYODRNN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22669 "UCJAJRYKTMXZQY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22670 "BJRFRTAJYNXVHJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22750 "CYYRDOMJJKMFEA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22775 "MILSFOYHUIXZFJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22790 "BCBFPYWQRAZQDT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22808 "ZQOMQZNITUGNLF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22821 "ZOTABHZTTCBGEN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22825 "AJGUXXCLSPQRQI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22843 "IOAXVAKHNSXCGL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22858 "OHGSZIBYWBJLOI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22862 "PTWKSXRHMWDLDX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22863 "RAUCLMWMJLNPTE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22876 "VXLGRYSEKBEEAO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22887 "XFNYJJBFMKDJDD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22890 "GDZWSUJGAMQBGV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22892 "QOPDGXBUTLNJBC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22920 "OBEWWTKKVDKNOL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22923 "PEERVOFDEZBLOY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22925 "ZTCRNANSRIGDFL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22966 "AZZHNOHEEUJYAZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22974 "ZLQNVHMFFHGBEJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22975 "MSUVVXHYNBXDJY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22987 "LUMLPEDBKRBXCO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C22995 "PSILDHITUQUQTG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23011 "SCCYNXWNOACXLF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23014 "VYUOOQGHWMPNSJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23017 "SPWAGLCQSBEZJY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23040 "OKWNAIAAEYDKFG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23054 "UBKTVCBHZLRXTN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23059 "UTNVYBNZSLNUOZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23061 "XBZQWDWGVUOVHK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23062 "IRUNNPMAGDPWCL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23063 "XZZQUZUXRPCSND-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23076 "KCYKFEBSHQOQQC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23086 "AQSSZTNNJQAZPK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23089 "YHSDJOTVTCXVIK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23092 "YZXMTRYCMRGQKW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23093 "OWCWUODGFHPQBV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23096 "XDTNOSCZQQUHGZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23099 "TWAXBOMTVAIRMH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23101 "ZHBFBFHXRJABKA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23119 "NRDATPPBHBZGMZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23121 "VUYVWVNJRZBDRV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23147 "ORGBNWQTBWUZER-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23155 "NUOIFJRKLORDGK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23176 "RUNGXHZLUZTPED-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23178 "MEQSJUPDIHKNHG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23184 "ANUCEDNUPUZDQF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23189 "SFWBCRKTLAHCFJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23202 "BWDQQMJYWHQDFM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23205 "PVJRXFRJZUUTKQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23213 "DCVZHTMBITXVBT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23220 "NAJAIOLHEKEAJJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23221 "SWGPBLMCHCFQBW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23222 "MOTZUJQPFJDZOR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23224 "NNRBXIDCABGTSH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23228 "CUUGVNVKUPEFBP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23233 "PQQIJFAKOKJRBT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23234 "RWWWEXSKSCQEDK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23237 "JNFFSLSVQDDFME-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23239 "OZNDMISWYCRCHP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23249 "LPMFBBPYLRYRDV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23251 "QLFYOCSGOGSUQQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23253 "YLSYXRHBTCIBOP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23256 "AXSJQTMYDVABOV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23259 "DVTBFLICCNPPHE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23262 "XYQNPNUFVDBSOW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23264 "YBWLGQQEPPLEDZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23267 "YPFNSVFYWXRRMO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23273 "FZTAYJPELYTGOW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23279 "LIEURDJWIPACRH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23282 "IOAOLSURDMSEJM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23295 "XDEDQHONKBYHOU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23303 "CMVILRNMIUHCEH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23305 "UTBHXLKXTWLWKQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23312 "PIPFZPQOQPKKBK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23314 "YEZAPXHAAFVSNG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23389 "NTYNKDIEXJTVIQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23406 "HKNHRVKZBRVJLD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23417 "SYFGBZDIJACYAT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23425 "JSWSICJGTWMAJP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23445 "PZUHEIPNXCMYKD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23452 "RLTWSJXDFWIPIJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23465 "ZRBVUPHOSUPZHX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23469 "DXNQORKZQWLLTQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23473 "FHZCXWYCIYNDLI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23488 "YJPVYCBZVCGGIG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23489 "MWYDXDZGTUTDOD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23496 "NMJDSBNASTUUBL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23512 "QCIFXYSGFLOLOW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23551 "ODPISGJCCBMUFK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23552 "QEDFXGRZMSUXRD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23563 "DZRWNZORUHGILZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23574 "LMIKIEDASYHWKV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23581 "VCDOAUHEGFAYMF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23707 "SWPIMUUABFPLSY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23708 "YUWZYMNEHVKHIK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23709 "KQLUEERTZMTBIE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23713 "CWACVHOGTGPGNS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23730 "JCANJUUGNYPHQV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23741 "IDEWAJWFCKSZMX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23783 "XHJPNHIQEDNSNH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23794 "DPTMADXIYZWWJY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23849 "XSROUEBLBDOXEA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23872 "HQYIPYGLPYHLPF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23935 "BVESVRZQEIUIHS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23947 "HTVMSHYRFMFYJC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23951 "AZYCPFSESFRRPB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23984 "JWPAGKFSYQMJRS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23985 "XXVZHYDHLIAPID-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C23992 "KBGZXJMYFMVRQW-UHFFFAOYSA-O"!

 Warning  Deleting 'Enamine' quotes for C23993 "GANFMBVJGKBIOO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24002 "DJMWSOQZFOTBAU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24032 "VZRMOKCIAPRTEX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24071 "QYRFSYKLYNLHGM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24083 "YXQBXRNVSPSHRN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24127 "KMGGLDMVOOVARI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24141 "ZAIXXZMNWBUORE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24148 "DSUHDKAMQXRJBD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24165 "YGMYKGKOIHWXPK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24186 "VFYLUNHDXYGDCP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24201 "RAPHKVFDFYJSLL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24210 "HLQQYNBFTFMVLI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24213 "POUYFPAIAVBIOV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24220 "QPQYHPLFUSRADW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24233 "HRRRDODKOYZHDG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24270 "KMHQLNUWNATUKB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24275 "NUFMCAIYFUFGSW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24278 "GSZLNZYTJIYVAU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24315 "MGZYHYUBOBABSI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24318 "BLXIAOGDQXHBFW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24324 "HDJMQQYJGWPHOL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24329 "VUMOOYTWFDNZDH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24337 "QABYHKMCPXOYCS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24341 "HEOVOASWWMCSFK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24347 "NSAADNNFRVZRMX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24392 "YYFBGEIHKHYNHO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24423 "JALIXOFBDXZDON-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24457 "HTKCIUCVAVIKNN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24474 "NLFOLQQWBJLQEK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24477 "SXRGLDMVXSNGGT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24484 "CFVYAZJUDRQJNL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24492 "UJZJBLJQIFRXGD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24539 "NPZLTSWKWVSIAX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24558 "XDVLJCGVPCGNMN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24575 "CMOBKAKQXYCRRR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24577 "ZHYRIFWPQWZLGO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24585 "POLGZLJEWBCPEM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24590 "QABBJFIUUXZPPA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24608 "QBLDOLACCYTJHQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24611 "CTBJWHRLHFFOQE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24613 "YQXCLBLVGYQSDI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24639 "UUKVNZJMPMAGNI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24640 "CDPXRYOBMIJVNW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24649 "ZVXKUELEICRBNL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24659 "HSBJAWVPGWOLKA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24663 "LRDJXCAGMBDKFO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24667 "XULWFMBPBDXECC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24675 "RQDPTGTWMZIVJL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24688 "SEQOSALUEWYPTM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24728 "ILDVLUSBXLVHMO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24733 "XMFHOBNKXJDERX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24735 "ZHCHNLJUWXSMRZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24739 "WAAWBXZWVLRCTR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24742 "YICBIEHLYKKQNL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24750 "NXENINORCFPSHM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24755 "WBRHQKAYBMPPFT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24756 "OYQXQUPIEVONJN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24758 "CJSKBWGIQBOHQS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24759 "GPTKHJMGTBDXJJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24770 "JCQLHDJDKPPTBP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24771 "IKOYQVWZYSZADL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24772 "VJKNRTFYJGKDJO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24789 "OEYBSXZBQPSCEL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24812 "BCZNINZRALPMFY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24818 "RJTBLGUZYLGWHP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24819 "KMHCKDFWGFCLIM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24851 "DFWAZAIJGAXPHM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24853 "BGQUSMNXMFGSTI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24858 "DCOPGBXDFRPMAX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24873 "WWCQOQMHYIRDDF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24878 "NLXRSBYLLGBTME-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24908 "UKDWIPCBLSJJFI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24912 "MKJMAHPTRRSFSE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24923 "QTFODYWATKEVNZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24926 "NZOZERBGAITINV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24927 "XDANZATWJOALAC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24938 "NPUMTALMOZCRJE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24951 "SPIBFKGYMOMNBF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24953 "HGKCTJUHEAQEIE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24955 "WMEWFRALAHEPHJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24957 "XVQAHVLPJGPJES-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24959 "GVFBDNUAYLGOCO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24966 "LMOMVTPLSWGCDY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24968 "XYHCJXSENSYPMP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24972 "CJBLBZHEVPPPQX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24973 "XCYFKRANQDMNNW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24978 "PJGZGCWCTNCUKC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C24981 "WWHSZGIGTIDICT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25016 "AJCPPKZMCJGIJA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25094 "YSQDQRXHUCFBDI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25106 "BSSHLOXEBAWNFD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25128 "JXZXZUDXAWXYSF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25131 "HFUPLTSCYGRNHS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25166 "DHZMJYKXQGTLBN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25185 "DQZJREGFBAYAID-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25297 "CQPZBNCLCXVCRO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25304 "VSKQBTHQSHQYKQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25324 "DFODLUPEKATRPW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25363 "IWLCGUOGQVPMKC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25388 "XYVMGEYUPUTDCP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25398 "MNPQHGPAIZELSB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25412 "GKBLFBVNYUVYOD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25446 "BOEHZXJIJYYGKW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25449 "FSOLSPAHYWOOGF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25489 "CUCJSSQXEPJPRQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25494 "MOZDKBJTNTWJOO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25500 "RPEGCYFAPWHPOW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25505 "PNESPAVEZLRZHD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25514 "XPGLIFFUOCNFNF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25530 "ZADUHCDQLVZDEH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25572 "NIAHOACVCBRSAD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25573 "JROJORKHLVZCSA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25583 "KOZFMZOXUWHDIC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25622 "VXQCYDNSAZIGFN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25624 "ZCETXSMNIOMQJN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25628 "ZIKDKOTWAHPFIC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25645 "NILWULBVQMINSJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25661 "HCVJFKHUWGWVCN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25699 "KYSSRXPYYMABFA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25710 "BAHQJJCEWVBIHL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25711 "ZWKYDBYSRHTCBB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25743 "YKHJCKPZYHMVNH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25812 "JZDVCWCHFPZVRZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25820 "DBYCZKGKATWRLX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25838 "XVALCIRLDBIKMY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25858 "QUBPSWPVLPIFKC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25864 "GRWWQPWVRWBXAM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25865 "NFVJUBJALRAPEU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25897 "IHHZYACJOIXALQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25898 "HAYJXVXLDLYZJC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25919 "MGNIIIAZTVVFIC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25921 "FWMDCHOTNXURAU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25982 "WIQCTRNFBPXVEQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C25998 "NHNDYICOBQQJFT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26072 "JMVPHVAZSXDAGE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26096 "QBSPMPYKGLYEPQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26137 "YJLCQJFEVFZBJW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26141 "KZPZPHRZKTXCSA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26142 "NQKBWFJSSMUHGW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26184 "GHWDDLBKKZEMRJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26340 "YHILCQFOCSNVNF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26359 "BMBFDHBHURBFHQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26386 "ZQXAOZDICCOGOS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26415 "WUDRJXFRYAPQPO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26471 "HUIVOGIVFBRRGU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26479 "WDKMVRNLWYGMPY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26530 "YBDVERFAAGTODC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26535 "MRGFPIVNPFBWSH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26540 "DFMCTMSODAGTRA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26552 "XWSCOLHSPAJGDE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26572 "ZZOMRAQXMMWOLN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26577 "VZCHGNWLMKPORK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26579 "VUOLDQSPHPAOOE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26581 "ZOJAMMURIGQRCL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26582 "YTOCORQZOCPBGW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26588 "QCXVNFLSEYSGSI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26608 "AWVQLXUPKLUPDB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26624 "WGDPKPTZIYBSEP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26633 "CVJXMDKNANHJFY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26638 "BXDLIVSCSQIOEE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26643 "AWMFJIODMGVVDL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26658 "ZSCQYMWGXZXNGT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26668 "RKSFFWBDWKXDRE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26696 "SZAOCEWDLFAGDS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26707 "XIYLXQVRKGSYCA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26764 "ZVGMSMAHCHSHDI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26792 "NBKSQZHAIYSYRY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26794 "KMIBXHLJXCGRIC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26851 "BDODFFYAQXTJJG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26876 "QEWNWSPLGWZJQS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26883 "TYVBTNSNCIIXFO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26927 "AXFKZZBUASYPSA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26928 "BFHBBZATYAOMHE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26960 "QBFNXCWEPKMHIU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26962 "LXBZBTLOPXSLTC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26975 "LIVSHQUQCIZRII-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C26985 "SKBNQNGAPRQBLQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27024 "NSJMDNSZMXGIAV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27072 "VAFMNXVPGQMAML-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27075 "PVHWVGCUJOCTSQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27098 "BGVDKKKGJBVVBW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27099 "OKFXNIWYJOUUQN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27111 "VOKHMAGDCRIRIF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27114 "XNLDSRGZWSDZTM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27123 "BWDPKFITUUDZKW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27126 "WXEYETWJACHRFY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27129 "UXQPXKCBHNKXMR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27131 "ZCHBVEYSAUOOAJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27132 "HTCPRPSFBWTTIF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27133 "KDVINVGGQBVTGF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27136 "FFZSWCXOJBABTF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27153 "QZCGDTBVNGFSRW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27154 "GSSRWDSUEPGDHK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27156 "PDNHLWMOIXSQND-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27166 "HNUAXQBAAZEEMH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27173 "APBMIEAOCLHSRH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27176 "UBUGXPYOUBPVQP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27177 "XUDOREOZCWVXJX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27179 "MOGOJHZFPDPWAG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27187 "DULOSDWLPOFMFA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27211 "GTCAXSODYRXCJN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27228 "KQRMWQJNYINGNH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27260 "AYHRFAIRZJSWGP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27262 "PHGPPSKWKDEVAB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27263 "JGPBJKMGUTUIMM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27264 "UGZMRPJZPUFQQJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27272 "PXVQQNLULIRFPW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27284 "DEPUWAWZQMQEQF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27287 "LWIYEHPRPKYIBS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27298 "OHXNSUZOEGOPHM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27301 "TUQGHRYMIHWJAZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27311 "BSZUDAPISCFBRA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27325 "GVUMASCPPWACIK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27333 "CJZZRNLUZNSZQT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27335 "NRPYGYKGGGOHMK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27336 "XOAKPUGCZYUXPB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27340 "DAALQJFHZUWTDW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27346 "QWUIIAWSHDJHFV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27351 "SJRPBNJMVZZICA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27362 "INENIVAZMOMTSX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27374 "KVMPYBHFZGZGLK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27376 "FRYPYPDVGDLANX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27384 "DAATVJSWFDZXMD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27497 "CIYQHLIDBRMVRA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27516 "YJPKEUAAXXVNKK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27542 "HUXUQJQVJIZCFO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27587 "MBLDUPSUFCYFTH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27620 "PQNJPEWRWHDPFT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27676 "MSLYXQCVTWTVIQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27706 "OKMOUFBJMDKMQG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27716 "QWXAHPFCABZTKD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27742 "MWGXULNAURETQU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27748 "TXLSVPWLNHHTJN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27762 "DOXPLBHJYWNMDQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27766 "SPZFUXFTFKRXPS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27774 "GASFJBAEFOWLLE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27779 "YDSHJYKEPJVNAG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27792 "DOOKTAGQJURRRK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27816 "ROJSONNSMZCBKO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27830 "PTDYVPANBFUNEU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27831 "ZROZSXVMNNEPHO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27832 "DQOLZJYUJUUZOL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27836 "HOTLWBBYPAKMHG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27866 "VYCSXADUWXUQGL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27880 "SBRBARILCMMYSI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27917 "BHGOALZCCRBHNI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C27990 "QALFBBSQNIHQBX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28003 "SOVUXHYCFLALDV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28021 "OOGHMIRSEDTBAO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28050 "WUNQLSSNLGBCRZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28086 "CLDGEEFPBAULBP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28093 "SEYDJKKXYTXCME-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28214 "LFMFZPBWWIRKSH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28216 "BRTHLZRECLJKOI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28233 "PGRSBCLWXACIBK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28241 "XJIYRTPREVPRND-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28264 "BPVGHZUXHMLAEZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28271 "GTDFHHGHSQROBD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28281 "UXJBOWKKUDHLQU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28292 "LLMYHBHHEPTMAI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28353 "GHGNYXCJGIDRPI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28362 "YDQMMCVSSOTGLO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28366 "ZNTZGPMSWQJPKJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28367 "RGENPVDJTVRZBE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28369 "AEUQMUKSRUCNMR-UHFFFAOYSA-M"!

 Warning  Deleting 'Enamine' quotes for C28415 "YVMNNYLRRNBOEF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28427 "BPXWFINXIKBDRU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28433 "NTLRCWRNIOXAEK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28489 "CFDWEUAIGJEOPA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28494 "MAKUWCPKQUUOPV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28513 "BISJWFSHTKKTNO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28555 "BJPUHHPFQKJNPN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28586 "AZIZABXIWWQACX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28602 "ORAVXFKICOXBFN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28655 "LXTJSXICTCZJSI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28725 "LQNOOFDGSDCUEN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28765 "RXAICXDYPAJDHA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28771 "IOLQURIPHVQRPQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28794 "GQEHBFDXMOEWGD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28847 "ZCQNDSAGNBUFOZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28894 "XRTFLAZUFDZULK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28927 "ZDQMWPLXUXOBBW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28933 "IDNRCKUUEMFNEG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C28934 "QUJVBQYCUFRQAS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29074 "ANJHSIWBSXFLQJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29083 "PFNFOXCGFCSPLR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29089 "VVKCKLDUSMLFFI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29097 "SJMHSHXWSMJZQX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29103 "JCSQWLWDNSIQDS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29134 "DHQHKIGLXKKSTE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29192 "VDOYJDJKQLRQTC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29208 "ZTWHKMPEEWMUGP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29218 "KKMVIZRGNUNJGH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29229 "HCWSPXYXXFGVPD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29269 "OLGGYODFTFVHLH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29276 "QKNIIWHXRVKIEH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29282 "DKRPCYMEHNIVIG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29284 "YLQNOVFCYXVNAJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29311 "SWAXWXSGTBQQHW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29317 "BAZLBFYYOQVXCC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29352 "SBUXCFRHDPFRJH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29392 "WJDZBJPEKVIYMU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29404 "GUDJEKMJLNERNJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29406 "OCBGJSZLBIWUKB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29428 "KKSMGRRAHNXIMW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29434 "YBFUSSHSHOGGJR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29440 "YBXOGOGJCMEVGE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29455 "HFCXSSHPHVKWBA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29529 "YAFAWLPJGNBFJQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29544 "UTYWSZOLIJKECN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29547 "ZUONQKHYLMEROW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29555 "OOYWYANUUOOHFR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29565 "ANAFFNVJVTYRQD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29570 "HNFJXMXBTZPGOQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29575 "LSGUELPRTKGABD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29581 "SGGKYZWPONCHQW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29583 "TUYJOPORWXMCDD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29589 "SKUAEDCJGHDWQX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29593 "GLVMPVWQDWEMGX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29599 "UPYLDBBXKOTDLG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29602 "LJSUGSUFGVYVTI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29603 "TWSFUCCAWJNCNH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29608 "NYERIKDQMKXPRU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29609 "OTDMXPVGXUZRRH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29611 "ACUMOOLRTKENJJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29632 "LVIFJCFWEQQISB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29650 "CQMGVAZLPYOEBE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29655 "HCXPKFMJIYJPES-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29668 "VJTJNCDLDLXJFH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29705 "RMLYGLPOHVONMN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29706 "LYOAVFVTIGBFPK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29729 "KIEFZXQWKLOLHB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29733 "DTNNCARKINZRKI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29751 "CLYXXJCLQTXTCX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29762 "OQTIYLJSGCKYHC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29776 "ORTJMAFDPCUYSJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29777 "DVKDSWOXTCELOB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29779 "YVZMNLKRZPVVEG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29784 "RLZHUVLUQZMADN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29817 "DYMDNVMIXYLQGL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29859 "BTEJGODIYPOSRY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C29870 "CCEYTWSHCWFKRL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30005 "UZFXGTIHHFJQGR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30006 "YRYGILZTQMOAAE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30009 "QTMSHYIXVHNGBV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30031 "IWWFZPYGLWINPY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30032 "NWONASKPCRUFHZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30061 "NXKVEYBXDZYDTQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30073 "YMAIXOKBYLLCRJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30078 "JPBOVCFUZSPFRY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30079 "KMRPHCMSBPNGMI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30090 "MLZKULIDLVYKMU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30105 "SIRFKMHBWMFGGR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30113 "CJKCRTBFAKXQEI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30137 "MXEYSDXOJJQNLC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30138 "IGCASMKZGZWHFQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30139 "KJURNELDBUILBG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30145 "RYJQWDJIBZEBDT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30146 "OWPLLGXHCORGMB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30152 "PHYMRCOYKOABAN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30230 "QZWPGSPXDZXKLI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30436 "DLSIZFMZXRKWNZ-UHFFFAOYSA-M"!

 Warning  Deleting 'Enamine' quotes for C30445 "PXHWXOCJQMWGSW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30465 "GUNZXYOHEURSEN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30473 "YQJAZHHOMFCPRZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30564 "CXCAIODRNPMSBM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30604 "MZZCRENQRVZNRV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30679 "KKAGJWOMEJGTQO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30681 "QPBFMHWWAIYYKB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30694 "AUYWDTLZSNRMDS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30707 "NJKXTUIJJNMNAZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30708 "LBEXLNHYCJKNPE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30714 "RAHHBBQYVWECQK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30748 "CYKSTISCCMVLRW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30753 "RDCMQEHWLOZWSX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30756 "JVBQKCZMSMEYHZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30768 "CMYQASSSFDLGBL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30775 "UWTOZYFNSACGKM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30777 "SJZPBJHELBGTMT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30789 "SGOOYPJRRLHSKN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30797 "XSPVQXFESGDKDB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30800 "ZBSCYNWSJUTFFV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30804 "BNGXTSIWUMVCAB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30886 "LHYRZNUFUAHCLE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30900 "SAKJZRKBVPCGIA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30921 "IGQVINHODNBEHU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30968 "ODHFLZMNURYNAJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C30970 "LTPVXOLDLZESIP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31004 "FBRWWIIOASDUEV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31092 "KVJUDSSQABZMPP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31111 "UHYLSOUKJDOSTN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31124 "DAXUPCPIOGDQEH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31150 "RJYVXYNXYNUDBI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31163 "WKJWUWSRTXBVLP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31279 "OFOFSJYRIUSRCG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31282 "QFWXAXDIRSBJKP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31284 "ANHPTCNZZKMMRX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31288 "KEXDUZGCDBPGMH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31314 "HUCSOSPPLVPNKC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31325 "ZMSNTGFVAQYYRC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31327 "HWFKQPYTCGCTCR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31349 "JMJOHTGIGNHXLX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31361 "KAQUHFFHLPUFOI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31398 "VOKAPNCBCJGBRO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31407 "WIDKYFVSFYUVQE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31448 "MYAQXUMZIMZULX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31507 "HBKVBQZJXHZHTG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31527 "IDGWRBWEGFRYNX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31539 "JSOLIBCQTJNIDU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31613 "LWKWWYUMOQWSDQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31646 "LXWGJLJFWJOWMJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31653 "MZAAZIZEOWSIJE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31655 "FXCUPNDAZOBXDR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31658 "OAUHGJXUCKZTJH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31698 "DNFKKCSHXYEKHC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31707 "HYECETPGTFYCSK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31709 "HYWTVSDTTKQGHU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31710 "OKACQEFJFQDYTI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31728 "CBRPQJRRWOIAMU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31733 "VZQNTMFOOXXYCA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31743 "XWQCRGBYOMEQFE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31754 "JLRVZVBAEDCRSQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31763 "VZPCZAIHGYLRBG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31770 "RVNJHTOMZKQGLN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31787 "HFIKCHXSWAQXPU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31790 "GCPGRRRCYMYGOK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31791 "YOPBLNOEGMGDDQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31796 "KBKYKFFJUJYVGT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31806 "RLCOBEMAUWYZDL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31807 "WFCVJJYALIHWKA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31814 "XIDZVWJKLUDIHI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31822 "KBRXHOJGMLLOAF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31840 "QJNJNTGJZLKYEI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31846 "TWPFZNSZIHGWFU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31848 "FWIBRWVXISTGSG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31859 "KMKXTRIKUJDWGU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31983 "IHBCBUAQHKHQDF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31993 "JEVGYPYCKJUVAC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31995 "HWLKOJBRILUVRN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C31999 "JMVUNPZIXZHIEG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32002 "MOOUBWVOXNCXNE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32010 "KTSJLBGLOHMITC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32014 "ZDJBKDHTQKIJIU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32019 "JEZAOPZXTCAMTD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32040 "LKQVYIIVFWYVAN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32041 "VOODHQDLHPYIRJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32045 "OMUFHKLXEKHHRQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32048 "HISDMGGJZCOODV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32065 "GFVXWJAETUDNSD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32066 "SBYACIDDNDCIRV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32118 "XKLDQSALWILWQR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32124 "KBLQQTCGHYEYNM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32125 "CVTWQCVXGMKZRL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32143 "RZPWBYBLZYAIDC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32180 "NOFCUNVXJMDPKR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32186 "MCXFLNPRDBBWSN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32187 "OAPPERJDBYKZDO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32201 "WOYPELKVNRGONM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32240 "KGCNUOLVSJDGRT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32279 "ATSPPYINPKCORO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32298 "LPQWPQOHCHHXJY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32345 "PAHWXRCPUIMXMH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32346 "SMWBQVLANXXHBJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32377 "HWKAMBDKTVQKAP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32386 "WIUVGWVPLZOFGO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32438 "RCLLLFQQIUMLEZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32497 "NKZDQFXSYUVXSK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32519 "QBGVQHPTBMSRHE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32523 "HRMUPGAZIBCZKC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32529 "IOBOVRGRYHOHKI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32540 "YWLHDJQOWGOFHP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32553 "NEKMOSKYAYISFC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32559 "JTJVOAYMOZHTSN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32567 "AJWUFWMYAPKEAB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32581 "KIKOFVNCKORCLQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32598 "HLIJQLASZKGWOH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32599 "UAUMGDPDXJYFEA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32603 "IVFMQULZHOERQD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32605 "VDJWTUOHANNJDF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32612 "GXDGDJFDEVGAGG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32619 "UJBFGZGANOXCJL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32623 "BZGHXJXIYJQHPD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32625 "ILOZDCUOGJEJCH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32628 "MTGXWOMWDJZIRG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32631 "DCGVTOIURCOUTG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32636 "BXCNYWNFSIIPLA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32637 "IRNFONUGOYHGJW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32644 "OLDNKJIJGGIERX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32646 "GKJLUPOFEZMYFJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32650 "PVIXYGGUGJKUNO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32659 "GDEXQLOLTGBEJQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32671 "OPOWYNFNOYRVIQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32676 "VTAFLKDFSNMRSY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32679 "NOEIMYVGDXWEGP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32693 "HBGOOWKJLYYLQI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32702 "DEAJZBIOBCNNGB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32710 "URLDNRVAIRGYMC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32777 "FPCITNBIKPVDQN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32844 "IHNNGXOPTNDKCV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32884 "WFNHQCAZKZWAIY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32888 "NQQGPQUMTFTHNW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32910 "CTODIYIJKCSOGH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32923 "KZEVXNGNZJUDJX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32959 "CKLYOCQVPIFOLU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C32992 "HPCPLIBPHNDZNB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33047 "MFDIPNCNTFUHPG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33064 "HYPGHBIRDABGAR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33079 "WGBURAOVQKEWFI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33084 "HTCMXUALPRQONI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33113 "OCWLVEAEKHMRFG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33137 "YRJVUGHKAXIDIB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33141 "ZKLSIZZTHLIKHK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33180 "PDWQTMBPESHVBS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33181 "VXYJVXQINILPFZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33214 "KSMAONFYWZLUPF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33218 "UCCWHJONSKISKW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33227 "GTCZSDOSRCVRCR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33233 "SDIHAPJDZJAWLL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33239 "ZAJMDUVKRGDKJU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33255 "CTXHHKZEQAYWRN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33354 "DQLVHFLYLZDELT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33361 "WXNSAJNJUJFUTR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33369 "JDTLVOARJWOFEZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33370 "VDEVOAWYQPRHHP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33377 "SUEZCPCHMYQALM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33379 "JFXRPEUTSJYODF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33388 "UTEJQQZLMUFYTG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33392 "UJWTYEFBCPZPJX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33399 "ISQMSPSMOMHCMW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33421 "YRIQSDWZWLSWIT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33428 "NKGZAXVUVCBFJT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33461 "WSYZTOJLOXBRFF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33531 "MCXMKUCGFQMJBM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33555 "HJFXXWHMBUJBFQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33582 "JOLOUZJKHKRRCY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33607 "VHDRCYDIPVHVFN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33626 "TXIBEIGDHVMIDJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33666 "CRRMKAGLAULBAJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33710 "MLTSGUNODIOABB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33711 "JQYQVLNBXJAVCN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33713 "VTERIDNKLCWUIZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33714 "NDSQHIIDDLZEKA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33718 "WEHXOAGONQNFDD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33727 "NMPAEEBUNALSLZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33732 "PAEZTHGHUVQVNS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33736 "LEETZQLKPJJLQV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33741 "AVXXZVQIGGRXOF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33746 "VNJSKBYBBDFAMT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33772 "RXYSVBWUJAJLCL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33777 "KDWHSELMWBNIEY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33811 "QBQSGHXYXOZFAK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33826 "UKSRMUURYAVJDV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33828 "RDGPABGENMVFQK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33834 "GOOLHOVJRNIKFR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33874 "VHMRANIFAPNBJX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33875 "DTHSRFMJGIQHPN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33886 "RIXOHFOHSMHTJC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33888 "MOGHOESTABKOKH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33893 "YVIZVVXUTJJPBD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33900 "BDKWAMUVARKYHI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33901 "YGUUFHYZFHGSHY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33904 "JZQHRTCBURZZMM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33907 "NTRRHWGNRAQPBF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33911 "RAESRHZKLXTXTR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33916 "RWWPWWGYOJLLAE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33918 "JFEIZMBEEHOIQN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C33955 "SJPWWXHIDHEJAX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34058 "YAOIGINQIHFYGH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34125 "SSFZBJVVIVMHKI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34132 "DDWWVWXDQALHTM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34195 "YEGCDVBSAQLEAA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34212 "NTMRWQMYPGDJME-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34246 "DSZNYJHHXBVHFU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34250 "UNDMYIVPFJCBLX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34261 "UBKVXHPYFGUNBU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34278 "XDLUJLYKAJZIKH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34279 "NEQJBDOGLFFGNU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34281 "IKZVLPUBWDXFPK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34290 "PRRDFMYXQNYYJP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34335 "QGYSCUSJBWROQZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34354 "DXJRPEPFEVWRMS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34454 "GZZJBYFUTHTLEG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34482 "ZXGUOXWYKRAGJB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34489 "DQBOMJUKLXVUOO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34494 "OFQCODABFIQTAP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34498 "WEQNNTUJRNJQJC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34502 "YZCXOEICVVFKLW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34558 "FAIPFNQEBLYXJM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34565 "NJDFDQWAJFNLJY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34569 "JCMILYOMNBKDRK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34668 "VDDSEECFTNXHJW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34672 "MMDMYFZKIZTTTN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34703 "BEMZHPSPHLYWGK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34742 "YWKFKORWYBUHMH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34753 "IQSZRMMYRBLOKU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34773 "JKXAOPSOBFLDTK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34804 "WVQBHRNVYMQPLZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34806 "BHKFBIOJSFKSOX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34816 "OKIABLNOPQTMJW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34840 "MONPNCUPIZSLAI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34842 "KXFNYYMSZNWHFC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34859 "QPOTWHIPJPHPKL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34866 "KEAGODUCIRLECM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34878 "ZDYKFFCLJFVZQW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34888 "KRXBOASNTOACFK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34892 "PYBJVMKMYIXNTP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34912 "AQKWDIQMZFUVIO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34918 "DYWXSZCXHKPGDW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34920 "UBZCKVSLYLOHPL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34922 "DJHWYUCRVXPCDJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34923 "COJHRTXNBUGMCY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34928 "QDZYQACWWXEXRA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34931 "IOBLEUHQWDOBIH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34941 "BLRURUILWRCQEF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34970 "FPDNXSFAHLUYSR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34974 "LYUWDFMRDRXIDW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34982 "SMLXBEFCYOZRAZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C34997 "ATYVCBXSCABLLW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35001 "NSMSNNPWHNHNIX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35037 "BVGSYHMQVNAIGS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35060 "CARATKHTGAMMPP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35070 "XMRJFPSKONDOAG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35086 "ASDUETXDKYOBOV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35090 "IAELZMIOGYXMNQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35094 "FAKVZYVRCODTRY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35109 "WQQHLNOWTVQOIN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35112 "BJGURDSZEQNWMA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35116 "FSZHKBNWNGXCLZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35134 "GZHDFUVXCPZZHG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35161 "XFKCUIKRNAYBMP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35164 "VSYUTJTYWHYVHT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35172 "FXUXWSYLJNQNMF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35184 "WQWALHJBOZOFHZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35221 "HGWIMLPNGHLAGI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35235 "GHWMFKBSZBTFMR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35262 "VTPRSJVYLOGQFT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35334 "AMPKQYJKAFWMKK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35371 "YKUTXBZPXNLKQT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35377 "XJDFENRJAJOBKR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35383 "RWEQECVCBUYOMR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35387 "AANJCKOQSPVUQC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35397 "IFKLLENXPZZRBY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35399 "BNCIVIKCPPETQA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35400 "XSTIVRVKJWQJLF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35401 "ULLLIQWBLCJSLQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35406 "MPATVCRIZMTTSO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35424 "OCGLDIOZUGXDBR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35429 "CJOXTPXWBBOVDC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35433 "GDIRKASRWGPDSM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35434 "JZVSCASNLBYTRB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35454 "PXKGJHWWPABRDK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35482 "GWHAKWDFTCEDAP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35488 "PTTYTSVVJJUJTE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35494 "PTCVQDUZPDFKCY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35496 "NCRSVSRTIIRPQM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35500 "SEHIYXJCXQOHNS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35512 "VIRMWMFIXWCSFR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35526 "HNGXRBQCKSFHPQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35539 "XCTHTPADXIPNKP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35544 "LJFZINHVZMOIMY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35546 "ZUSHZZWHDUXHGD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35550 "ZCHALLWMEWUUHD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35566 "HGFBUWODPQNGMU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35573 "RDWWZRQSGSJUMP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35582 "ZGUWPGWXVHPQHU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35583 "SXICVAULCYXFOU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35586 "MYRPYNSGJHJUMU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35589 "CTKGYDJKCJXAHH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35592 "WTWLIQVCKCHYLZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35593 "WIQJUIUFUBZBIA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35598 "NILPMFQISOIIAX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35599 "MPRLNEHJIGLLSE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35608 "WTCKVQRHKULWED-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35623 "YVRUDUZHGJWBSQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35646 "VLUQEJGAPSYATL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35675 "NPBLHYOHICKKLE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35692 "TWFJLZASZQAOJE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35710 "RRJATQWELNEPBH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35740 "SJKIKHHEECIYBW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35756 "VGBLDGXRCWPURX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35762 "GAXKQVYBFCGUSL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C35894 "LTNRPXLQLPSVHY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36008 "SNQKBBNOVGSZEA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36153 "AOMLEQOQLGFLPB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36156 "GISUBLGMUIVURF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36158 "GBKQAPGMRFCFJS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36163 "RDOBDGZSSKGTHU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36201 "NVURVWBIDBWWCB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36226 "FBMWPVHSXRVSLI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36253 "HUGLBVFZEBSREN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36255 "MEKCCPCJQARDBW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36256 "CYVZMROZHZZWES-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36266 "YAWPWHAMFGVESA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36274 "PWRKCVYLOBXUEM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36320 "QCTNUQJRPCDCEL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36333 "OYKOFQAKSHAGCG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36373 "OVAVVGKVYBUUJF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36433 "VBJMVLPDNOYOTD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36524 "XBWPBDPSKPKGDB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36658 "GFNLMPIANOJETK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36715 "SJNLZDWOKMXQTM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36721 "ZQRZEGCWOHKELN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36731 "UQTVAYFSJAZPHS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36737 "MJAOEDZZNLGKAR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36744 "NGHBHUTYBQCRHS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36769 "VAFPOTHFGPXXOV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36776 "NDCXIEOWMIGQTP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36784 "ZXQINSJIWPINDD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36786 "IZKCLHLCHLPFGS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36796 "GKJGOWOSKCBEAC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36802 "IZOAMVDXRRGPSA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36846 "ALBNIABXIPWXAF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36847 "FBAMDLZTOFRBQZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36848 "QSIXCYJHXWDRAG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36851 "VJYZIPUJZJBTHI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36852 "NMVBKXDXDLTFSD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36857 "YTYWYPCWELPCOC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36865 "BDSILUQPPGZUJV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36871 "MEROHLQYVWGVIP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36876 "WQAURZNNVUOONB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36880 "XPSDLLFVZLUALB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36882 "UVZPTIJGTJQXBZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36921 "XNDLSBYERQVIHW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36928 "APHNPFQKPRADIV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36937 "AHJAKTVCUXZTMK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36938 "XQJWLRVAIIXSLQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36954 "LNHFVGBVLPJPNX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36958 "GRKFHXDGUVDZSM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36961 "YWDJFHSZXKAIPJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36963 "SLYHXADHYALSCG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36964 "LQGMBNUFGVXGBZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36967 "HQYSVVWCCIJIHZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36968 "LWLDJYSCOBMASV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36969 "IPAFLTQSRMAFGJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36971 "VHZGPDSQFFMHDH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36972 "XCWFBSUDPANXSK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36976 "DJQYOSMTOPCXKX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36979 "PYHTYFWLYCTXEE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36984 "CSILFHZVMABLGS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36986 "RUSYVGDVCJWSSK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36988 "JIKXAOCUYDGVJA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C36994 "WBZULIDKRMDMPO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37003 "WJYCGYWKXRAWGS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37009 "KTRYNWBUPOFVAM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37012 "YBGDCCIFIOXAGO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37015 "YTBGOEVGZUSBHY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37017 "JZZRYLMZUCNFHJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37018 "JOEOHSUMSLFAGI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37021 "KRIHGECVGQDSJY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37025 "FIGWNNGEFWPDPU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37026 "VREHJJZBXCWDHC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37034 "AYQAFZSIUVNPTL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37040 "BNPMGSZCUHGGQR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37047 "WVFWOZFTBLQHEA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37050 "VGOZPBAGOORSDS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37052 "SVRJLRPXRZGAEF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37063 "SRGSQXGQLSIKDG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37064 "VCYDTUBFWGNQQG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37073 "DYBRLXZRWNOTOS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37077 "DVNYXGCTQTXANC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37081 "VAIWKNDLEARGJF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37088 "ZQXAXSVDHMRASA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37101 "LPKCCQGWAWOTLN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37109 "BZQPBMLLRMNULA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37111 "NIDXIDKYRXGDHO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37113 "TWZRQMYDFYICDZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37114 "FNRBVBLONGRTMA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37132 "NSSGSWNWCIYKAC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37137 "WNJHKMIXZSISIQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37149 "GZRFRGFNCPVZJI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37158 "OGNAIZBZFVAZHP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37159 "BGMCQTGCRJFANC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37163 "SCACPXRAAXKNTC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37173 "ZCSHBQCCTXHHQY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37175 "PTTPHRFXBLZWAT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37181 "DZVGWXSDXWOZCU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37186 "NWYAWIQCYFLJEZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37201 "OOADHHAXCOFFFC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37203 "RGGIFCGOLRJYEE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37204 "LAGPXDFVROIDEQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37206 "HXZXPMQNAGYRTE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37208 "XZLPNIHQCUMSAG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37216 "CSEITILPHJHCBD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37219 "ARHXKILUXXRFPW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37225 "MDKMMZZVSHXNOY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37231 "PNOSEBXKAGZDKA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37236 "PGOOIOMFBVSSDL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37254 "NQKJBGLWSBXQBD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37255 "CZLOGUWXQFFTQU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37258 "PNUWOTYSFHAYLW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37259 "JZNAFSUZJWYZEQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37261 "RAYAZEORFFINCL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37264 "YYNZABYFMHAFAK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37268 "PVJXDILPPAIEFF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37271 "AWCALMNDIKYDEP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37301 "SPEDQXIAVLGKEG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37305 "JCPWHODBQLGMSS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37341 "JYTWBQYRCHTZAW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37355 "ZESYTFLPEVNJTR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37379 "LBEVZDUOWMWVAZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37382 "ICLAVZHLDRVRPG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37393 "NAAWFQKTVSHBBN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37427 "YDAGAIFMCFHNRC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37439 "JNUJROPEFXLZPI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37453 "MOAWKCCKOHPPBB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37458 "BHJRENTVRKGLJG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37462 "QEOWCKJFPVSFLR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37463 "ACDFYRHXIVZDBA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37465 "IDXOQASWDCFXOY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37468 "HHYPXYWQMSDATR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37474 "JDQIKAQVPLEYNU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37478 "UAKSGJHYLXBQKT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37511 "KQLLKWBEDJXULU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37526 "WTGCCCQAJHKSCC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37531 "WLJQFYQWVJNKGJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37541 "SSDCLPMFGGSNOJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37543 "RGMVVABASKONMI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37547 "XFXCHARPXKEPKI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37554 "FPQPIGUOHMAGDU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37555 "GXRUYNUYXUVCQI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37556 "LHSOFULUZNWMKT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37564 "JAQWSODHSSZHCB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37573 "SMAUVPULZPUOFN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37577 "SFYKUJRVIAYCNI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37580 "LFDXQNYRFLHMMW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37581 "HKYPBOUGJSVKGX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37595 "MNVVHVKFTIYVFM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37600 "UBEANCGSIVAOLP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37605 "GRAOAVAPFANLFK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37608 "YKYAAOVJZZSEPB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37614 "IMBKDSFAVYMYDM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37622 "JQNASAAYNNXCEV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37627 "RXZQKAJOJUZNKZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37640 "ZGKPQEPIGFCUGR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37641 "MYMYZCHOVGVKSW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37643 "NUKXHUOVMRSKLP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37666 "GZBHIILNROBLBK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37707 "XOXHVKFKXBVCDY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37724 "DGKKWSIBKOPHSR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37727 "OULMMIWLKUJUSQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37786 "FFRMZLMYASPMAX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37807 "MUOVYVDWEFCGAQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37821 "MTPLTZGDUBPQBF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37829 "XYXMGVBGXAVTIO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37842 "WJLOOIFXYJICNZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37847 "DBQNZTCIWZPJQN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37868 "KEULZDLXKWCYKD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37910 "SIFQVDTYBKASIM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37944 "HKIBVAYOOMZNJJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37954 "PEVFSJPUVTULJR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37970 "NLYQLRDVZNIXEE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37971 "RXXWLSRGGSICTE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C37994 "PFJRYLXYZBHVNB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38006 "ZOMUTWCHAPGCMM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38009 "HQNCKAAUNQBDIG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38040 "KKPATQNVQDEWIT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38055 "DFNWTKBXLMELIO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38060 "IYXLKPDATFEZAX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38108 "RZHMDQYEPYGJOG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38109 "MUUWOZXFFVCXED-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38119 "BUEOTCYTPUSPMV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38162 "YYDFKBLRUMJUDC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38165 "ZIYQYBMPWSNFJF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38171 "FKANHDCXDAVWCX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38177 "QLQYVKZFOKRXFC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38184 "NTSAYNDZMRSMJO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38201 "WYMUFFJEOKHQQH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38240 "VWJCRAYTNJEGRE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38287 "BOBJRRGCTBTGPJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38343 "OFLAGGQEKFLVFW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38352 "UKHLOWZWOVKHIP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38361 "SJJYNIBBFQAIKR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38363 "HQMXAFLXESYAEL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38372 "MFBOVJHYNZYQRZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38377 "URQSAQKNIPPDKR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38379 "YSFLXCQOQUMFKA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38380 "YUHSCROXCVGKFI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38381 "PDQUROPBETWEKZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38391 "OJEYVYFHCOEOCP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38392 "HEVHFUKGBWHRGY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38393 "DCAKSEDOZAWDDY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38397 "QIYLOAIUHIFSAS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38399 "AWWRKTPXANKXMD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38407 "SDVYTJNJBQTGSB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38427 "YNMNUOATOZYDPM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38433 "KRHHXKAFMXSFDA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38453 "YJQGEWTYBXUVIE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38463 "DNZCCZIPFHSVFG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38467 "PFIJFDQRCOSGSG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38490 "BFEXBTIWTBADPG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38491 "HAOYGSJLNCOVRE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38536 "XQODRUOBZUFPLN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38632 "NBANKVZJDMCTAI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38668 "NRIFVLWDBCDPOG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38684 "GGCAPZUMABTACZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38687 "DJUAGXZMFMEGBZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38710 "VIOIOQYUARLVRI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38744 "OXSGBTRFWCPVST-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38748 "UDQAUMJRPMNFPO-UHFFFAOYSA-O"!

 Warning  Deleting 'Enamine' quotes for C38785 "BNXRMAIXNZUAFS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38804 "VGFBVWWBBRKUCE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38812 "RARHUYLKEARPSI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38829 "MGVRTAOJRGQUCX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38873 "ZIYLEPHOANJEKZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C38878 "WIWSPYXZSJIOMS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39033 "SEMMAHCPRKTGJZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39083 "HTLNFANTBGLVFK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39207 "CTYJETRFKCIEQY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39247 "LHHYDNCNVLAXTB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39319 "KIXQUTJFHHSYGM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39336 "ZKOMOSSSASDFPP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39347 "RZFVUCZGONRKIB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39382 "WBALRDIIJLXHIU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39384 "IGUXRBNXCVYCFQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39412 "JSYXVFBNCLUBQB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39537 "RBVWITRJPMOMKR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39542 "CNXOBVVHQNSJQZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39553 "QYEJIAPDMZXYAN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39561 "QAOMMKKFPGKXSO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39590 "KXNKMAQQYPIXTC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39609 "FJLKXPRKLDOMEE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39617 "HFSLTIYBTZOLEO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39618 "URAUPIRDXYAQNQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39621 "CHJYVTCQEOZSTM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39629 "XTGZDSWLMMXJSE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39633 "VNURJTODJVIMMC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39634 "XGBZZBGVDHLBBY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39640 "VDLPUHYEAORXEM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39690 "PNVTWFSTHBDLAV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39710 "INWPGVBRTKPTIS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39824 "KAWGZIGQAJWGMQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39835 "BDJZWUVLEOIYGS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39851 "HSWKKQXLOLWORQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39865 "QJAIZHXCSLKTJX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39910 "IERDCPAHYOKKFJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39913 "LSHUJNWVIYBKTD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39926 "PBERZXAUQMLAAI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39932 "PNTKFCUWQHSSCF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39962 "QMWOOYQNMGHVSU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39979 "YLQHTSFPYPSXSW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39981 "UGLBHUSBYUSHES-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39986 "MDPBQGJKNCYZOS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C39987 "GIUHBHVCSLUVNC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40004 "SPMVGKHNBCXKKU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40020 "VOZCRZRLYNSPHX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40029 "UWYXTEMHGDHJIW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40052 "SRLBOGOMCJWFQI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40056 "UPMHNSZIPFIGRP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40080 "FEQYMPWGJHEQBZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40092 "YGWGRXPQQZKLRT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40136 "IAIGGBVFJHYVCM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40152 "UHCOIXSLDCEZFH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40159 "PTGYPOHQAADDDF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40173 "MLWXEHYUMYPBSR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40190 "OPFHEBTUUXZQQC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40199 "DHXBKYNTTOIRNA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40203 "IONRYGLGSXFSPJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40210 "AURBOPDLSLCDEM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40283 "DPVILKOBBYLOHP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40301 "BDBFEWUNXUWTNP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40303 "BCJYZXLCRBSLMH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40308 "MPZWTOHSFMUFDK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40318 "DCDRNQHUGNYQEZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40326 "MBRISQIELZAWSP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40334 "IARYHQNKQZFUEG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40336 "DATORCKXSBIXAV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40379 "VMGGUSUHPOAGSJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40393 "AXIJZDVIDRYESV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40411 "QIDNDVNNQQTCIY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40426 "WUMDQAKJIBJBNS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40444 "LWEUMGLYZPVJJH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40445 "QKNYSDDKZKWPRW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40484 "CTWFDIHOJVRQBL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40542 "JZQMVQPBAYISIR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40551 "SLMSHDBKBLQGMS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40553 "PWPOHZUWVIRJJM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40559 "KYOLPOPWUAIFEF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40618 "GRGZLECXJCWSPQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40697 "BMZVEJWCOUCTPY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40786 "PFKDLDBEANMMHT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40801 "SNKYWFRLXCVXKT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40804 "IPMOEXMARLOJMQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40825 "OJIPDPGNVXTDTE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40832 "UDWOFCRCYFHKHP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40881 "SUYMJMYKBMAEBI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40883 "OXJUTCNZUAHHTM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40884 "YLUFFWRQKGFJLY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40892 "RYFSLQQESOBHMB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40914 "JIGOPHUWBOEGJF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40915 "FCJFBVSWKPIIBY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40933 "LAYKYTVRYWIMGW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40943 "TYQZZYWNDFBIAK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40981 "LFSWVNGMWSAAFF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40996 "VYGGJWCZBCMUDU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C40998 "WXDDIVGPHPLQGG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41021 "IBCFVGJRBLHVGP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41100 "XITVNMPNYKYMNK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41122 "UTGRTGWHZNBRDL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41137 "XCODQOWVJVIYJC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41154 "QXBZOVJOSSJDDV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41168 "IWFVRDJKOVOZHU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41217 "GTBBOLNCIMGJHZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41254 "SSWHNAKCQUVWCU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41318 "RPTRFZQZDXEOMU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41343 "OZRWBQRSWXUCNE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41374 "DWSKHAFHCNAPKN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41376 "QSJGIVUXJHAUGF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41380 "JSBVXJYOWWBFDJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41386 "XJZFPSGQSVQVDI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41401 "CKXJMDPMPXKEPR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41411 "IPJBAOHCWMRYAS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41415 "UEMKBNQASCMCLR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41417 "PLZLEIHKDCFDHT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41463 "KTTIQFVXXBBECZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41466 "OYIGYIMWTRFVAY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41483 "HQYUJNAPLGODNB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41491 "CROLKKLLXKJBCA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41508 "YHLCQEMAHUCREL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41518 "HPOADKZDWPBEET-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41591 "PJWNQWAJHCGHIA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41602 "QDIQQSGEVNHYGM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41605 "FDWRCKCBDLYHED-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41621 "REUBKMOUYFOYEN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41633 "TWNFKATYKIQJOL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41642 "PPZKZBFSOFMTOZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41644 "OFVIPXQAOOXQFT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41646 "IVCNKEZJGAIQEE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41648 "RAMMNONVWLYRAI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41667 "BUQPQTPGPJOZNX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41669 "PBJXLSPKRJAENJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41673 "FZUKUIIQNJMWDP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41676 "MYKGKMVDKCPNRO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41677 "ZMLAQUSTMWEOMO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41678 "DWXBKQAQWUENKE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41681 "DSMIRNLXPKNRQX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41701 "KCAYPGJSFFDDSN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41702 "CDVIVRZTWPFGPO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41725 "HIZVJHANPIVSEJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41731 "GLDOVZDXJYAZRK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41732 "ISZQGIZUCPVDTG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41742 "LLYWLTVKBSUYAH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41748 "OYXDLXXZXFYXPX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41752 "FBRIPDMOYVVRTO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41759 "XJRBHNUSFNDHLW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41761 "FBMBDOAFTLCQLI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41764 "FVEKUHMHUVAJCU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41767 "KCIVPXLJVOPNMZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41820 "MQSFWCYRNRUEQZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41821 "GOBDQBAJPRAZBR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41823 "KWCZWUSYBBIDOX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41825 "AIJWJVVVNZKHLG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41832 "YRPRITOLENAXMD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41840 "GYGDBOJGLNZBTI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41889 "GSSPTOQYSYAQHK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41893 "MTASNEMVSHPYKM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41896 "JDNIFNVGDROTPG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41899 "AXLATZBCHKLNJP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41909 "DQFCGSWSTPWDQK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41923 "SAZCVIQRBTVSCH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41924 "NOSQMOANMPCCJA-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41938 "UMADBEPZUIKEOT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41943 "QXRCUBAEQBTWJN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41951 "IXNWSQQGMYNYRU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41955 "DSHPEUREIMMLDD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41991 "PFVGDCLQPPZHFN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41992 "FPXZPEVAGQDEDG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C41999 "KYJOBDYBNUMSND-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42042 "NOSHWWSMXZRTMC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42142 "ASEBXHLHCNZXTK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42149 "SASSEHMZLXPAHV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42203 "PPHDWVYOCZABLE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42208 "LDSAXDWZGXQIFZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42267 "JQDYTNSMZCAEPB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42268 "LQOKDLHFGKARJL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42338 "BQTLWPFLHYROHP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42344 "JCKDPTFRKGFNRH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42437 "UAGVNDIABRZKNV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42496 "QNQQGBAQASHZEK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42498 "YIDYBPJGQOGVPH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42506 "YPBQWXDCTOLUGP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42529 "OQKHXNIPODPCTQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42539 "PCHZGDHHWFXEJJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42545 "KFKMPDFQTYXPIW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42546 "XMGXSRDSLHYZAI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42550 "VMIBQUVCEDZZGM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42552 "OCOMJEJHQGPPLN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42562 "VLNFFUBAAWMSHP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42568 "CJLNETUPSCAECV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42582 "WCUGPRSFJXJLAR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42621 "BYWKDYBUWVLGQV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42624 "KUMIAZYEJZXZKQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42637 "HXMOXFGOLFLQKZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42656 "JCIGKSOBIMHABW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42680 "COKNWLYJJSTVCC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42691 "ASXKQLNUDYSZQN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42695 "DNGJWXDIQCXOJI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42744 "ZNMBKZWBRGGKCY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42853 "NOGZMORTYWUVDU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42864 "CMEFPTCHWAUQBM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42871 "KGZDHXSHQJLZPU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42904 "PSQGMZIOCGDDBQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42924 "CBQWQRCQWNYBQF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42929 "ZTUILTYUOBOJKY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42932 "BOAPGFVZXKOXFF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42950 "LFVFZTYMJAXTQX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42954 "QHCFLNVDEXJYEQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C42988 "LUGLITRDIWTJQZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43015 "OEUAZLUVFDAKNZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43026 "JWNHMHNARZEGLB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43057 "NJZMUARBDGDASX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43062 "JSWAWVRVENINID-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43083 "FYNNFWIMGGOAPC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43105 "OUMZPDLIUZBUEJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43156 "MUDVAFWKIMEKHC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43243 "KDPPBLONVKPKAV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43246 "GWDXZRXLJXWHAW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43288 "LEIYSWQAIQBCDP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43291 "HKPJLMOZYXCBEY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43306 "IAJALLKOBJHSMX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43336 "OQJVSVQHZLHMQO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43363 "ZMCBTMJFDJVIGC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43410 "YLPJHQZNQKTUOI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43414 "SCXIGHSMMDFLNN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43423 "USHGIJHBECJXIQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43441 "BLDRZZPKXALEHG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43462 "MZELUCOUQOURLS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43483 "OFJSNVYGIXIRCF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43490 "KWGDXPUEAXZJNS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43497 "ABVZWWXUBLDHEB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43505 "BKBQWUZJTHIAQT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43525 "QZDBJTHFHKUECW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43527 "ZIGXPMDSIHVQAZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43541 "IWPYBROIVCZRSO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43727 "QIIBZGQRTSXAHF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C43785 "GUPVAHXZWVYEOJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C44304 "WMNSOAYHMBBLEJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C45037 "STYNGALNKQNYRV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C48727 "QRHJXWJEDNGVCX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C49235 "LFJOPEBLDLHNDY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C56096 "BCYRUWSZPDQGBR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C57814 "RSPLUFYFOMHUOI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C58383 "PEMNCQLYCZXYQJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C61214 "CLNOCISDBHNNBK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C65697 "AULDUHQKJWJWFW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70482 "OEVBXDCBFLNYQW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70496 "AKJGWODDFBYWDW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70500 "KEAULGAIXPGKFX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70536 "OCYNPZIVTGLJBR-UHFFFAOYSA-O"!

 Warning  Deleting 'Enamine' quotes for C70544 "CNDHCGIXNQVGMI-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70550 "LHKBPSHMBLTNCD-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70563 "BKCQIVZWFPZPPX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70566 "PESVXDYOTOVXLC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70568 "PFAZBKFGCHTNTK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70584 "VBICFGRVHUMGEE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70586 "YZOZAAMRCRMDKW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70600 "NGJUVEBIHGCBRN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70624 "LCBVWEDEEPBWPW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70685 "IKFLIMCYWKJILX-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70733 "FOYRWJZFBZMFPT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70740 "QQELWSSSVJQNHH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70756 "WAXSLAZOEYQDDU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70875 "JASPDSLTCZRELL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70881 "ZYNDFBSJWRCOLM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70892 "VBWILDQPPYPBPN-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70951 "RNULVZPUFIBHRW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70958 "DHJPMJFNCZNQLK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70959 "OXSGKFUBVPVPLF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70978 "KYFJMOBLDQNAKL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C70984 "LBQMXMLFZTZSBM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71010 "UODJYNBUPNZYMQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71098 "PNEYTBAAWKFEIU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71108 "IDTOUFGRVBHGEV-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71110 "BRKLTDWXXAKBFP-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71111 "IYYKJZSELCTUKO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71154 "YQKCMQBFCUKEIU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71167 "DUIHABQUPONTIZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71210 "JIYBNMQXVOLGMJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71314 "GHBURXZYEIFANE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71320 "QXRGVLGSKXSQLS-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71368 "BTDQOAISOOESSO-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71384 "SUMSXVNUUQVMHL-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71393 "QMHWWCUNLLMGMK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71412 "FTLBCUGZALZAPR-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71413 "HALBYYUTCWTKMF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71423 "RJVPTRKTWXFXIB-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71451 "BPOBVXGNTVHDKT-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71518 "FHEBFUATGCWMRC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71529 "YJXFUTJLMFHVBZ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71552 "NGLMYFWPSDOTRH-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71561 "QXDBAYBLFWOWCE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71575 "SNUKIXMRQQXLSK-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71577 "XHSQPKJRDFEDGC-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71582 "ZOZKLPQFARZXSU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71588 "XADBFEJLWLKDCY-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71590 "PZAVCOUCRVRWBJ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71617 "MLNJKKYXQPTSMM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71634 "PIOCYEWEDQCGSQ-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71635 "NFCLZVXHAMZBMM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71636 "JQYIIQRAJXPGFU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71638 "KAYRJLAKXYZENF-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71639 "APAKQZDFUXTSNU-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71641 "HYNNPQYSIPUAQW-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71646 "UHOOWWVGFAGAIE-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71648 "KSMUOPFIPRMBBG-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71650 "TWYSDNPAUNHTRM-UHFFFAOYSA-N"!

 Warning  Deleting 'Enamine' quotes for C71655 "KFJFUSXXBYNWKV-UHFFFAOYSA-N"!

In [18]:
mod_recipe = hippo.Recipe.from_compounds(cset, quoted_only=True)
mod_recipe

#compounds = 459

Output()

Solving recipe combinations...

Output()

DEBUG: Calculating prices...

Picking cheapest from 1 options

Recipe({Ingredient × 740} --> {Ingredient × 2} --> {Ingredient × 459} via {R × 459})

In [19]:
mod_recipe.write_json("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_quoted.json")

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chem
ok_quoted.json...

In [20]:
mod_recipe.write_CAR_csv("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_quoted_CAR.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chem
ok_quoted_CAR_1steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chem
ok_quoted_CAR_2steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chem
ok_quoted_CAR.csv...

,target-names,no-steps,concentration-required-mM,amount-required-uL,batch-tag,reactant-1-1,reactant-2-1,reaction-product-smiles-1,reaction-name-1,reaction-recipe-1,reaction-groupby-column-1,reactant-3-1,reactant-1-2,reactant-2-2,reaction-product-smiles-2,reaction-name-2,reaction-recipe-2,reaction-groupby-column-2
0,C62668,1,None,None,None,Cc1ccc(N)c2cccnc12,O=C(O)c1cccc2scnc12,Cc1ccc(NC(=O)c2cccc3scnc23)c2cccnc12,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,C61598,1,None,None,None,O=Cc1ccc2c(c1)CNC2,CCCCN,CCCCNCc1ccc2c(c1)CNC2,Reductive_amination,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,C67555,1,None,None,None,O=C1CC(C(=O)O)CCN1,Nc1nnc(C2CCNC2)[nH]1,O=C1CC(C(=O)Nc2nnc(C3CCNC3)[nH]2)CCN1,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,C59954,1,None,None,None,CC(=O)O,NCC12CCCN1CCC2,CC(=O)NCC12CCCN1CCC2,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,C69956,1,None,None,None,NC1Cc2cscc2C1,COC(=O)c1cnc2c(C=O)cccn12,COC(=O)c1cnc2c(CNC3Cc4cscc4C3)cccn12,Reductive_amination,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,C15530,1,None,None,None,CC(=O)O,NCC1CCNC(=O)C1,CC(=O)NCC1CCNC(=O)C1,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
457,C14578,1,None,None,None,Clc1ccc2c(c1)CNC2,O=C(O)c1ccncn1,O=C(c1ccncn1)N1Cc2ccc(Cl)cc2C1,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
458,C5939,1,None,None,None,CCNCc1cccnc1,COc1ccn2c(C(=O)O)cnc2c1,CCN(Cc1cccnc1)C(=O)c1cnc2cc(OC)ccn12,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
459,C64802,1,None,None,None,O=C(O)c1cccc2cn[nH]c12,Nc1nc(-c2cnco2)cs1,O=C(Nc1nc(-c2cnco2)cs1)c1cccc2cn[nH]c12,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
460,C65714,1,None,None,None,O=C(O)c1csc2nccn12,CCOC(C)c1nc(CNC)cs1,CCOC(C)c1nc(CN(C)C(=O)c2csc3nccn23)cs1,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [22]:
mod_recipe.write_reactant_csv("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_quoted_reactants.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

 DISK  Writing cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_quoted_reactants.csv...

In [23]:
mod_recipe.price

€85892.00 EUR

## Generate EUR 10k scaffold recipes

In [24]:
route_pool = hippo.RouteSet.from_product_ids(animal.db, mod_recipe.product_compounds.ids)
route_pool

Output()

{Route × 461}

In [25]:
data = []
for route in mrich.track(route_pool.prune_unavailable(["Enamine"])):
    data.append(dict(product_id=route.product.id, route_id=route.id, chemistry=route.reactions.types[0], price=route.price.amount))
df = pd.DataFrame(data)
df

#routes before pruning = 461

#routes after pruning = 461

Output()

Output()

,product_id,route_id,chemistry,price
0,71544,39,Reductive_amination,226.0
1,76716,108,Sp2-sp2_Suzuki_coupling,36.0
2,74983,119,Mitsunobu_reaction_with_amine_alcohol_and_thio...,299.0
3,76707,125,Sp2-sp2_Suzuki_coupling,36.0
4,119,317,Amidation,277.0
...,...,...,...,...
456,6613,2412,Amidation,89.0
457,59157,2413,Sp3-sp2_Suzuki_coupling,249.0
458,51363,2416,Amidation,49.0
459,13296,2573,N-Boc_deprotection,631.0
460,69166,2796,Amidation,183.0

In [26]:
df_min = df.loc[df.groupby('chemistry')['price'].idxmin()]
df_min = df_min.sort_values("price", ascending=False)
print(df_min["price"].sum())
df_min

1993.0

,product_id,route_id,chemistry,price
281,53862,2076,N-Boc_deprotection,613.0
388,13880,2263,Formation_of_sulfone_from_halide_-_Shavnya_rea...,236.0
413,70416,2310,Williamson_ether_synthesis,196.0
350,62098,2200,Isocyanate_to_urea,194.0
292,67471,2098,Petasis-borono_Mannich_reaction,66.0
45,48859,1679,Nucleophilic_substitution_with_thiol,62.0
148,7519,1847,Steglich_esterification,61.0
313,63027,2126,Chan-Lam_coupling_(amination),51.0
417,9946,2316,Sp3-sp2_Suzuki_coupling,48.0
50,3992,1684,Formation_of_sulfonamide_from_boronic_and_amine,47.0
212,5838,1953,Mitsunobu_reaction_with_amine_alcohol_and_thio...,38.0
54,3857,1693,Ester_amidation,38.0
379,17917,2248,Sulfonamide_Schotten-Baumann_with_amine_(inter...,37.0
12,171,718,Amidation,36.0
215,115821,1959,Formation_of_sulfonamide_from_halide_-_Shavnya...,36.0
430,11169,2340,Buchwald-Hartwig_amination,36.0
26,10692,1644,Formation_of_urea_from_two_amines,36.0
130,48044,1819,Mitsunobu_aryl_ether_synthesis,36.0
1,76716,108,Sp2-sp2_Suzuki_coupling,36.0
7,74617,529,N-nucleophilic_aromatic_substitution,36.0
20,15239,1631,Reductive_amination,36.0
311,59808,2122,N-oxide_formation,18.0

In [27]:
# Starting recipe representing all chemistries
starting_recipe = hippo.Recipe.from_compounds(animal.compounds[list(df_min["product_id"].unique())])
starting_recipe

#compounds = 22

Output()

 Success  Found solution for compound=C171!

 Success  Found solution for compound=C3857!

 Success  Found solution for compound=C3992!

 Success  Found solution for compound=C5838!

 Success  Found solution for compound=C7519!

 Success  Found solution for compound=C9946!

 Success  Found solution for compound=C10692!

 Success  Found solution for compound=C11169!

 Success  Found solution for compound=C13880!

 Success  Found solution for compound=C15239!

 Success  Found solution for compound=C17917!

 Success  Found solution for compound=C48044!

 Success  Found solution for compound=C48859!

 Success  Found solution for compound=C53862!

 Success  Found solution for compound=C59808!

 Success  Found solution for compound=C62098!

 Success  Found solution for compound=C63027!

 Success  Found solution for compound=C67471!

 Success  Found solution for compound=C70416!

 Success  Found solution for compound=C74617!

 Success  Found solution for compound=C76716!

Solving recipe combinations...

Output()

DEBUG: Calculating prices...

Picking cheapest from 1 options

Recipe({Ingredient × 42} --> {Ingredient × 22} via {R × 22})

In [30]:
starting_recipe.write_json("cycle_01/rgen/openbind_xx01zvns2b_c1_scaffold_rgen_starting_recipe.json")
starting_recipe.write_CAR_csv("cycle_01/rgen/openbind_xx01zvns2b_c1_scaffold_rgen_starting_recipe_CAR.csv")

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/rgen/openbind_xx01zvns2b_c1_scaffold_rgen_startin
g_recipe.json...

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/rgen/openbind_xx01zvns2b_c1_scaffold_rgen_startin
g_recipe_CAR_1steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/rgen/openbind_xx01zvns2b_c1_scaffold_rgen_startin
g_recipe_CAR.csv...

,target-names,no-steps,concentration-required-mM,amount-required-uL,batch-tag,reactant-1-1,reactant-2-1,reaction-product-smiles-1,reaction-name-1,reaction-recipe-1,reaction-groupby-column-1,reactant-3-1
0,C70416,1,None,None,None,Cc1nc2cc(O)ccc2n1C,CC(C)CCNC(=O)CCl,Cc1nc2cc(OCC(=O)NCCC(C)C)ccc2n1C,Williamson_ether_synthesis,None,None,<NA>
1,C9946,1,None,None,None,CC1(C)OB(C2CCNCC2)OC1(C)C,Ic1cccc2[nH]ccc12,c1cc(C2CCNCC2)c2cc[nH]c2c1,Sp3-sp2_Suzuki_coupling,None,None,<NA>
2,C48859,1,None,None,None,Sc1ccccn1,CC(Cl)C(=O)Nc1ccc2[nH]c(=O)[nH]c2c1,CC(Sc1ccccn1)C(=O)Nc1ccc2[nH]c(=O)[nH]c2c1,Nucleophilic_substitution_with_thiol,None,None,<NA>
3,C74617,1,None,None,None,CC(C)N,Brc1nnc2ccccn12,CC(C)Nc1nnc2ccccn12,N-nucleophilic_aromatic_substitution,None,None,<NA>
4,C3992,1,None,None,None,OB(O)c1cccc2cccnc12,CNCc1cscn1,CN(Cc1cscn1)S(=O)(=O)c1cccc2cccnc12,Formation_of_sulfonamide_from_boronic_and_amine,None,None,<NA>
5,C62098,1,None,None,None,CCOCCCN=C=O,CC(N)C(=O)N1Cc2ccccc2C1,CCOCCCNC(=O)NC(C)C(=O)N1Cc2ccccc2C1,Isocyanate_to_urea,None,None,<NA>
6,C48044,1,None,None,None,CC(O)C(N)=O,Cc1ccc(O)c(N)n1,Cc1ccc(OC(C)C(N)=O)c(N)n1,Mitsunobu_aryl_ether_synthesis,None,None,<NA>
7,C53862,1,None,None,None,CC(C)(C)OC(=O)N1CCNCC1c1cccnc1,<NA>,c1cncc(C2CNCCN2)c1,N-Boc_deprotection,None,None,<NA>
8,C3857,1,None,None,None,COC(=O)c1ccc2c(c1)CNC2,Cc1n[nH]c2ncc(N)cc12,Cc1n[nH]c2ncc(NC(=O)c3ccc4c(c3)CNC4)cc12,Ester_amidation,None,None,<NA>
9,C5838,1,None,None,None,CNCc1ccccn1,O=C(NCCO)c1cccnc1,CN(CCNC(=O)c1cccnc1)Cc1ccccn1,Mitsunobu_reaction_with_amine_alcohol_and_thio...,None,None,<NA>
10,C11169,1,None,None,None,CC(C)N,Brc1cccc2cc[nH]c12,CC(C)Nc1cccc2cc[nH]c12,Buchwald-Hartwig_amination,None,None,<NA>
11,C115821,1,None,None,None,CC(=O)NCC1CCCNC1,Brc1ccc2ncsc2c1,CC(=O)NCC1CCCN(S(=O)(=O)c2ccc3ncsc3c2)C1,Formation_of_sulfonamide_from_halide_-_Shavnya...,None,None,<NA>
12,C67471,1,None,None,None,CC=O,OB(O)c1cccc2cn[nH]c12,CC(NCc1cnc2ccccc2c1)c1cccc2cn[nH]c12,Petasis-borono_Mannich_reaction,None,None,NCc1cnc2ccccc2c1
13,C7519,1,None,None,None,OCc1cncs1,O=C(O)COc1ncnc2ccccc12,O=C(COc1ncnc2ccccc12)OCc1cncs1,Steglich_esterification,None,None,<NA>
14,C17917,1,None,None,None,O=S(=O)(Cl)c1ccc2ncsc2c1,CCN1CCC(NC)CC1,CCN1CCC(N(C)S(=O)(=O)c2ccc3ncsc3c2)CC1,Sulfonamide_Schotten-Baumann_with_amine_(inter...,None,None,<NA>
15,C59808,1,None,None,None,c1cncc(C2CCCCN2)c1,<NA>,[O-][n+]1cccc(C2CCCCN2)c1,N-oxide_formation,None,None,<NA>
16,C171,1,None,None,None,NCc1cccc(N)c1,O=C1Cc2c(cccc2C(=O)O)N1,NCc1cccc(NC(=O)c2cccc3c2CC(=O)N3)c1,Amidation,None,None,<NA>
17,C63027,1,None,None,None,OB(O)c1ccncc1,COCC(N)COC,COCC(COC)Nc1ccncc1,Chan-Lam_coupling_(amination),None,None,<NA>
18,C13880,1,None,None,None,Brc1ncc[nH]1,COc1nc2ccccc2cc1CCl,COc1nc2ccccc2cc1CS(=O)(=O)c1ncc[nH]1,Formation_of_sulfone_from_halide_-_Shavnya_rea...,None,None,<NA>
19,C15239,1,None,None,None,NC1CCCNC1,COc1nc2ccccc2cc1C=O,COc1nc2ccccc2cc1CNC1CCCNC1,Reductive_amination,None,None,<NA>
20,C10692,1,None,None,None,Nc1ccc2[nH]ccc2c1,C1CCN(C2CCNCC2)C1,O=C(Nc1ccc2[nH]ccc2c1)N1CCC(N2CCCC2)CC1,Formation_of_urea_from_two_amines,None,None,<NA>
21,C76716,1,None,None,None,Cc1cccc(Br)c1,C=CB1OC(C)(C)C(C)(C)O1,C=Cc1cccc(C)c1,Sp2-sp2_Suzuki_coupling,None,None,<NA>

In [31]:
gen = hippo.RandomRecipeGenerator(
    db=animal.db, 
    start_with=starting_recipe, 
    suppliers=['Enamine'],
    route_pool=route_pool,
    out_key="cycle_01/rgen/xx01zvns2b_c1_scaffolds"
)

DEBUG: RandomRecipeGenerator.__init__()

database = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/XX01ZVNS2B/XX01ZVNS2B.sqlite

max_lead_time = None

suppliers =
['Enamine']

out_key = cycle_01/rgen/xx01zvns2b_c1_scaffolds

 DISK  Writing cycle_01/rgen/xx01zvns2b_c1_scaffolds_recipes/...

#routes before pruning = 461

#routes after pruning = 461

Output()

 DISK  Writing cycle_01/rgen/xx01zvns2b_c1_scaffolds_rgen.json...

In [32]:
# test the genenerator
recipe = gen.generate(
    budget = 10_000,
    currency = "EUR",
)

DEBUG: Shuffling Route pool

route pool = 461

max_iter = 461

Output()

 Success  Product pool depleted!

 Success  Completed after 460 iterations!

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/rgen/xx01zvns2b_c1_scaffolds_recipes/Recipe_1GERQ
3S.json...

## Syndirella inputs

In [20]:
recipe.products.compounds.add_tag("openbind_xx01zvns2b_c1_scaffolds_chemok_bbok")

Tagged {C × 459} w/ "openbind_xx01zvns2b_c1_scaffolds_chemok_bbok"

In [21]:
cset = animal.compounds(tag="openbind_xx01zvns2b_c1_scaffolds_chemok_bbok")
cset

compounds tagged openbind_xx01zvns2b_c1_scaffolds_chemok_bbok: {C × 459}

In [22]:
cset_poses = cset.poses
cset_poses

{P × 851}

In [23]:
cset_fstein_poses = cset_poses(tag="fragmenstein_placed")
cset_fstein_poses

{P × 845}

In [24]:
pset = cset_fstein_poses.get_best_placed_poses_per_compound()
pset

{P × 459}

In [5]:
# pset.add_tag("openbind_xx01zvns2b_c1_scaffolds_chemok_bbok")
pset = animal.poses(tag="openbind_xx01zvns2b_c1_scaffolds_chemok_bbok")
pset

poses tagged "openbind_xx01zvns2b_c1_scaffolds_chemok_bbok": {P × 459}

In [6]:
df = recipe.to_syndirella("cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs", pset, separate=True)
df

out_key = xx01zvns2b_c01_elabs

out_dir = cycle_01/syndirella/elabs

 DISK  Writing cycle_01/syndirella/elabs...

 DISK  Writing cycle_01/syndirella/elabs/templates...

DEBUG: querying...

Output()

DEBUG: adding inspiration column(s)

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0844a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z2971a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0089a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0101a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0182a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0422a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0425a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0429a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0435a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0455a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0465a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0472a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0559a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0589a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0605a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0673a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0693a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0701a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0709a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0719a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0727a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0772a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0773b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0788b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0788a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0800a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0819a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0827a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0846b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0846a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0852a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0875a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0917a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0945a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0951a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0969a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z0990a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z1098a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z1274a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z1342a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z1495a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z1597a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z1674a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z1688a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z1716a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z1719a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z1729a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3093a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3465a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3476a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3486a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3503a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3506a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3515a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3527a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3596a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3677a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3685a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3729a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3733a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3799a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3842a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3880a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z3970a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z4245a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z4429a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/Z4959a_apo-desolv.pdb...

DEBUG: querying...

Output()

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_syndirella_inspiration_hits.sdf...

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

Output()

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C71544_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C76716_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C74983_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C76707_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C119_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C99513_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C137_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C74617_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C101237_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C173_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C18613_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C18682_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C171_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C20760_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C22467_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C193_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C27833_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C35751_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C268_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C39979_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C15239_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C52276_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C4207_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C53732_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13330_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C9898_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C10692_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C50969_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C12944_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C51218_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C50099_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C14273_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C52693_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1469_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C14548_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C7401_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1789_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C17115_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C52296_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C15670_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3704_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C50148_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C51869_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C9911_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C15238_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C48859_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3980_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C9884_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C51002_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C17079_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3992_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C52306_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C4121_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C48235_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3857_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C14680_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C16262_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1031_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2328_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C51060_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C50914_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5576_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C51325_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C48853_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C16956_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1967_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C9576_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C48850_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C4305_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C47653_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C6745_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1649_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C52192_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C11345_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C50756_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C54021_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C16969_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C4263_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2006_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C7984_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1717_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2008_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13324_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C17089_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C12439_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13732_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C51867_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C52819_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2037_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2841_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C55564_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C53342_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3936_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3692_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5363_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C48944_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C15322_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C51214_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C47617_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C6526_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C52423_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C7420_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C11823_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5622_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C771_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13030_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C6461_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C17109_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C7721_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C53731_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C52857_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C8888_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C53587_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C55394_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13011_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3735_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2823_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2925_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13044_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1225_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C10180_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C10728_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C54617_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C49238_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C50193_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C55427_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1881_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C824_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3206_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13694_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C48044_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C116932_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C116077_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C12922_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C53652_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3773_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3324_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2106_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13043_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C4318_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C17150_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13423_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5783_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C114282_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C114937_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C4737_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C10062_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C56830_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C7519_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2694_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C10065_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C116294_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C56919_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C8328_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5492_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C10523_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C56798_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C48463_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C11370_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C9466_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C116770_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C784_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13867_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C113667_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C10166_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1906_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C7126_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1434_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5856_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C4933_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C117262_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1728_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C17250_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C113775_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C14982_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C114072_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5831_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C14892_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C55811_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C16770_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C50645_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C9007_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5065_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5866_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C9558_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C56430_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C114014_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C10165_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C115508_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C48240_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5694_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C8113_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C15916_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C113525_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1219_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C48454_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C56508_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C775_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C9579_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C15616_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3289_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C10474_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C9118_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C12342_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C15858_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3693_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C50104_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C56396_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C116066_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C6213_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C116156_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5838_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C117748_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1737_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C115821_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5850_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C51739_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C4139_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C10191_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5187_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C7475_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3291_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C55804_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C8622_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C14536_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C621_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C14716_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2607_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13057_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C10072_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C4344_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C15313_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C4755_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13921_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C453_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C9337_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13206_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3418_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2977_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5811_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C12880_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C9828_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5763_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C15459_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2771_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C6746_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2295_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C6774_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3197_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C8907_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C626_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3739_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C7133_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5852_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13977_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13195_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C10351_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C15515_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C15530_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C14578_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5939_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C64802_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C65714_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C62668_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C61598_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C67555_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59954_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C69956_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C56722_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C64151_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C63174_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C66225_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C58144_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C61950_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C61266_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C61575_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C7770_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C68932_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C62267_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C53862_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C66393_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59572_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C63038_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C60777_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C61309_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C62788_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C62695_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C58690_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C64241_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C62280_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C67471_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C64652_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C60764_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C61607_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C64791_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C68003_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C63241_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59624_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C58671_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C64798_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C60616_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C57216_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C63904_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C68640_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C70364_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C64147_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C65040_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C64818_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C58201_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59808_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C67777_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C63027_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C65217_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C60166_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C66477_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C68732_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3469_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C66556_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C69166_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13296_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C60302_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C60723_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C6489_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C61450_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C65268_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C15448_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C68073_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C61273_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59569_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C66681_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C68443_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C10365_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C60806_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59027_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C58592_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C63711_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C62980_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C49245_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C9697_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C67775_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C7563_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C58017_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C66459_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C64544_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C2807_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C110920_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C107826_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C62013_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C62098_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C112745_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C112217_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C62126_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108386_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59176_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59115_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13863_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108373_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C109200_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108379_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108381_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C109220_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108383_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C111558_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108385_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C60959_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C111861_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C57833_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108392_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108396_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C61503_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108399_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13903_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C6014_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108403_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59573_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108408_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108410_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59253_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C17917_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C68259_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C17132_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59837_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C111931_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59959_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C8117_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C110260_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59613_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13880_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108828_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C62670_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108304_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C60230_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C61042_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C62466_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59541_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C110950_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C13853_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C110271_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C1047_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C107817_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59923_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C5200_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C15917_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C112705_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59610_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C68984_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C70444_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C58440_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C63742_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C112609_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C111786_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108280_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59260_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C70416_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C60966_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C110510_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C109286_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C9946_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108375_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C63872_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C55897_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C112762_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C48749_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C118335_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C118342_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C65345_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C118458_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C118843_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C108582_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C118995_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C11169_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C119032_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C119040_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C119043_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C119044_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C119052_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C119797_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C119143_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C118804_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C58094_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C68703_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C64361_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C61750_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C109063_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C64434_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C67611_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C120734_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C113212_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C66691_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C120359_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C3146_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C65943_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C60165_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C60098_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C51409_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C120894_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C6613_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C59157_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/xx01zvns2b_c01_elabs_C51363_syndirella_input.csv...

,,smiles,compound_set,template,hit1,hit2,hit3,hit4,hit5,hit6,hit7,...,hit33,hit34,hit35,hit36,hit37,reactant_step1,reactant2_step1,product_step1,reaction_name_step1,reactant3_step1
compound_id,pose_id,,,,,,,,,,,,,,,,,,,,,
71544,1036,O=c1[nH]ncn1C1CCN(Cc2c[nH]c3cc(Cl)ccc23)CC1,C71544,Z2971a,Z0435a,Z2971a,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,O=c1[nH]ncn1C1CCNCC1,O=Cc1c[nH]c2cc(Cl)ccc12,O=c1[nH]ncn1C1CCN(Cc2c[nH]c3cc(Cl)ccc23)CC1,Reductive_amination,NaN
76716,2620,Cc1cccc2c(N3CCNCC3)ccnc12,C76716,Z0425a,Z1756a,Z0425a,Z1752a,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Cc1cccc(Br)c1,C=CB1OC(C)(C)C(C)(C)O1,C=Cc1cccc(C)c1,Sp2-sp2_Suzuki_coupling,NaN
74983,2916,CCN(C)[C@H]1CCCN2CCC[C@H]12,C74983,Z0435a,Z0435a,Z3831a,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,OC1CCCN2CCCC12,CCNC,CCN(C)C1CCCN2CCCC12,Mitsunobu_reaction_with_amine_alcohol_and_thio...,NaN
76707,3811,C=Cc1cc(C)cc(N)c1,C76707,Z0589a,Z0589a,Z4827a,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Cc1cc(N)cc(Br)c1,C=CB1OC(C)(C)C(C)(C)O1,C=Cc1cc(C)cc(N)c1,Sp2-sp2_Suzuki_coupling,NaN
119,17076,O=C(Nc1ccc2c(c1)CNC2)c1cc(F)cc2[nH]nnc12,C119,Z3093a,Z3093a,Z5348a,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Nc1ccc2c(c1)CNC2,O=C(O)c1cc(F)cc2[nH]nnc12,O=C(Nc1ccc2c(c1)CNC2)c1cc(F)cc2[nH]nnc12,Amidation,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51409,67822,CCC(C)(C)NC(=O)c1cccc2[nH]ncc12,C51409,Z0701a,Z0701a,Z0719a,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NC(CO)Cc1c[nH]cn1,CCCn1c(C(=O)O)cc2ccccc21,CCCn1c(C(=O)NC(CO)Cc2c[nH]cn2)cc2ccccc21,Amidation,NaN
120894,67830,CC[C@H](C)NC(=O)c1cccc2[nH]ncc12,C120894,Z0701a,Z0701a,Z0719a,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,CCC(C)N,O=C(O)c1cccc2[nH]ncc12,CCC(C)NC(=O)c1cccc2[nH]ncc12,Amidation,NaN
6613,67831,CC(C)C(CNC(=O)c1n[nH]c2ccccc12)C(C)C,C6613,Z0701a,Z0701a,Z0719a,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,CNc1nc2ccccc2s1,Cc1csc(=O)n1CC(=O)O,Cc1csc(=O)n1CC(=O)N(C)c1nc2ccccc2s1,Amidation,NaN
59157,67838,C[S@+]([O-])CCCNC(=O)c1cccc2[nH]ncc12,C59157,Z0701a,Z0701a,Z0719a,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Ic1cccnc1,CC1(C)OB(C23CCNCC2C3)OC1(C)C,c1cncc(C23CCNCC2C3)c1,Sp3-sp2_Suzuki_coupling,NaN
51363,68309,O=S(=O)(c1ccn[nH]1)N1CCC[C@@H]1c1ncccn1,C51363,Z0875a,Z1098a,Z0875a,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NCCc1ncc[nH]1,COc1ccc2cc(C(=O)O)[nH]c2c1,COc1ccc2cc(C(=O)NCCc3ncc[nH]3)[nH]c2c1,Amidation,NaN

## Queue elaboration

```

```