# OpenBind-HIPPO

- **Target: A71EV2A**
- **Cycle: 01**

## Imports

In [17]:
%load_ext autoreload
%autoreload 2
import hippo
import mrich
from mrich import print
from pathlib import Path
from os import environ
import shutil
import molparse as mp
import pandas as pd
import plotly.express as px

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Config

In [18]:
target_name = "XX01ZVNS2B"
target_dir = Path(environ["BULK"]) / "TARGETS" / target_name
cycle_name = "cycle_01"
cycle_dir = Path(cycle_name)
aligned_dir = target_dir / "aligned_files"

## Animal

In [3]:
animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")

 Creating HIPPO animal

name = XX01ZVNS2B

db_path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/XX01ZVNS2B/XX01ZVNS2B.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/XX01ZVNS2B/XX01ZVNS2B.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/XX01ZVNS2B/XX01ZVNS2B.sqlite!

 Success  Initialised animal HIPPO("XX01ZVNS2B")!

In [18]:
df = pd.read_excel("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_1steps.xlsx")#, sheet_name="chem-review")
select = df[df["lisa-select"]=="Y"]
print(len(select))
ids = [int(cname[1:]) for cname in select["target-names"]]
cset = animal.compounds[ids]
cset.add_tag("openbind_xx01zvns2b_c1_scaffolds_chemok")
cset

767

Tagged {C × 767} w/ "openbind_xx01zvns2b_c1_scaffolds_chemok"

{C × 767}

In [19]:
df = pd.read_excel("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_2steps.xlsx")#, sheet_name="chem-review")
select = df[df["lisa-select"]=="Y"]
print(len(select))
ids = [int(cname[1:]) for cname in select["target-names"]]
cset = animal.compounds[ids]
cset.add_tag("openbind_xx01zvns2b_c1_scaffolds_chemok")
cset

0

Tagged {C × 0} w/ "openbind_xx01zvns2b_c1_scaffolds_chemok"

{C × 0}

In [10]:
bbdb = hippo.HIPPO("BB", Path(environ["HOME2"])/"EnamineCatalogs/enamine_bb_hippo.sqlite")

 Creating HIPPO animal

name = BB

db_path = /opt/xchem-fragalysis-2/maxwin/EnamineCatalogs/enamine_bb_hippo.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/EnamineCatalogs/enamine_bb_hippo.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/EnamineCatalogs/enamine_bb_hippo.sqlite!

 Success  Initialised animal HIPPO("BB")!

In [11]:
animal.quote_reactants(bbdb)

#compounds = 3618

Output()

Output()

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

#new quotes = 30140

#quoted_compounds = 1757

#unquoted_compounds = 1861

## Queue BulkDock (re)placements

In [46]:
scaffold_poses = animal.poses(tag="openbind_xx01zvns2b_c1_scaffolds_chemok_bbok")
elaborated_scaffolds = scaffold_poses.compounds.elabs.scaffolds
elaborated_scaffold_poses = animal.poses[set(elaborated_scaffolds.poses.ids).intersection(set(scaffold_poses.ids))]
elaborated_scaffold_poses

{P × 45}

In [47]:
data = []
for i,pose in enumerate(elaborated_scaffold_poses):
    print(i, pose)
    compound = pose.compound
    elabs = compound.elabs
    reference = pose.reference
    inspirations = pose.inspirations

    inspiration_d = dict()
    for i, name in enumerate(inspirations.names):
        inspiration_d[f"hit{i+1}"] = name
    
    for elab in mrich.track(elabs):
        d = dict(smiles=elab.smiles)
        d.update(inspiration_d)
        data.append(d)

df = pd.DataFrame(data)
df.to_csv("cycle_01/syndirella/elabs/xx01zvns2b_c1_elab_bulkdock_input.csv", index=False)
df

0 C119->P17076: "DHEAQALHKCHLOS-UHFFFAOYSA-N"

Output()

1 C18613->P20591: "XFFIHLDPRDKNKR-UHFFFAOYSA-N"

Output()

2 C18682->P20632: "CIWIMLBMRDLEFZ-UHFFFAOYSA-N"

Output()

3 C193->P23307: "LFCFADNCZRJYKM-UHFFFAOYSA-N"

Output()

4 C27833->P24129: "AAOWTMGLVHBFNB-UHFFFAOYSA-N"

Output()

5 C35751->P27622: "KADSGMPYWRRADT-UHFFFAOYSA-N"

Output()

6 C39979->P29376: "YLQHTSFPYPSXSW-UHFFFAOYSA-N"

Output()

7 C5576->P31894: "BWQHUTSQNYTJCI-UHFFFAOYSA-N"

Output()

8 C51867->P36023: "ZTHZBLAVMPXHMP-UHFFFAOYSA-N"

Output()

9 C55811->P44733: "CYPOFIRFZWWIJF-UHFFFAOYSA-N"

Output()

10 C117748->P47327: "HQJVWWZLOLLFOC-UHFFFAOYSA-N"

Output()

11 C4344->P48957: "IANSQNGDXZKZMC-UHFFFAOYSA-N"

Output()

12 C4755->P49137: "FXWZJNDKYPKVCU-UHFFFAOYSA-N"

Output()

13 C9828->P50682: "NAPZUNQCBHIRPL-UHFFFAOYSA-N"

Output()

14 C61266->P54277: "NFFXHWPBOGQOAI-UHFFFAOYSA-N"

Output()

15 C64241->P55921: "NVVXDBBCPYCMRN-UHFFFAOYSA-N"

Output()

16 C64652->P56197: "ZFCFMSIKJGEQIG-UHFFFAOYSA-N"

Output()

17 C64791->P56257: "MFZOQTVMCFTJFC-UHFFFAOYSA-N"

Output()

18 C64798->P56264: "PVWNPFUPWZVGMP-UHFFFAOYSA-N"

Output()

19 C65040->P56493: "RIZNQZOXTPMWOW-UHFFFAOYSA-N"

Output()

20 C60166->P57300: "FLKNWAFFRSIEQV-UHFFFAOYSA-N"

Output()

21 C66477->P57358: "FZPVTGVORHPRMV-UHFFFAOYSA-N"

Output()

22 C65268->P58291: "XJHFOHPLVXEAJK-UHFFFAOYSA-N"

Output()

23 C68073->P58306: "SKDJHYMDJKHBLX-UHFFFAOYSA-N"

Output()

24 C108373->P60858: "HONZPOPPNAQRJH-UHFFFAOYSA-N"

Output()

25 C108379->P60864: "KVVPNFQDRHKSIT-UHFFFAOYSA-N"

Output()

26 C108381->P60865: "FQPYZRHCGIEGGC-UHFFFAOYSA-N"

Output()

27 C108383->P60867: "DPYOJOSEVBEMBW-UHFFFAOYSA-N"

Output()

28 C108385->P60869: "DQRUAVNAEHNBMF-UHFFFAOYSA-N"

Output()

29 C108396->P60878: "KGTBMRSXKDMOPW-UHFFFAOYSA-N"

Output()

30 C108399->P60881: "JKOJGNKTCVRBMD-UHFFFAOYSA-N"

Output()

31 C108403->P60885: "ODAARTYSKDMQEJ-UHFFFAOYSA-N"

Output()

32 C108410->P60891: "AUXIMAVBHFYSOM-UHFFFAOYSA-N"

Output()

33 C108828->P61241: "MDHIDMWPVSUSIH-UHFFFAOYSA-N"

Output()

34 C110510->P63966: "PPXTXQWZJYEIPC-UHFFFAOYSA-N"

Output()

35 C112762->P64483: "ABCCHUVOZOZXSJ-UHFFFAOYSA-N"

Output()

36 C48749->P65060: "XYOFFROFSMOCNR-UHFFFAOYSA-N"

Output()

37 C118335->P65140: "ICULPCWAIXXDSL-UHFFFAOYSA-N"

Output()

38 C118342->P65141: "USLQWDDSHRJFIX-UHFFFAOYSA-N"

Output()

39 C65345->P65161: "DFYBXILNMWHGOO-UHFFFAOYSA-N"

Output()

40 C119032->P65868: "GUQBXRHGLOWICG-UHFFFAOYSA-N"

Output()

41 C119043->P65875: "KQKNLWKVNWUMHC-UHFFFAOYSA-N"

Output()

42 C119143->P65947: "NNBHYCZETFFDQK-UHFFFAOYSA-N"

Output()

43 C61750->P66179: "MMOYNOVVZMWGSB-UHFFFAOYSA-N"

Output()

44 C109063->P66377: "XKJVMBDEKZNDDC-UHFFFAOYSA-N"

Output()

,smiles,hit1,hit2,hit3,hit4,hit5
0,O=C1NCc2cc(NC(=O)c3cc(F)cc4[nH]nnc34)ccc21,Z3093a,Z5348a,NaN,NaN,NaN
1,O=C(Nc1ccc2c(c1)CN(c1ccccc1)C2)c1cc(F)cc2[nH]n...,Z3093a,Z5348a,NaN,NaN,NaN
2,O=C1NC(=O)c2cc(NC(=O)C3CCN(C(=O)c4cc(F)cc5[nH]...,Z3093a,Z5348a,NaN,NaN,NaN
3,O=C(c1ccc2c(c1)C1(CCOCC1)C(=O)N2)N1Cc2ccc(NC(=...,Z3622a,Z3677a,NaN,NaN,NaN
4,CN1Cc2ccc(NC(=O)c3ccc4c(c3)C3(CCOCC3)C(=O)N4)c...,Z3677a,Z4590a,NaN,NaN,NaN
...,...,...,...,...,...,...
8121,CC1CC1CC(=O)Nc1cccc2c1n(C)c(=O)n2C1CCC(=O)NC1=O,Z0846a,Z1597a,NaN,NaN,NaN
8122,Cn1c(=O)n(C2CCC(=O)NC2=O)c2cccc(NC(=O)CCC3CC3)c21,Z0846a,Z1597a,NaN,NaN,NaN
8123,O=C(CCC1CC1)Nc1cc(Cl)cc2nc(-c3cc4ccccc4o3)[nH]c12,Z0846a,Z1597a,NaN,NaN,NaN
8124,O=C(CC1CCC1)Nc1cc(Cl)cc2nc(-c3cc4ccccc4o3)[nH]c12,Z0846a,Z1597a,NaN,NaN,NaN
8125,Cn1c(=O)n(C2CCC(=O)NC2=O)c2cccc(NC(=O)CC3CCC3)c21,Z0846a,Z1597a,NaN,NaN,NaN

## Define chemspace

In [32]:
scaffolds = animal.compounds(tag="openbind_xx01zvns2b_c1_scaffolds_chemok_bbok")
scaffolds

compounds tagged openbind_xx01zvns2b_c1_scaffolds_chemok_bbok: {C × 459}

In [33]:
elabs = scaffolds.elabs
elabs

{C × 13402}

In [34]:
posed_elabs = elabs.poses.compounds
posed_elabs

{C × 4731}

In [35]:
posed_elabs.add_tag("openbind_xx01zvns2b_c1_elabs")

Tagged {C × 4731} w/ "openbind_xx01zvns2b_c1_elabs"

In [36]:
posed_elabs.scaffolds.add_tag("openbind_xx01zvns2b_c1_elaborated_scaffolds")

Tagged {C × 64} w/ "openbind_xx01zvns2b_c1_elaborated_scaffolds"

In [37]:
chemspace = posed_elabs + posed_elabs.scaffolds
chemspace

{C × 4795}

In [38]:
full_recipe = hippo.Recipe.from_compounds(chemspace, use_routes=True, quoted_only=True, pick_first=True, pick_cheapest=False)

#compounds = 4795

Output()

 Warning  Multiple solutions for compound=C69166!

Solving recipe combinations...

Output()

In [39]:
full_recipe

Recipe({Ingredient × 1396} --> {Ingredient × 4795} via {R × 4795})

In [42]:
full_recipe.price

€260576.00 EUR

In [43]:
full_recipe.write_json("cycle_01/syndirella/elabs/openbind_xx01zvns2b_c1_all_elabs.json")

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/syndirella/elabs/openbind_xx01zvns2b_c1_all_elabs
.json...

In [44]:
full_recipe.write_CAR_csv("cycle_01/syndirella/elabs/openbind_xx01zvns2b_c1_all_elabs_CAR.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/syndirella/elabs/openbind_xx01zvns2b_c1_all_elabs
_CAR_1steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/syndirella/elabs/openbind_xx01zvns2b_c1_all_elabs
_CAR.csv...

,target-names,no-steps,concentration-required-mM,amount-required-uL,batch-tag,reactant-1-1,reactant-2-1,reaction-product-smiles-1,reaction-name-1,reaction-recipe-1,reaction-groupby-column-1
0,C142804,1,None,None,None,Nc1ccc2c(c1)CNC2=O,O=C(O)c1ccc2c(c1)C1(CCOCC1)C(=O)N2,O=C(Nc1ccc2c(c1)CNC2=O)c1ccc2c(c1)C1(CCOCC1)C(...,Amidation,None,None
1,C142805,1,None,None,None,O=C(O)c1ccc2c(c1)C1(CCOCC1)C(=O)N2,Nc1ccc2c(c1)C(=O)NC2,O=C(Nc1ccc2c(c1)C(=O)NC2)c1ccc2c(c1)C1(CCOCC1)...,Amidation,None,None
2,C142806,1,None,None,None,O=C(O)c1ccc2c(c1)C1(CCOCC1)C(=O)N2,CN1Cc2ccc(N)cc2C1=O,CN1Cc2ccc(NC(=O)c3ccc4c(c3)C3(CCOCC3)C(=O)N4)c...,Amidation,None,None
3,C149211,1,None,None,None,CC1CCCn2c(CC(=O)O)cnc21,Fc1cncc(Cl)c1CC1CCCCN1,CC1CCCn2c(CC(=O)N3CCCCC3Cc3c(F)cncc3Cl)cnc21,Amidation,None,None
4,C142808,1,None,None,None,O=C(O)c1ccc2c(c1)C1(CCOCC1)C(=O)N2,Nc1cc2c(cc1F)CNC2=O,O=C(Nc1cc2c(cc1F)CNC2=O)c1ccc2c(c1)C1(CCOCC1)C...,Amidation,None,None
...,...,...,...,...,...,...,...,...,...,...,...
4790,C142787,1,None,None,None,Cc1ccc(C(=O)O)c2[nH]cc(C#N)c12,CCN1Cc2ccc(N)cc2C1=O,CCN1Cc2ccc(NC(=O)c3ccc(C)c4c(C#N)c[nH]c34)cc2C1=O,Amidation,None,None
4791,C142788,1,None,None,None,Cc1ccc(C(=O)O)c2[nH]cc(C#N)c12,CN1Cc2cc(N)ccc2C1(C)C,Cc1ccc(C(=O)Nc2ccc3c(c2)CN(C)C3(C)C)c2[nH]cc(C...,Amidation,None,None
4792,C142791,1,None,None,None,Nc1ccc2c(c1)CN(CC(F)F)C2,Cc1ccc(C(=O)O)c2[nH]cc(C#N)c12,Cc1ccc(C(=O)Nc2ccc3c(c2)CN(CC(F)F)C3)c2[nH]cc(...,Amidation,None,None
4793,C142793,1,None,None,None,Nc1ccc2c(c1)CN(CC(F)(F)F)C2,Cc1ccc(C(=O)O)c2[nH]cc(C#N)c12,Cc1ccc(C(=O)Nc2ccc3c(c2)CN(CC(F)(F)F)C3)c2[nH]...,Amidation,None,None
4794,C142794,1,None,None,None,Cc1ccc(C(=O)O)c2[nH]cc(C#N)c12,COCN1C(=O)c2ccc(N)cc2C1=O,COCN1C(=O)c2ccc(NC(=O)c3ccc(C)c4c(C#N)c[nH]c34...,Amidation,None,None

In [45]:
full_recipe.write_reactant_csv("cycle_01/syndirella/elabs/openbind_xx01zvns2b_c1_all_elabs_reactants.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

 DISK  Writing cycle_01/syndirella/elabs/openbind_xx01zvns2b_c1_all_elabs_reactants.csv...