# OpenBind-HIPPO

- **Target: A71EV2A**
- **Cycle: 01**

## Imports

In [1]:
%load_ext autoreload
%autoreload 2
import hippo
import mrich
from mrich import print
from pathlib import Path
from os import environ
import shutil
import molparse as mp
import pandas as pd
import plotly.express as px

## Config

In [2]:
target_name = "D68EV3C"
target_dir = Path(environ["BULK"]) / "TARGETS" / target_name
cycle_name = "cycle_01"
cycle_dir = Path(cycle_name)
aligned_dir = target_dir / "aligned_files"

## Animal

In [5]:
animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")

 Creating HIPPO animal

name = D68EV3C

db_path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C.sqlite!

 Success  Initialised animal HIPPO("D68EV3C")!

## Load chem review

In [9]:
df = pd.read_excel("cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_1steps.xlsx")#, sheet_name="chem-review")
select = df[df["lisa-select"]=="Y"]
print(len(select))
ids = [int(cname[1:]) for cname in select["target-names"]]
cset = animal.compounds[ids]
cset.add_tag("openbind_d68ev3c_c1_scaffolds_chemok")
cset

174

Tagged {C × 174} w/ "openbind_d68ev3c_c1_scaffolds_chemok"

{C × 174}

In [11]:
df = pd.read_excel("cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_2steps.xlsx")#, sheet_name="chem-review")
select = df[df["lisa-select"]=="Y"]
print(len(select))
ids = [int(cname[1:]) for cname in select["target-names"]]
cset = animal.compounds[ids]
cset.add_tag("openbind_d68ev3c_c1_scaffolds_chemok")
cset

0

Tagged {C × 0} w/ "openbind_d68ev3c_c1_scaffolds_chemok"

{C × 0}

In [12]:
df = pd.read_excel("cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_3steps.xlsx")#, sheet_name="chem-review")
select = df[df["lisa-select"]=="Y"]
print(len(select))
ids = [int(cname[1:]) for cname in select["target-names"]]
cset = animal.compounds[ids]
cset.add_tag("openbind_d68ev3c_c1_scaffolds_chemok")
cset

1

Tagged {C × 1} w/ "openbind_d68ev3c_c1_scaffolds_chemok"

{C × 1}

## Quote reactants

In [13]:
bbdb = hippo.HIPPO("BB", Path(environ["HOME2"])/"EnamineCatalogs/enamine_bb_hippo.sqlite")

 Creating HIPPO animal

name = BB

db_path = /opt/xchem-fragalysis-2/maxwin/EnamineCatalogs/enamine_bb_hippo.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/EnamineCatalogs/enamine_bb_hippo.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/EnamineCatalogs/enamine_bb_hippo.sqlite!

 Success  Initialised animal HIPPO("BB")!

In [ ]:
animal.quote_reactants(bbdb)

#compounds = 575

Output()

Output()

## In-Stock recipe

In [ ]:
recipe = hippo.Recipe.from_compounds(cset, quoted_only=True)
recipe

In [ ]:
recipe.write_json("cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_chemok_bbok.json")

In [16]:
df = recipe.write_reactant_csv("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_bbok_reactants.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

 DISK  Writing cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_bbok_reactants.csv...

In [14]:
recipe.write_CAR_csv("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_bbok.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chem
ok_bbok_1steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chem
ok_bbok.csv...

,target-names,no-steps,concentration-required-mM,amount-required-uL,batch-tag,reactant-1-1,reactant-2-1,reaction-product-smiles-1,reaction-name-1,reaction-recipe-1,reaction-groupby-column-1,reactant-3-1
0,C62668,1,None,None,None,Cc1ccc(N)c2cccnc12,O=C(O)c1cccc2scnc12,Cc1ccc(NC(=O)c2cccc3scnc23)c2cccnc12,Amidation,None,None,<NA>
1,C61598,1,None,None,None,O=Cc1ccc2c(c1)CNC2,CCCCN,CCCCNCc1ccc2c(c1)CNC2,Reductive_amination,None,None,<NA>
2,C67555,1,None,None,None,O=C1CC(C(=O)O)CCN1,Nc1nnc(C2CCNC2)[nH]1,O=C1CC(C(=O)Nc2nnc(C3CCNC3)[nH]2)CCN1,Amidation,None,None,<NA>
3,C59954,1,None,None,None,CC(=O)O,NCC12CCCN1CCC2,CC(=O)NCC12CCCN1CCC2,Amidation,None,None,<NA>
4,C69956,1,None,None,None,NC1Cc2cscc2C1,COC(=O)c1cnc2c(C=O)cccn12,COC(=O)c1cnc2c(CNC3Cc4cscc4C3)cccn12,Reductive_amination,None,None,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...
454,C15530,1,None,None,None,CC(=O)O,NCC1CCNC(=O)C1,CC(=O)NCC1CCNC(=O)C1,Amidation,None,None,<NA>
455,C14578,1,None,None,None,Clc1ccc2c(c1)CNC2,O=C(O)c1ccncn1,O=C(c1ccncn1)N1Cc2ccc(Cl)cc2C1,Amidation,None,None,<NA>
456,C5939,1,None,None,None,CCNCc1cccnc1,COc1ccn2c(C(=O)O)cnc2c1,CCN(Cc1cccnc1)C(=O)c1cnc2cc(OC)ccn12,Amidation,None,None,<NA>
457,C64802,1,None,None,None,O=C(O)c1cccc2cn[nH]c12,Nc1nc(-c2cnco2)cs1,O=C(Nc1nc(-c2cnco2)cs1)c1cccc2cn[nH]c12,Amidation,None,None,<NA>
458,C65714,1,None,None,None,O=C(O)c1csc2nccn12,CCOC(C)c1nc(CNC)cs1,CCOC(C)c1nc(CN(C)C(=O)c2csc3nccn23)cs1,Amidation,None,None,<NA>

In [17]:
recipe.write_product_csv("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_bbok_products.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

Output()

Output()

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 recipe.write_product_csv("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_b     │
│   2                                                                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ aligned_dir = PosixPath('/opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/XX01ZVNS2B/aligned… │ │
│ │      animal = HIPPO("XX01ZVNS2B")                                                            │ │
│ │        bbdb = HIPPO("BB")                                                                    │ │
│ │        cset = {C × 767}                                                                      │ │
│ │   cycle_dir = PosixPath('cycle_01')                                                          │ │
│ │  cycle_name = 'cycle_01'                                                                     │ │
│ │          df = None                                                                           │ │
│ │     environ = environ({                                                                      │ │
│ │               │   'HYDRA_LAUNCHER_EXTRA_ARGS': '--external-launcher',                        │ │
│ │               │   'PRECURSOR': '/opt/xchem-fragalysis-2/maxwin/2A_Precursor_FFF',            │ │
│ │               │   'MAMBA_ALWAYS_YES': 'yes',                                                 │ │
│ │               │   'CONDA_SHLVL': '1',                                                        │ │
│ │               │   'LD_LIBRARY_PATH':                                                         │ │
│ │               '/usr/local/cuda/compat:/opt/xchem-fragalysis-2/maxwin/conda/lib:/dls_sw/epic… │ │
│ │               │   'LS_COLORS':                                                               │ │
│ │               'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;… │ │
│ │               │   'CONDA_EXE': '/opt/xchem-fragalysis-2/maxwin/conda/bin/conda',             │ │
│ │               │   'SLURM_NODEID': '0',                                                       │ │
│ │               │   'SLURM_TASK_PID': '157145',                                                │ │
│ │               │   'SSH_CONNECTION': '172.23.162.11 43788 172.23.176.6 22',                   │ │
│ │               │   ... +131                                                                   │ │
│ │               })                                                                             │ │
│ │        exit = <IPython.core.autocall.ZMQExitAutocall object at 0x7f811ccbf920>               │ │
│ │ get_ipython = <bound method InteractiveShell.get_ipython of                                  │ │
│ │               <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f811ceeda30>>             │ │
│ │       hippo = <module 'hippo' from                                                           │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages… │ │
│ │         ids = [                                                                              │ │
│ │               │   62668,                                                                     │ │
│ │               │   55265,                                                                     │ │
│ │               │   67555,                                                                     │ │
│ │               │   59954,                                                                     │ │
│ │               │   56722,                                                                     │ │
│ │               │   64151,                                                                     │ │
│ │               │   63174,                                                                     │ │
│ │               │   58144,                                                                     │ │
│ │               │   61950,                                                                     │ │
│ │               │   7770,                                                                      │ │
│ │               │   ... +757                                                                   │ │
│ │               ]                                                                              │ │
│ │          In = [                                                                              │ │
│ │               │   '',                                                                        │ │
│ │               │   'target_name = "XX01ZVNS2B"\ntarget_dir = Path(environ["BULK"]) /          │ │
│ │               "TARGETS" / targ'+103,                                                         │ │
│ │               │   "get_ipython().run_line_magic('load_ext',                                  │ │
│ │               'autoreload')\nget_ipython().run_line_ma"+204,                                 │ │
│ │               │   'target_name = "XX01ZVNS2B"\ntarget_dir = Path(environ["BULK"]) /          │ │
│ │               "TARGETS" / targ'+103,                                                         │ │
│ │               │   'animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")', │ │
│ │               │   'df =                                                                      │ │
│ │               pd.read_excel("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_1steps'+… │ │
│ │               │   'df =                                                                      │ │
│ │               pd.read_excel("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_1steps'+… │ │
│ │               │   'df.iloc[0]',                                                              │ │
│ │               │   'select = df[df["lisa-select"]=="Y"]\nlen(select)',                        │ │
│ │               │   'ids = [int(cname[1:]) for cname in select["target-names"]]\ncset =        │ │
│ │               animal.compoun'+68,                                                            │ │
│ │               │   ... +8                                                                     │ │
│ │               ]                                                                              │ │
│ │          mp = <module 'molparse' from                                                        │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages… │ │
│ │       mrich = <module 'mrich' from                                                           │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages… │ │
│ │         Out = {                                                                              │ │
│ │               │   7: target-names                                                            │ │
│ │               C109749                                                                        │ │
│ │               no-steps                                                                     1 │ │
│ │               concentration-required-mM                                                  NaN │ │
│ │               amount-required-uL                                                         NaN │ │
│ │               batch-tag                                                                  NaN │ │
│ │               reactant-1-1                                                             NC=NO │ │
│ │               reactant-2-1                                              COC(=O)c1cnn2c1CNCC2 │ │
│ │               reaction-product-smiles-1                              c1noc(-c2cnn3c2CNCC3)n1 │ │
│ │               reaction-name-1              1,2,4-Oxadiazole_synthesis_(amidoxime_+_carbox... │ │
│ │               reaction-recipe-1                                                          NaN │ │
│ │               reaction-groupby-column-1                                                  NaN │ │
│ │               reactant-3-1                                                               NaN │ │
│ │               reactant-4-1                                                               NaN │ │
│ │               warren-select                                                              NaN │ │
│ │               lisa-select                                                                  N │ │
│ │               Unnamed: 15                                                                NaN │ │
│ │               Name: 0, dtype: object,                                                        │ │
│ │               │   8: 767,                                                                    │ │
│ │               │   9: {C × 767},                                                              │ │
│ │               │   12: Recipe({Ingredient × 740} --> {Ingredient × 2} --> {Ingredient × 459}  │ │
│ │               via {R × 459}),                                                                │ │
│ │               │   14:     target-names  no-steps concentration-required-mM                   │ │
│ │               amount-required-uL  \                                                          │ │
│ │               0         C62668         1                      None               None        │ │
│ │               1         C61598         1                      None               None        │ │
│ │               2         C67555         1                      None               None        │ │
│ │               3         C59954         1                      None               None        │ │
│ │               4         C69956         1                      None               None        │ │
│ │               ..           ...       ...                       ...                ...        │ │
│ │               454       C15530         1                      None               None        │ │
│ │               455       C14578         1                      None               None        │ │
│ │               456        C5939         1                      None               None        │ │
│ │               457       C64802         1                      None               None        │ │
│ │               458       C65714         1                      None               None        │ │
│ │               │                                                                              │ │
│ │               │   batch-tag            reactant-1-1               reactant-2-1  \            │ │
│ │               0        None      Cc1ccc(N)c2cccnc12        O=C(O)c1cccc2scnc12               │ │
│ │               1        None      O=Cc1ccc2c(c1)CNC2                      CCCCN               │ │
│ │               2        None      O=C1CC(C(=O)O)CCN1       Nc1nnc(C2CCNC2)[nH]1               │ │
│ │               3        None                 CC(=O)O             NCC12CCCN1CCC2               │ │
│ │               4        None           NC1Cc2cscc2C1  COC(=O)c1cnc2c(C=O)cccn12               │ │
│ │               ..        ...                     ...                        ...               │ │
│ │               454      None                 CC(=O)O             NCC1CCNC(=O)C1               │ │
│ │               455      None       Clc1ccc2c(c1)CNC2             O=C(O)c1ccncn1               │ │
│ │               456      None            CCNCc1cccnc1    COc1ccn2c(C(=O)O)cnc2c1               │ │
│ │               457      None  O=C(O)c1cccc2cn[nH]c12         Nc1nc(-c2cnco2)cs1               │ │
│ │               458      None      O=C(O)c1csc2nccn12        CCOC(C)c1nc(CNC)cs1               │ │
│ │               │   │   │   │                                                                  │ │
│ │               │   │   │   │      reaction-product-smiles-1      reaction-name-1  \           │ │
│ │               0       Cc1ccc(NC(=O)c2cccc3scnc23)c2cccnc12            Amidation              │ │
│ │               1                      CCCCNCc1ccc2c(c1)CNC2  Reductive_amination              │ │
│ │               2      O=C1CC(C(=O)Nc2nnc(C3CCNC3)[nH]2)CCN1            Amidation              │ │
│ │               3                       CC(=O)NCC12CCCN1CCC2            Amidation              │ │
│ │               4       COC(=O)c1cnc2c(CNC3Cc4cscc4C3)cccn12  Reductive_amination              │ │
│ │               ..                                       ...                  ...              │ │
│ │               454                     CC(=O)NCC1CCNC(=O)C1            Amidation              │ │
│ │               455           O=C(c1ccncn1)N1Cc2ccc(Cl)cc2C1            Amidation              │ │
│ │               456     CCN(Cc1cccnc1)C(=O)c1cnc2cc(OC)ccn12            Amidation              │ │
│ │               457  O=C(Nc1nc(-c2cnco2)cs1)c1cccc2cn[nH]c12            Amidation              │ │
│ │               458   CCOC(C)c1nc(CN(C)C(=O)c2csc3nccn23)cs1            Amidation              │ │
│ │               │                                                                              │ │
│ │               │   reaction-recipe-1 reaction-groupby-column-1 reactant-3-1                   │ │
│ │               0                None                      None         <NA>                   │ │
│ │               1                None                      None         <NA>                   │ │
│ │               2                None                      None         <NA>                   │ │
│ │               3                None                      None         <NA>                   │ │
│ │               4                None                      None         <NA>                   │ │
│ │               ..                ...                       ...          ...                   │ │
│ │               454              None                      None         <NA>                   │ │
│ │               455              None                      None         <NA>                   │ │
│ │               456              None                      None         <NA>                   │ │
│ │               457              None                      None         <NA>                   │ │
│ │               458              None                      None         <NA>                   │ │
│ │                                                                                              │ │
│ │               [459 rows x 12 columns]                                                        │ │
│ │               }                                                                              │ │
│ │          pd = <module 'pandas' from                                                          │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/lib/python3.12/site-packages/pandas/__i… │ │
│ │          px = <module 'plotly.express' from                                                  │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages… │ │
│ │        quit = <IPython.core.autocall.ZMQExitAutocall object at 0x7f811ccbf920>               │ │
│ │      recipe = Recipe({Ingredient × 740} --> {Ingredient × 2} --> {Ingredient × 459} via {R × │ │
│ │               459})                                                                          │ │
│ │      select = │   target-names  no-steps  concentration-required-mM  amount-required-uL  \   │ │
│ │               19        C62668         1                        NaN                 NaN      │ │
│ │               20        C55265         1                        NaN                 NaN      │ │
│ │               21        C67555         1                        NaN                 NaN      │ │
│ │               22        C59954         1                        NaN                 NaN      │ │
│ │               23        C56722         1                        NaN                 NaN      │ │
│ │               ..           ...       ...                        ...                 ...      │ │
│ │               899        C3980         1                        NaN                 NaN      │ │
│ │               900        C5811         1                        NaN                 NaN      │ │
│ │               901        C3197         1                        NaN                 NaN      │ │
│ │               905       C70416         1                        NaN                 NaN      │ │
│ │               906      C120410         1                        NaN                 NaN      │ │
│ │               │                                                                              │ │
│ │               │    batch-tag                 reactant-1-1  \                                 │ │
│ │               19         NaN           Cc1ccc(N)c2cccnc12                                    │ │
│ │               20         NaN                     O=C(O)CO                                    │ │
│ │               21         NaN           O=C1CC(C(=O)O)CCN1                                    │ │
│ │               22         NaN                      CC(=O)O                                    │ │
│ │               23         NaN                  CC(O)C(=O)O                                    │ │
│ │               ..         ...                          ...                                    │ │
│ │               899        NaN   O=S(=O)(Cl)Cc1cccc2cccnc12                                    │ │
│ │               900        NaN           COc1ccc2cccnc2c1CN                                    │ │
│ │               901        NaN  O=[N+]([O-])c1ccc2c(c1)CNC2                                    │ │
│ │               905        NaN           Cc1nc2cc(O)ccc2n1C                                    │ │
│ │               906        NaN                 OCc1ccn[nH]1                                    │ │
│ │               │   │   │   │   │   │                                                          │ │
│ │               │   │   │   │   │   │      reactant-2-1  \                                     │ │
│ │               19                  O=C(O)c1cccc2scnc12                                        │ │
│ │               20   CC(N)C1CCCCN1C(=O)c1cccc2[nH]cnc12                                        │ │
│ │               21                 Nc1nnc(C2CCNC2)[nH]1                                        │ │
│ │               22                       NCC12CCCN1CCC2                                        │ │
│ │               23                             Nc1nccs1                                        │ │
│ │               ..                                  ...                                        │ │
│ │               899                         CNCc1scnc1C                                        │ │
│ │               900                 O=S(=O)(Cl)c1ccccn1                                        │ │
│ │               901                 O=S(=O)(Cl)Cc1cscn1                                        │ │
│ │               905                    CC(C)CCNC(=O)CCl                                        │ │
│ │               906                        O=C1CCNCC1Br                                        │ │
│ │               │   │   │   │   │   │                                                          │ │
│ │               │   │   │   │   │   │     reaction-product-smiles-1  \                         │ │
│ │               19             Cc1ccc(NC(=O)c2cccc3scnc23)c2cccnc12                            │ │
│ │               20        CC(NC(=O)CO)C1CCCCN1C(=O)c1cccc2[nH]cnc12                            │ │
│ │               21            O=C1CC(C(=O)Nc2nnc(C3CCNC3)[nH]2)CCN1                            │ │

## Syndirella inputs

In [93]:
cset = animal.compounds(tag="openbind_a71ev2a_c1_scaffolds_chemok_bbok")
cset

compounds tagged openbind_a71ev2a_c1_scaffolds_chemok_bbok: {C × 558}

In [94]:
cset_poses = cset.poses
cset_poses

{P × 15429}

In [95]:
cset_fstein_poses = cset_poses(tag="fragmenstein_placed")
cset_fstein_poses

{P × 15278}

In [96]:
pset = cset_fstein_poses.get_best_placed_poses_per_compound()
pset

{P × 558}

In [97]:
pset.add_tag("openbind_a71ev2a_c1_scaffolds_chemok_bbok")
pset

Tagged {P × 558} w/ "openbind_a71ev2a_c1_scaffolds_chemok_bbok"

{P × 558}

In [131]:
df = recipe.to_syndirella("cycle_01/syndirella/elabs/c01_elabs", pset, separate=True)
df

out_key = c01_elabs

out_dir = cycle_01/syndirella/elabs

DEBUG: querying...

Output()

DEBUG: adding inspiration column(s)

DEBUG: querying...

Output()

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_syndirella_inspiration_hits.sdf...

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

Output()

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47020_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C53713_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C73035_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C48641_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C31471_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C75387_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C51171_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C104497_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C56319_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C51690_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C84541_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C84544_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C64811_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C106545_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C74188_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C49748_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C18489_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C124015_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C54984_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C52583_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C124652_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C124674_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C62872_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C62954_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C57322_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C65382_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C65392_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C16361_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C76291_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C76574_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C59983_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C57140_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C79400_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C53105_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C141599_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C193943_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C204781_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C107_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C205067_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C205775_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C209837_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C176894_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C264727_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C266892_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C195109_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C97354_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C97404_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C50762_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C125028_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C50277_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C78261_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1120_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C52055_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C128372_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C78532_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C43009_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C51476_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46715_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C114736_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47059_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13612_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C124499_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C53746_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46587_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46399_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C51536_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C51256_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C59001_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46960_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46519_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46525_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46545_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C48075_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C66135_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45999_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C52333_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45943_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C49166_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45686_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C63643_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C102808_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2619_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47013_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47021_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7420_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46596_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C65008_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C68883_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C49222_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C65365_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4120_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C53750_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C60642_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45979_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C119723_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46563_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46686_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C105126_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C48665_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C52375_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C52408_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C55108_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C50543_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C55679_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C50224_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C50246_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C51172_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2124_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C59004_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C17883_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46492_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47045_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C55754_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C63895_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C124752_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46913_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13618_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C48055_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C61947_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47626_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C55076_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C60696_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C53753_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C69262_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46019_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2123_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C53762_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C21631_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C55892_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46503_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45868_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C48106_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C18492_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C69436_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45947_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45769_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C48114_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C43016_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C72837_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C26549_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C95588_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C12140_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C72495_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46745_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C54609_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C96564_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45746_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C97204_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C48099_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C48069_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C55828_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47453_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C28778_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C48060_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C9170_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C35473_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C75046_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C21087_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45975_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C51493_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C33363_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4100_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C55900_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7530_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C48047_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C50555_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C27143_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C70623_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C50711_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47450_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C66538_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C51268_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45698_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C49767_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C65117_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C50577_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C68683_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45718_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46497_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47934_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47635_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45621_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C3473_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C99744_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C59009_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C50851_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C119126_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C55819_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C52315_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45810_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C21091_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C51495_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47038_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C49818_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C18151_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47019_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C45987_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C3732_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C104894_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C99297_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47082_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C72721_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47143_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C32955_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C129593_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C22516_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C51490_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C107313_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C54541_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C35612_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C51543_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C69028_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C71025_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47627_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C76428_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C76437_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13655_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C48630_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2409_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5356_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6003_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C9783_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C131861_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1613_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C66955_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13863_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1318_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1366_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C87747_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1384_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C9910_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8874_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C14093_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5654_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1685_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1719_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C15998_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5958_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5959_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5539_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1238_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C24648_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C39872_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6035_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C43497_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C20144_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C14594_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8070_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2418_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C15324_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5996_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2911_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C137292_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8165_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C16607_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C901_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1509_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C11209_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C25407_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C92303_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C12499_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10335_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C20719_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6258_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C875_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C137590_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C137594_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13878_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8470_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C82633_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C39011_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6021_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8952_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C129989_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6632_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7479_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C40896_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C30751_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5452_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8457_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6013_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6034_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C759_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C87026_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2514_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6066_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7605_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1349_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C38623_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C29374_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1414_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C22202_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C20947_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8031_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2306_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C712_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1401_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4781_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C12946_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C16890_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13648_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5394_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10831_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C3768_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C93118_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1169_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C899_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1386_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1391_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2404_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5691_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1807_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4560_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C17161_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C88601_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13635_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C31914_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C533_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7653_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7655_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1338_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6343_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6132_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7634_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1353_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C15036_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C12439_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C29365_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C686_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7499_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C23517_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4764_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5645_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C37776_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C34425_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2081_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C12016_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C33243_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8920_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7587_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C11989_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C12012_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8912_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C27918_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6036_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C3782_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10686_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7188_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C11605_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7524_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4756_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10681_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C717_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7825_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C3542_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13624_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10379_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1322_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7092_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C11248_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C11207_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2040_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7839_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5666_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C42149_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1373_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8160_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1357_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7182_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10683_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C40319_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7443_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8155_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C44440_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C733_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1419_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1602_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1603_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2378_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C31867_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C33915_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8064_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C26592_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C26601_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C760_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8054_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8059_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C21294_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C29031_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8468_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8891_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C9987_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8861_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C22847_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C15735_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C795_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1404_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13636_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8878_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8906_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C15369_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4708_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7185_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C12411_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C83456_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8486_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1360_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1359_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1786_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4106_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C3758_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2609_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C79657_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C84716_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C82790_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6131_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7596_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7644_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7660_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C14910_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5954_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5967_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C22220_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C32415_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6060_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7141_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13629_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10571_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C39794_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C12436_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8041_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2390_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C43738_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C23295_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C12320_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C12352_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5169_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C86181_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8923_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C16455_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7045_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13816_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6181_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6187_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C23130_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4801_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4805_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7599_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C9079_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7166_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4528_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C25347_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C27189_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6170_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C27676_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C27907_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7819_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C28573_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C15053_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C20140_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C29675_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C29686_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C29842_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7140_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C22223_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C29440_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C27712_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10549_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C15058_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1382_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7041_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C11204_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7642_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7673_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C20145_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C27893_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10704_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C43550_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13661_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C20940_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C20970_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C15069_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C91439_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5358_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C41442_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8484_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1418_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5638_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6282_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C82666_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C29678_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7139_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C35886_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C17988_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C18032_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C43172_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C29694_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8445_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C9801_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10567_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C20308_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C3919_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C29671_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8035_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4820_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8485_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C92925_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C2063_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C28323_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C38131_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C9822_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5396_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C14073_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C14078_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8052_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7529_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7674_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C3532_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C678_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C12403_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1002_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C9590_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10333_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7520_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C934_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5997_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C31957_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10575_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10535_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7417_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1406_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C3842_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C3863_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1392_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1399_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8876_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4256_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C33613_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C26238_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1132_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C82527_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C11987_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1455_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C15471_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C15476_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C15494_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6688_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5151_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C89709_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7181_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5313_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C684_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4036_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7625_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7845_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6528_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13918_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C1142_syndirella_input.csv...

,,smiles,reaction_name_step1,reactant_step1,reactant2_step1,reactant3_step1,product_step11,hit1,hit2,hit3,hit4,hit5,hit6,hit7,hit8,template,compound_set
compound_id,pose_id,,,,,,,,,,,,,,,,
47020,1043,C[C@H](NC(=O)NCc1ccnc(N2CCCCC2)c1)C(=O)N1CCCCC1,Formation_of_urea_from_two_amines,NCc1ccnc(N2CCCCC2)c1,CC(N)C(=O)N1CCCCC1,NaN,CC(NC(=O)NCc1ccnc(N2CCCCC2)c1)C(=O)N1CCCCC1,A3868a,A0875a,NaN,NaN,NaN,NaN,NaN,NaN,A3868a,C47020
53713,1740,CCC(=O)N1CCCN(C(=O)CCN2CCOCC2)CC1,Amidation,CCC(=O)N1CCCNCC1,O=C(O)CCN1CCOCC1,NaN,CCC(=O)N1CCCN(C(=O)CCN2CCOCC2)CC1,A4237a,A1779a,NaN,NaN,NaN,NaN,NaN,NaN,A4237a,C53713
73035,2235,O=C(NCc1nnc2n1CCCC2)c1cncc(N2CCCC2)n1,Amidation,O=C(O)c1cncc(N2CCCC2)n1,NCc1nnc2n1CCCC2,NaN,O=C(NCc1nnc2n1CCCC2)c1cncc(N2CCCC2)n1,A0239a,A4855a,NaN,NaN,NaN,NaN,NaN,NaN,A0239a,C73035
48641,2325,CC[C@@H](NC(=O)Nc1cc(CCOC)ccn1)c1cccnc1,Formation_of_urea_from_two_amines,CCC(N)c1cccnc1,COCCc1ccnc(N)c1,NaN,CCC(NC(=O)Nc1cc(CCOC)ccn1)c1cccnc1,A2629a,A3201a,NaN,NaN,NaN,NaN,NaN,NaN,A2629a,C48641
31471,5840,O=C1CCCN1CCC(=O)N1[C@@H]2CC[C@H]1C[C@@H](F)C2,Amidation,O=C(O)CCN1CCCC1=O,FC1CC2CCC(C1)N2,NaN,O=C1CCCN1CCC(=O)N1C2CCC1CC(F)C2,A0528a,A4445b,NaN,NaN,NaN,NaN,NaN,NaN,A4445b,C31471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7625,493064,O=S(=O)(CCCC1CC1)N(C1CCNCC1)C1CC1,Formation_of_sulfonamide_from_halide_-_Shavnya...,ClCCCC1CC1,C1CC(NC2CC2)CCN1,NaN,O=S(=O)(CCCC1CC1)N(C1CCNCC1)C1CC1,A0719a,A3223a,NaN,NaN,NaN,NaN,NaN,NaN,A3223a,C7625
7845,493832,C[C@@H](Cn1cccn1)C(=O)NCC=CCl,Amidation,CC(Cn1cccn1)C(=O)O,NCC=CCl,NaN,CC(Cn1cccn1)C(=O)NCC=CCl,A3306a,A0556a,NaN,NaN,NaN,NaN,NaN,NaN,A3306a,C7845
6528,494667,c1nc([C@@H]2CCNC2)co1,Sp3-sp2_Suzuki_coupling,Ic1cocn1,CC1(C)OB(C2CCNC2)OC1(C)C,NaN,c1nc(C2CCNC2)co1,A3694a,A0556a,NaN,NaN,NaN,NaN,NaN,NaN,A3694a,C6528
13918,495248,CN1C(=O)CC[C@@H]1C(=O)OCC(C)(C)n1cccn1,Steglich_esterification,CN1C(=O)CCC1C(=O)O,CC(C)(CO)n1cccn1,NaN,CN1C(=O)CCC1C(=O)OCC(C)(C)n1cccn1,A2629a,A3956a,NaN,NaN,NaN,NaN,NaN,NaN,A2629a,C13918
1142,496163,COc1ccc2c(c1)[C@H](NC(=O)[C@@H]1CCCCCN1)CCN2,Amidation,O=C(O)C1CCCCCN1,COc1ccc2c(c1)C(N)CCN2,NaN,COc1ccc2c(c1)C(NC(=O)C1CCCCCN1)CCN2,A0586a,A4786a,NaN,NaN,NaN,NaN,NaN,NaN,A4786a,C1142

## Queue elaboration

```

```