# OpenBind-HIPPO

- **Target: A71EV2A**
- **Cycle: 01**

## Imports

In [1]:
%load_ext autoreload
%autoreload 2
import hippo
import mrich
from mrich import print
from pathlib import Path
from os import environ
import shutil
import molparse as mp
import pandas as pd
import plotly.express as px

## Config

In [2]:
target_name = "D68EV3C"
target_dir = Path(environ["BULK"]) / "TARGETS" / target_name
cycle_name = "cycle_01"
cycle_dir = Path(cycle_name)
aligned_dir = target_dir / "aligned_files"

## Animal

In [5]:
animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")

 Creating HIPPO animal

name = D68EV3C

db_path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C.sqlite!

 Success  Initialised animal HIPPO("D68EV3C")!

## Load chem review

In [17]:
df = pd.read_excel("cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_1steps.xlsx")#, sheet_name="chem-review")
select = df[df["lisa-select"]=="Y"]
print(len(select))
ids = [int(cname[1:]) for cname in select["target-names"]]
cset = animal.compounds[ids]
cset.add_tag("openbind_d68ev3c_c1_scaffolds_chemok")
cset

174

Tagged {C × 174} w/ "openbind_d68ev3c_c1_scaffolds_chemok"

{C × 174}

In [18]:
df = pd.read_excel("cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_2steps.xlsx")#, sheet_name="chem-review")
select = df[df["lisa-select"]=="Y"]
print(len(select))
ids = [int(cname[1:]) for cname in select["target-names"]]
cset += animal.compounds[ids]
cset.add_tag("openbind_d68ev3c_c1_scaffolds_chemok")
cset

0

Tagged {C × 174} w/ "openbind_d68ev3c_c1_scaffolds_chemok"

{C × 174}

In [19]:
df = pd.read_excel("cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_3steps.xlsx")#, sheet_name="chem-review")
select = df[df["lisa-select"]=="Y"]
print(len(select))
ids = [int(cname[1:]) for cname in select["target-names"]]
cset += animal.compounds[ids]
cset.add_tag("openbind_d68ev3c_c1_scaffolds_chemok")
cset

1

Tagged {C × 175} w/ "openbind_d68ev3c_c1_scaffolds_chemok"

{C × 175}

## Quote reactants

In [13]:
bbdb = hippo.HIPPO("BB", Path(environ["HOME2"])/"EnamineCatalogs/enamine_bb_hippo.sqlite")

 Creating HIPPO animal

name = BB

db_path = /opt/xchem-fragalysis-2/maxwin/EnamineCatalogs/enamine_bb_hippo.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/EnamineCatalogs/enamine_bb_hippo.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/EnamineCatalogs/enamine_bb_hippo.sqlite!

 Success  Initialised animal HIPPO("BB")!

In [14]:
animal.quote_reactants(bbdb)

#compounds = 575

Output()

Output()

#new quotes = 5950

#quoted_compounds = 359

#unquoted_compounds = 216

## In-Stock recipe

In [20]:
recipe = hippo.Recipe.from_compounds(cset, quoted_only=True)
recipe

#compounds = 175

Output()

 ERROR  Reactants not available for reaction=R242: C167 + C97509 -> C197 via
Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

 ERROR  Reactants not available for reaction=R244: C167 + C97523 -> C197 via
Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

 ERROR  No solutions for compound=C197 (comp.reactions.ids=[242, 244])!

 ERROR  Reactants not available for reaction=R54: C97079 + C97080 -> C624 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C624 (comp.reactions.ids=[54])!

 Success  Found solution for compound=C793!

 ERROR  Reactants not available for reaction=R90: C97177 + C97178 -> C1111 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C1111 (comp.reactions.ids=[90])!

 ERROR  Reactants not available for reaction=R1: C96979 + C96980 -> C1366 via
Buchwald-Hartwig_amination!

 ERROR  No solutions for compound=C1366 (comp.reactions.ids=[1])!

 ERROR  Reactants not available for reaction=R7: C96981 + C96983 + C96990 -> C1418 via
Petasis-borono_Mannich_reaction!

 ERROR  No solutions for compound=C1418 (comp.reactions.ids=[7])!

 ERROR  Reactants not available for reaction=R97: C97190 + C97191 -> C3200 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C3200 (comp.reactions.ids=[97])!

 ERROR  Reactants not available for reaction=R109: C97216 + C97217 + C97218 -> C3330 via
Petasis-borono_Mannich_reaction!

 ERROR  No solutions for compound=C3330 (comp.reactions.ids=[109])!

 Success  Found solution for compound=C4740!

 Success  Found solution for compound=C5010!

 ERROR  Reactants not available for reaction=R322: C97569 + C97696 -> C5200 via Amidation!

 ERROR  No solutions for compound=C5200 (comp.reactions.ids=[322])!

 Success  Found solution for compound=C6030!

 ERROR  Reactants not available for reaction=R305: C97665 + C97666 -> C6391 via Amidation!

 ERROR  No solutions for compound=C6391 (comp.reactions.ids=[305])!

 Success  Found solution for compound=C6392!

 Success  Found solution for compound=C6519!

 Success  Found solution for compound=C6668!

 Success  Found solution for compound=C7379!

 Success  Found solution for compound=C7644!

 ERROR  Reactants not available for reaction=R286: C6362 + C97625 -> C7931 via
Formation_of_urea_from_two_amines!

 ERROR  No solutions for compound=C7931 (comp.reactions.ids=[286])!

 ERROR  Reactants not available for reaction=R306: C97667 + C97668 -> C8130 via Amidation!

 ERROR  No solutions for compound=C8130 (comp.reactions.ids=[306])!

 ERROR  Reactants not available for reaction=R323: C97579 + C97697 -> C8561 via Amidation!

 ERROR  No solutions for compound=C8561 (comp.reactions.ids=[323])!

 ERROR  Reactants not available for reaction=R279: C97602 + C97603 -> C8615 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C8615 (comp.reactions.ids=[279])!

 Success  Found solution for compound=C8782!

 ERROR  Reactants not available for reaction=R357: C97794 + C97795 -> C8797 via Amidation!

 ERROR  No solutions for compound=C8797 (comp.reactions.ids=[357])!

 Success  Found solution for compound=C8896!

 ERROR  Reactants not available for reaction=R317: C97688 + C97689 -> C9337 via Amidation!

 ERROR  No solutions for compound=C9337 (comp.reactions.ids=[317])!

 ERROR  Reactants not available for reaction=R331: C97720 + C97721 -> C9408 via
Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides!

 ERROR  No solutions for compound=C9408 (comp.reactions.ids=[331])!

 Success  Found solution for compound=C9941!

 ERROR  Reactants not available for reaction=R431: C97688 + C97961 -> C10038 via Amidation!

 ERROR  No solutions for compound=C10038 (comp.reactions.ids=[431])!

 Success  Found solution for compound=C10158!

 Success  Found solution for compound=C10168!

 ERROR  Reactants not available for reaction=R302: C94916 + C97656 -> C10267 via Amidation!

 ERROR  No solutions for compound=C10267 (comp.reactions.ids=[302])!

 ERROR  Reactants not available for reaction=R380: C97573 + C97852 -> C10608 via Amidation!

 ERROR  No solutions for compound=C10608 (comp.reactions.ids=[380])!

 ERROR  Reactants not available for reaction=R434: C97965 + C97966 -> C10619 via Amidation!

 ERROR  No solutions for compound=C10619 (comp.reactions.ids=[434])!

 ERROR  No solutions for compound=C10625 (comp.reactions.ids=[366])!

 Success  Found solution for compound=C12064!

 ERROR  Reactants not available for reaction=R253: C97546 + C97547 -> C12434 via Reductive_amination!

 ERROR  No solutions for compound=C12434 (comp.reactions.ids=[253])!

 ERROR  Reactants not available for reaction=R287: C97626 + C97627 -> C12802 via Amidation!

 ERROR  No solutions for compound=C12802 (comp.reactions.ids=[287])!

 ERROR  Reactants not available for reaction=R332: C97724 + C97725 -> C12821 via Amidation!

 ERROR  No solutions for compound=C12821 (comp.reactions.ids=[332])!

 ERROR  Reactants not available for reaction=R282: C97610 + C97611 -> C12873 via Amidation!

 ERROR  No solutions for compound=C12873 (comp.reactions.ids=[282])!

 Success  Found solution for compound=C13421!

 ERROR  Reactants not available for reaction=R277: C97592 + C97593 -> C14395 via
N-nucleophilic_aromatic_substitution!

 ERROR  No solutions for compound=C14395 (comp.reactions.ids=[277])!

 Success  Found solution for compound=C14644!

 ERROR  Reactants not available for reaction=R258: C97556 + C97557 -> C15003 via Amidation!

 ERROR  No solutions for compound=C15003 (comp.reactions.ids=[258])!

 ERROR  Reactants not available for reaction=R428: C97637 + C97953 -> C15320 via Amidation!

 ERROR  No solutions for compound=C15320 (comp.reactions.ids=[428])!

 Success  Found solution for compound=C15381!

 Success  Found solution for compound=C15762!

 ERROR  Reactants not available for reaction=R280: C97604 + C97605 -> C16691 via Amidation!

 ERROR  No solutions for compound=C16691 (comp.reactions.ids=[280])!

 Success  Found solution for compound=C16736!

 Success  Found solution for compound=C17118!

 Success  Found solution for compound=C17133!

 ERROR  Reactants not available for reaction=R288: C97628 + C97629 -> C19520 via Amidation!

 ERROR  No solutions for compound=C19520 (comp.reactions.ids=[288])!

 ERROR  Reactants not available for reaction=R327: C97707 + C97708 -> C19986 via Amidation!

 ERROR  No solutions for compound=C19986 (comp.reactions.ids=[327])!

 Success  Found solution for compound=C20035!

 Success  Found solution for compound=C20165!

 ERROR  Reactants not available for reaction=R343: C97765 + C97766 -> C20704 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C20704 (comp.reactions.ids=[343])!

 ERROR  Reactants not available for reaction=R330: C97718 + C97719 -> C21933 via Reductive_amination!

 ERROR  No solutions for compound=C21933 (comp.reactions.ids=[330])!

 ERROR  Reactants not available for reaction=R320: C97693 + C97694 -> C22085 via Amidation!

 ERROR  No solutions for compound=C22085 (comp.reactions.ids=[320])!

 ERROR  Reactants not available for reaction=R378: C97849 + C97850 -> C22289 via Amidation!

 ERROR  No solutions for compound=C22289 (comp.reactions.ids=[378])!

 Success  Found solution for compound=C22769!

 ERROR  Reactants not available for reaction=R394: C97883 + C97884 -> C22807 via Reductive_amination!

 ERROR  No solutions for compound=C22807 (comp.reactions.ids=[394])!

 ERROR  Reactants not available for reaction=R268: C97575 + C97576 -> C22874 via Amidation!

 ERROR  No solutions for compound=C22874 (comp.reactions.ids=[268])!

 ERROR  Reactants not available for reaction=R349: C97776 + C97777 -> C22925 via Amidation!

 ERROR  No solutions for compound=C22925 (comp.reactions.ids=[349])!

 Success  Found solution for compound=C24299!

 ERROR  Reactants not available for reaction=R274: C97586 + C97587 -> C24504 via Amidation!

 ERROR  No solutions for compound=C24504 (comp.reactions.ids=[274])!

 ERROR  Reactants not available for reaction=R262: C97563 + C97564 -> C24602 via Amidation!

 ERROR  No solutions for compound=C24602 (comp.reactions.ids=[262])!

 Success  Found solution for compound=C25412!

 ERROR  Reactants not available for reaction=R265: C97569 + C97570 -> C25561 via Amidation!

 ERROR  No solutions for compound=C25561 (comp.reactions.ids=[265])!

 ERROR  Reactants not available for reaction=R276: C97590 + C97591 -> C26446 via Amidation!

 ERROR  No solutions for compound=C26446 (comp.reactions.ids=[276])!

 Success  Found solution for compound=C27243!

 Success  Found solution for compound=C27587!

 ERROR  Reactants not available for reaction=R269: C97577 + C97578 -> C27867 via Amidation!

 ERROR  No solutions for compound=C27867 (comp.reactions.ids=[269])!

 ERROR  Reactants not available for reaction=R259: C97558 + C97559 -> C28354 via Amidation!

 ERROR  No solutions for compound=C28354 (comp.reactions.ids=[259])!

 ERROR  Reactants not available for reaction=R347: C97772 + C97773 -> C28379 via Reductive_amination!

 ERROR  No solutions for compound=C28379 (comp.reactions.ids=[347])!

 Success  Found solution for compound=C28382!

 ERROR  Reactants not available for reaction=R295: C97645 + C97646 -> C28399 via Amidation!

 ERROR  No solutions for compound=C28399 (comp.reactions.ids=[295])!

 Success  Found solution for compound=C28511!

 ERROR  Reactants not available for reaction=R289: C97630 + C97631 -> C28536 via Amidation!

 ERROR  No solutions for compound=C28536 (comp.reactions.ids=[289])!

 Success  Found solution for compound=C28548!

 Success  Found solution for compound=C28736!

 ERROR  Reactants not available for reaction=R411: C97923 + C97924 -> C28783 via Amidation!

 ERROR  No solutions for compound=C28783 (comp.reactions.ids=[411])!

 Success  Found solution for compound=C28938!

 Success  Found solution for compound=C29828!

 Success  Found solution for compound=C30056!

 Success  Found solution for compound=C30265!

 ERROR  Reactants not available for reaction=R402: C97655 + C97902 -> C30273 via Amidation!

 ERROR  No solutions for compound=C30273 (comp.reactions.ids=[402])!

 ERROR  Reactants not available for reaction=R298: C97650 + C97651 -> C30528 via Amidation!

 ERROR  No solutions for compound=C30528 (comp.reactions.ids=[298])!

 Success  Found solution for compound=C31678!

 Success  Found solution for compound=C32037!

 Success  Found solution for compound=C32354!

 Success  Found solution for compound=C32763!

 Success  Found solution for compound=C32774!

 ERROR  Reactants not available for reaction=R272: C97583 + C97584 -> C33290 via Amidation!

 ERROR  No solutions for compound=C33290 (comp.reactions.ids=[272])!

 ERROR  Reactants not available for reaction=R321: C5865 + C97695 -> C33499 via
Formation_of_urea_from_two_amines!

 ERROR  No solutions for compound=C33499 (comp.reactions.ids=[321])!

 Success  Found solution for compound=C33707!

 Success  Found solution for compound=C33797!

 ERROR  Reactants not available for reaction=R355: C97790 + C97791 -> C35558 via Amidation!

 ERROR  No solutions for compound=C35558 (comp.reactions.ids=[355])!

 ERROR  Reactants not available for reaction=R440: C97981 + C97982 -> C35601 via Amidation!

 ERROR  No solutions for compound=C35601 (comp.reactions.ids=[440])!

 ERROR  Reactants not available for reaction=R352: C97655 + C97786 -> C36373 via Amidation!

 ERROR  No solutions for compound=C36373 (comp.reactions.ids=[352])!

 ERROR  Reactants not available for reaction=R429: C97655 + C97954 -> C36756 via Amidation!

 ERROR  No solutions for compound=C36756 (comp.reactions.ids=[429])!

 ERROR  Reactants not available for reaction=R255: C97550 + C97551 -> C36757 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C36757 (comp.reactions.ids=[255])!

 ERROR  Reactants not available for reaction=R329: C97655 + C97717 -> C37006 via Amidation!

 ERROR  No solutions for compound=C37006 (comp.reactions.ids=[329])!

 Success  Found solution for compound=C38140!

 ERROR  Reactants not available for reaction=R375: C97655 + C97845 -> C38446 via Amidation!

 ERROR  No solutions for compound=C38446 (comp.reactions.ids=[375])!

 ERROR  Reactants not available for reaction=R388: C97872 + C97873 -> C38631 via Amidation!

 ERROR  No solutions for compound=C38631 (comp.reactions.ids=[388])!

 Success  Found solution for compound=C39494!

 Success  Found solution for compound=C39995!

 ERROR  Reactants not available for reaction=R264: C97567 + C97568 -> C40157 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C40157 (comp.reactions.ids=[264])!

 ERROR  Reactants not available for reaction=R397: C26626 + C97887 -> C45106 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C45106 (comp.reactions.ids=[397])!

 Success  Found solution for compound=C46293!

 ERROR  Reactants not available for reaction=R391: C97813 + C97878 -> C46386 via Amidation!

 ERROR  No solutions for compound=C46386 (comp.reactions.ids=[391])!

 ERROR  Reactants not available for reaction=R364: C97813 + C97814 -> C46391 via Amidation!

 ERROR  No solutions for compound=C46391 (comp.reactions.ids=[364])!

 Success  Found solution for compound=C46521!

 ERROR  Reactants not available for reaction=R438: C97976 + C97977 -> C46835 via Amidation!

 ERROR  No solutions for compound=C46835 (comp.reactions.ids=[438])!

 Success  Found solution for compound=C47228!

 ERROR  Reactants not available for reaction=R386: C97864 + C97865 -> C47435 via
Sp3-sp2_Suzuki_coupling!

 ERROR  No solutions for compound=C47435 (comp.reactions.ids=[386])!

 ERROR  Reactants not available for reaction=R398: C97888 -> C47477 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C47477 (comp.reactions.ids=[398])!

 ERROR  Reactants not available for reaction=R427: C97651 + C97952 -> C47727 via Amidation!

 ERROR  No solutions for compound=C47727 (comp.reactions.ids=[427])!

 ERROR  Reactants not available for reaction=R390: C97876 + C97877 -> C48391 via Amidation!

 ERROR  No solutions for compound=C48391 (comp.reactions.ids=[390])!

 ERROR  Reactants not available for reaction=R423: C97944 + C97945 -> C48399 via Amidation!

 ERROR  No solutions for compound=C48399 (comp.reactions.ids=[423])!

 Success  Found solution for compound=C48494!

 Success  Found solution for compound=C48981!

 Success  Found solution for compound=C49240!

 ERROR  Reactants not available for reaction=R382: C97854 -> C49683 via Reductive_amination!

 ERROR  No solutions for compound=C49683 (comp.reactions.ids=[382])!

 Success  Found solution for compound=C50489!

 ERROR  Reactants not available for reaction=R416: C97655 + C97931 -> C50961 via Amidation!

 ERROR  No solutions for compound=C50961 (comp.reactions.ids=[416])!

 ERROR  Reactants not available for reaction=R301: C97591 + C97655 -> C50965 via Amidation!

 ERROR  No solutions for compound=C50965 (comp.reactions.ids=[301])!

 ERROR  Reactants not available for reaction=R441: C97983 + C97984 -> C51482 via Amidation!

 ERROR  No solutions for compound=C51482 (comp.reactions.ids=[441])!

 ERROR  Reactants not available for reaction=R373: C97841 + C97842 -> C51935 via Amidation!

 ERROR  No solutions for compound=C51935 (comp.reactions.ids=[373])!

 ERROR  Reactants not available for reaction=R369: C97827 + C97828 -> C51983 via
Formation_of_sulfonamide_from_boronic_and_amine!

 ERROR  No solutions for compound=C51983 (comp.reactions.ids=[369])!

 Success  Found solution for compound=C52064!

 ERROR  Reactants not available for reaction=R392: C97879 + C97880 -> C52439 via Ester_amidation!

 ERROR  No solutions for compound=C52439 (comp.reactions.ids=[392])!

 Success  Found solution for compound=C52888!

 Success  Found solution for compound=C54502!

 ERROR  Reactants not available for reaction=R365: C97815 + C97816 -> C54771 via Amidation!

 ERROR  No solutions for compound=C54771 (comp.reactions.ids=[365])!

 ERROR  Reactants not available for reaction=R437: C97893 + C97975 -> C55202 via Amidation!

 ERROR  No solutions for compound=C55202 (comp.reactions.ids=[437])!

 Success  Found solution for compound=C55308!

 Success  Found solution for compound=C55785!

 Success  Found solution for compound=C55917!

 ERROR  Reactants not available for reaction=R384: C97851 + C97862 -> C56038 via Amidation!

 ERROR  No solutions for compound=C56038 (comp.reactions.ids=[384])!

 ERROR  Reactants not available for reaction=R344: C97767 + C97768 -> C56349 via Amidation!

 ERROR  No solutions for compound=C56349 (comp.reactions.ids=[344])!

 ERROR  Reactants not available for reaction=R408: C97549 + C97920 -> C56667 via Reductive_amination!

 ERROR  No solutions for compound=C56667 (comp.reactions.ids=[408])!

 Success  Found solution for compound=C56761!

 Success  Found solution for compound=C57354!

 ERROR  Reactants not available for reaction=R433: C97963 + C97964 -> C58027 via Amidation!

 ERROR  No solutions for compound=C58027 (comp.reactions.ids=[433])!

 ERROR  Reactants not available for reaction=R293: C97637 + C97638 -> C58294 via Amidation!

 ERROR  No solutions for compound=C58294 (comp.reactions.ids=[293])!

 ERROR  Reactants not available for reaction=R399: C97893 + C97894 -> C58499 via Amidation!

 ERROR  No solutions for compound=C58499 (comp.reactions.ids=[399])!

 ERROR  Reactants not available for reaction=R354: C97788 + C97789 -> C58538 via Reductive_amination!

 ERROR  No solutions for compound=C58538 (comp.reactions.ids=[354])!

 Success  Found solution for compound=C59056!

 Success  Found solution for compound=C59662!

 Success  Found solution for compound=C60663!

 Success  Found solution for compound=C60665!

 Success  Found solution for compound=C60777!

 Success  Found solution for compound=C60920!

 ERROR  Reactants not available for reaction=R443: C97986 + C97987 -> C63365 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C63365 (comp.reactions.ids=[443])!

 ERROR  Reactants not available for reaction=R348: C97774 + C97775 -> C63571 via Amidation!

 ERROR  No solutions for compound=C63571 (comp.reactions.ids=[348])!

 ERROR  Reactants not available for reaction=R358: C97796 + C97797 -> C63572 via Amidation!

 ERROR  No solutions for compound=C63572 (comp.reactions.ids=[358])!

 Success  Found solution for compound=C64715!

 Success  Found solution for compound=C65802!

 Success  Found solution for compound=C65808!

 Success  Found solution for compound=C67927!

 ERROR  Reactants not available for reaction=R314: C97684 + C97685 -> C70501 via Amidation!

 ERROR  No solutions for compound=C70501 (comp.reactions.ids=[314])!

 ERROR  Reactants not available for reaction=R379: C68492 + C97851 -> C73145 via Amidation!

 ERROR  No solutions for compound=C73145 (comp.reactions.ids=[379])!

 ERROR  Reactants not available for reaction=R290: C97189 + C97632 -> C74593 via Reductive_amination!

 ERROR  No solutions for compound=C74593 (comp.reactions.ids=[290])!

 ERROR  Reactants not available for reaction=R294: C97639 + C97640 -> C75318 via Amine_alkylation!

 ERROR  No solutions for compound=C75318 (comp.reactions.ids=[294])!

 Success  Found solution for compound=C75727!

 ERROR  Reactants not available for reaction=R383: C97860 + C97861 -> C76545 via Amidation!

 ERROR  No solutions for compound=C76545 (comp.reactions.ids=[383])!

 Success  Found solution for compound=C76789!

 Success  Found solution for compound=C79165!

 Success  Found solution for compound=C81324!

 ERROR  Reactants not available for reaction=R425: C97948 + C97949 -> C82192 via Reductive_amination!

 ERROR  No solutions for compound=C82192 (comp.reactions.ids=[425])!

 ERROR  Reactants not available for reaction=R419: C97935 + C97936 -> C84049 via Amidation!

 ERROR  No solutions for compound=C84049 (comp.reactions.ids=[419])!

 Success  Found solution for compound=C84677!

 ERROR  Reactants not available for reaction=R318: C97690 + C97691 -> C90248 via Amidation!

 ERROR  No solutions for compound=C90248 (comp.reactions.ids=[318])!

 ERROR  Reactants not available for reaction=R310: C97675 + C97676 -> C95401 via
Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol!

 ERROR  No solutions for compound=C95401 (comp.reactions.ids=[310])!

Solving recipe combinations...

Output()

DEBUG: Calculating prices...

Picking cheapest from 1 options

Recipe({Ingredient × 144} --> {Ingredient × 77} via {R × 77})

In [21]:
recipe.write_json("cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_chemok_bbok.json")

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/d68ev3c/cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_chemok_bbo
k.json...

In [22]:
df = recipe.write_reactant_csv("cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_chemok_bbok_reactants.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

 DISK  Writing cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_chemok_bbok_reactants.csv...

In [23]:
recipe.write_CAR_csv("cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_chemok_bbok.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/d68ev3c/cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_chemok_bbo
k_1steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/d68ev3c/cycle_01/chem_review/openbind_d68ev3c_c1_scaffolds_chemok_bbo
k.csv...

,target-names,no-steps,concentration-required-mM,amount-required-uL,batch-tag,reactant-1-1,reactant-2-1,reaction-product-smiles-1,reaction-name-1,reaction-recipe-1,reaction-groupby-column-1,reactant-3-1
0,C793,1,None,None,None,O=C(O)c1sc(F)cc1Br,CC1(C)OB(CCC(=O)O)OC1(C)C,O=C(O)CCc1cc(F)sc1C(=O)O,Sp3-sp2_Suzuki_coupling,None,None,<NA>
1,C27587,1,None,None,None,O=C(O)c1csc(N2CCCCC2)n1,CC(CN)[S+](C)[O-],CC(CNC(=O)c1csc(N2CCCCC2)n1)[S+](C)[O-],Amidation,None,None,<NA>
2,C38140,1,None,None,None,CCOC(=O)C1CCNC1,O=C(O)C(O)C1CCOCC1,CCOC(=O)C1CCN(C(=O)C(O)C2CCOCC2)C1,Amidation,None,None,<NA>
3,C13421,1,None,None,None,Nc1cnn(CC(=O)O)c1,CC(CC(=O)O)n1cccn1,CC(CC(=O)Nc1cnn(CC(=O)O)c1)n1cccn1,Amidation,None,None,<NA>
4,C29828,1,None,None,None,NC(Cc1cnc[nH]1)C(=O)O,Cc1nc2ccccn2c1C=O,Cc1nc2ccccn2c1CNC(Cc1cnc[nH]1)C(=O)O,Reductive_amination,None,None,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...
72,C49240,1,None,None,None,O=C(O)c1cnc2n1CCS2,Nc1cccc2c1ccn2C(F)F,O=C(Nc1cccc2c1ccn2C(F)F)c1cnc2n1CCS2,Amidation,None,None,<NA>
73,C7379,1,None,None,None,CC(C)S(=O)(=O)C1CCNC1,CC(N)c1cn[nH]c1,CC(NC(=O)N1CCC(S(=O)(=O)C(C)C)C1)c1cn[nH]c1,Formation_of_urea_from_two_amines,None,None,<NA>
74,C55308,1,None,None,None,CC(C)(C)c1nc2cc(N)ccc2o1,CC(=O)c1c[nH]cn1,CC(Nc1ccc2oc(C(C)(C)C)nc2c1)c1c[nH]cn1,Reductive_amination,None,None,<NA>
75,C28511,1,None,None,None,NCc1cnc2nccn2c1,Clc1cccnc1,O=S(=O)(NCc1cnc2nccn2c1)c1cccnc1,Formation_of_sulfonamide_from_halide_-_Shavnya...,None,None,<NA>
76,C32763,1,None,None,None,c1c[nH]c(N2CCNCC2)n1,O=C(O)CCc1ccc2ncsc2c1,O=C(CCc1ccc2ncsc2c1)N1CCN(c2ncc[nH]2)CC1,Amidation,None,None,<NA>

In [17]:
recipe.write_product_csv("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_bbok_products.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

Output()

Output()

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 recipe.write_product_csv("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_chemok_b     │
│   2                                                                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ aligned_dir = PosixPath('/opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/XX01ZVNS2B/aligned… │ │
│ │      animal = HIPPO("XX01ZVNS2B")                                                            │ │
│ │        bbdb = HIPPO("BB")                                                                    │ │
│ │        cset = {C × 767}                                                                      │ │
│ │   cycle_dir = PosixPath('cycle_01')                                                          │ │
│ │  cycle_name = 'cycle_01'                                                                     │ │
│ │          df = None                                                                           │ │
│ │     environ = environ({                                                                      │ │
│ │               │   'HYDRA_LAUNCHER_EXTRA_ARGS': '--external-launcher',                        │ │
│ │               │   'PRECURSOR': '/opt/xchem-fragalysis-2/maxwin/2A_Precursor_FFF',            │ │
│ │               │   'MAMBA_ALWAYS_YES': 'yes',                                                 │ │
│ │               │   'CONDA_SHLVL': '1',                                                        │ │
│ │               │   'LD_LIBRARY_PATH':                                                         │ │
│ │               '/usr/local/cuda/compat:/opt/xchem-fragalysis-2/maxwin/conda/lib:/dls_sw/epic… │ │
│ │               │   'LS_COLORS':                                                               │ │
│ │               'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;… │ │
│ │               │   'CONDA_EXE': '/opt/xchem-fragalysis-2/maxwin/conda/bin/conda',             │ │
│ │               │   'SLURM_NODEID': '0',                                                       │ │
│ │               │   'SLURM_TASK_PID': '157145',                                                │ │
│ │               │   'SSH_CONNECTION': '172.23.162.11 43788 172.23.176.6 22',                   │ │
│ │               │   ... +131                                                                   │ │
│ │               })                                                                             │ │
│ │        exit = <IPython.core.autocall.ZMQExitAutocall object at 0x7f811ccbf920>               │ │
│ │ get_ipython = <bound method InteractiveShell.get_ipython of                                  │ │
│ │               <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f811ceeda30>>             │ │
│ │       hippo = <module 'hippo' from                                                           │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages… │ │
│ │         ids = [                                                                              │ │
│ │               │   62668,                                                                     │ │
│ │               │   55265,                                                                     │ │
│ │               │   67555,                                                                     │ │
│ │               │   59954,                                                                     │ │
│ │               │   56722,                                                                     │ │
│ │               │   64151,                                                                     │ │
│ │               │   63174,                                                                     │ │
│ │               │   58144,                                                                     │ │
│ │               │   61950,                                                                     │ │
│ │               │   7770,                                                                      │ │
│ │               │   ... +757                                                                   │ │
│ │               ]                                                                              │ │
│ │          In = [                                                                              │ │
│ │               │   '',                                                                        │ │
│ │               │   'target_name = "XX01ZVNS2B"\ntarget_dir = Path(environ["BULK"]) /          │ │
│ │               "TARGETS" / targ'+103,                                                         │ │
│ │               │   "get_ipython().run_line_magic('load_ext',                                  │ │
│ │               'autoreload')\nget_ipython().run_line_ma"+204,                                 │ │
│ │               │   'target_name = "XX01ZVNS2B"\ntarget_dir = Path(environ["BULK"]) /          │ │
│ │               "TARGETS" / targ'+103,                                                         │ │
│ │               │   'animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")', │ │
│ │               │   'df =                                                                      │ │
│ │               pd.read_excel("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_1steps'+… │ │
│ │               │   'df =                                                                      │ │
│ │               pd.read_excel("cycle_01/chem_review/openbind_xx01zvns2b_c1_scaffolds_1steps'+… │ │
│ │               │   'df.iloc[0]',                                                              │ │
│ │               │   'select = df[df["lisa-select"]=="Y"]\nlen(select)',                        │ │
│ │               │   'ids = [int(cname[1:]) for cname in select["target-names"]]\ncset =        │ │
│ │               animal.compoun'+68,                                                            │ │
│ │               │   ... +8                                                                     │ │
│ │               ]                                                                              │ │
│ │          mp = <module 'molparse' from                                                        │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages… │ │
│ │       mrich = <module 'mrich' from                                                           │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages… │ │
│ │         Out = {                                                                              │ │
│ │               │   7: target-names                                                            │ │
│ │               C109749                                                                        │ │
│ │               no-steps                                                                     1 │ │
│ │               concentration-required-mM                                                  NaN │ │
│ │               amount-required-uL                                                         NaN │ │
│ │               batch-tag                                                                  NaN │ │
│ │               reactant-1-1                                                             NC=NO │ │
│ │               reactant-2-1                                              COC(=O)c1cnn2c1CNCC2 │ │
│ │               reaction-product-smiles-1                              c1noc(-c2cnn3c2CNCC3)n1 │ │
│ │               reaction-name-1              1,2,4-Oxadiazole_synthesis_(amidoxime_+_carbox... │ │
│ │               reaction-recipe-1                                                          NaN │ │
│ │               reaction-groupby-column-1                                                  NaN │ │
│ │               reactant-3-1                                                               NaN │ │
│ │               reactant-4-1                                                               NaN │ │
│ │               warren-select                                                              NaN │ │
│ │               lisa-select                                                                  N │ │
│ │               Unnamed: 15                                                                NaN │ │
│ │               Name: 0, dtype: object,                                                        │ │
│ │               │   8: 767,                                                                    │ │
│ │               │   9: {C × 767},                                                              │ │
│ │               │   12: Recipe({Ingredient × 740} --> {Ingredient × 2} --> {Ingredient × 459}  │ │
│ │               via {R × 459}),                                                                │ │
│ │               │   14:     target-names  no-steps concentration-required-mM                   │ │
│ │               amount-required-uL  \                                                          │ │
│ │               0         C62668         1                      None               None        │ │
│ │               1         C61598         1                      None               None        │ │
│ │               2         C67555         1                      None               None        │ │
│ │               3         C59954         1                      None               None        │ │
│ │               4         C69956         1                      None               None        │ │
│ │               ..           ...       ...                       ...                ...        │ │
│ │               454       C15530         1                      None               None        │ │
│ │               455       C14578         1                      None               None        │ │
│ │               456        C5939         1                      None               None        │ │
│ │               457       C64802         1                      None               None        │ │
│ │               458       C65714         1                      None               None        │ │
│ │               │                                                                              │ │
│ │               │   batch-tag            reactant-1-1               reactant-2-1  \            │ │
│ │               0        None      Cc1ccc(N)c2cccnc12        O=C(O)c1cccc2scnc12               │ │
│ │               1        None      O=Cc1ccc2c(c1)CNC2                      CCCCN               │ │
│ │               2        None      O=C1CC(C(=O)O)CCN1       Nc1nnc(C2CCNC2)[nH]1               │ │
│ │               3        None                 CC(=O)O             NCC12CCCN1CCC2               │ │
│ │               4        None           NC1Cc2cscc2C1  COC(=O)c1cnc2c(C=O)cccn12               │ │
│ │               ..        ...                     ...                        ...               │ │
│ │               454      None                 CC(=O)O             NCC1CCNC(=O)C1               │ │
│ │               455      None       Clc1ccc2c(c1)CNC2             O=C(O)c1ccncn1               │ │
│ │               456      None            CCNCc1cccnc1    COc1ccn2c(C(=O)O)cnc2c1               │ │
│ │               457      None  O=C(O)c1cccc2cn[nH]c12         Nc1nc(-c2cnco2)cs1               │ │
│ │               458      None      O=C(O)c1csc2nccn12        CCOC(C)c1nc(CNC)cs1               │ │
│ │               │   │   │   │                                                                  │ │
│ │               │   │   │   │      reaction-product-smiles-1      reaction-name-1  \           │ │
│ │               0       Cc1ccc(NC(=O)c2cccc3scnc23)c2cccnc12            Amidation              │ │
│ │               1                      CCCCNCc1ccc2c(c1)CNC2  Reductive_amination              │ │
│ │               2      O=C1CC(C(=O)Nc2nnc(C3CCNC3)[nH]2)CCN1            Amidation              │ │
│ │               3                       CC(=O)NCC12CCCN1CCC2            Amidation              │ │
│ │               4       COC(=O)c1cnc2c(CNC3Cc4cscc4C3)cccn12  Reductive_amination              │ │
│ │               ..                                       ...                  ...              │ │
│ │               454                     CC(=O)NCC1CCNC(=O)C1            Amidation              │ │
│ │               455           O=C(c1ccncn1)N1Cc2ccc(Cl)cc2C1            Amidation              │ │
│ │               456     CCN(Cc1cccnc1)C(=O)c1cnc2cc(OC)ccn12            Amidation              │ │
│ │               457  O=C(Nc1nc(-c2cnco2)cs1)c1cccc2cn[nH]c12            Amidation              │ │
│ │               458   CCOC(C)c1nc(CN(C)C(=O)c2csc3nccn23)cs1            Amidation              │ │
│ │               │                                                                              │ │
│ │               │   reaction-recipe-1 reaction-groupby-column-1 reactant-3-1                   │ │
│ │               0                None                      None         <NA>                   │ │
│ │               1                None                      None         <NA>                   │ │
│ │               2                None                      None         <NA>                   │ │
│ │               3                None                      None         <NA>                   │ │
│ │               4                None                      None         <NA>                   │ │
│ │               ..                ...                       ...          ...                   │ │
│ │               454              None                      None         <NA>                   │ │
│ │               455              None                      None         <NA>                   │ │
│ │               456              None                      None         <NA>                   │ │
│ │               457              None                      None         <NA>                   │ │
│ │               458              None                      None         <NA>                   │ │
│ │                                                                                              │ │
│ │               [459 rows x 12 columns]                                                        │ │
│ │               }                                                                              │ │
│ │          pd = <module 'pandas' from                                                          │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/lib/python3.12/site-packages/pandas/__i… │ │
│ │          px = <module 'plotly.express' from                                                  │ │
│ │               '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages… │ │
│ │        quit = <IPython.core.autocall.ZMQExitAutocall object at 0x7f811ccbf920>               │ │
│ │      recipe = Recipe({Ingredient × 740} --> {Ingredient × 2} --> {Ingredient × 459} via {R × │ │
│ │               459})                                                                          │ │
│ │      select = │   target-names  no-steps  concentration-required-mM  amount-required-uL  \   │ │
│ │               19        C62668         1                        NaN                 NaN      │ │
│ │               20        C55265         1                        NaN                 NaN      │ │
│ │               21        C67555         1                        NaN                 NaN      │ │
│ │               22        C59954         1                        NaN                 NaN      │ │
│ │               23        C56722         1                        NaN                 NaN      │ │
│ │               ..           ...       ...                        ...                 ...      │ │
│ │               899        C3980         1                        NaN                 NaN      │ │
│ │               900        C5811         1                        NaN                 NaN      │ │
│ │               901        C3197         1                        NaN                 NaN      │ │
│ │               905       C70416         1                        NaN                 NaN      │ │
│ │               906      C120410         1                        NaN                 NaN      │ │
│ │               │                                                                              │ │
│ │               │    batch-tag                 reactant-1-1  \                                 │ │
│ │               19         NaN           Cc1ccc(N)c2cccnc12                                    │ │
│ │               20         NaN                     O=C(O)CO                                    │ │
│ │               21         NaN           O=C1CC(C(=O)O)CCN1                                    │ │
│ │               22         NaN                      CC(=O)O                                    │ │
│ │               23         NaN                  CC(O)C(=O)O                                    │ │
│ │               ..         ...                          ...                                    │ │
│ │               899        NaN   O=S(=O)(Cl)Cc1cccc2cccnc12                                    │ │
│ │               900        NaN           COc1ccc2cccnc2c1CN                                    │ │
│ │               901        NaN  O=[N+]([O-])c1ccc2c(c1)CNC2                                    │ │
│ │               905        NaN           Cc1nc2cc(O)ccc2n1C                                    │ │
│ │               906        NaN                 OCc1ccn[nH]1                                    │ │
│ │               │   │   │   │   │   │                                                          │ │
│ │               │   │   │   │   │   │      reactant-2-1  \                                     │ │
│ │               19                  O=C(O)c1cccc2scnc12                                        │ │
│ │               20   CC(N)C1CCCCN1C(=O)c1cccc2[nH]cnc12                                        │ │
│ │               21                 Nc1nnc(C2CCNC2)[nH]1                                        │ │
│ │               22                       NCC12CCCN1CCC2                                        │ │
│ │               23                             Nc1nccs1                                        │ │
│ │               ..                                  ...                                        │ │
│ │               899                         CNCc1scnc1C                                        │ │
│ │               900                 O=S(=O)(Cl)c1ccccn1                                        │ │
│ │               901                 O=S(=O)(Cl)Cc1cscn1                                        │ │
│ │               905                    CC(C)CCNC(=O)CCl                                        │ │
│ │               906                        O=C1CCNCC1Br                                        │ │
│ │               │   │   │   │   │   │                                                          │ │
│ │               │   │   │   │   │   │     reaction-product-smiles-1  \                         │ │
│ │               19             Cc1ccc(NC(=O)c2cccc3scnc23)c2cccnc12                            │ │
│ │               20        CC(NC(=O)CO)C1CCCCN1C(=O)c1cccc2[nH]cnc12                            │ │
│ │               21            O=C1CC(C(=O)Nc2nnc(C3CCNC3)[nH]2)CCN1                            │ │

## Syndirella inputs

In [26]:
recipe.products.compounds.add_tag("openbind_d68ev3c_c1_scaffolds_chemok_bbok")

Tagged {C × 77} w/ "openbind_d68ev3c_c1_scaffolds_chemok_bbok"

In [27]:
cset = animal.compounds(tag="openbind_d68ev3c_c1_scaffolds_chemok_bbok")
cset

compounds tagged openbind_d68ev3c_c1_scaffolds_chemok_bbok: {C × 77}

In [28]:
cset_poses = cset.poses
cset_poses

{P × 232}

In [29]:
cset_fstein_poses = cset_poses(tag="fragmenstein_placed")
cset_fstein_poses

{P × 232}

In [30]:
pset = cset_fstein_poses.get_best_placed_poses_per_compound()
pset

{P × 77}

In [31]:
pset.add_tag("openbind_d68ev3c_c1_scaffolds_chemok_bbok")
pset

Tagged {P × 77} w/ "openbind_d68ev3c_c1_scaffolds_chemok_bbok"

{P × 77}

In [32]:
df = recipe.to_syndirella("cycle_01/syndirella/elabs/c01_elabs", pset, separate=True)
df

out_key = c01_elabs

out_dir = cycle_01/syndirella/elabs

 DISK  Writing cycle_01/syndirella/elabs...

 DISK  Writing cycle_01/syndirella/elabs/templates...

DEBUG: querying...

Output()

DEBUG: adding inspiration column(s)

 DISK  Writing cycle_01/syndirella/elabs/templates/7gpp-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/7gqd-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/7got-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/7gq5-b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/7go7-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/7go9-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/7gqa-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/7go4-b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/7gq3-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/elabs/templates/7gpo-a_apo-desolv.pdb...

DEBUG: querying...

Output()

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_syndirella_inspiration_hits.sdf...

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

Output()

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C793_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C27587_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C38140_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C13421_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C29828_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10168_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6030_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C14644_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C39995_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C28548_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C12064_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C28736_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C15381_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C27243_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C32037_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C33707_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C25412_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C5010_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6392_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C75727_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C22769_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8782_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C17118_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C39494_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C20165_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C10158_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C24299_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C28938_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6668_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C6519_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C4740_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C33797_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C17133_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C65808_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C60663_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C64715_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C67927_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C55917_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C84677_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C52064_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C28382_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C32354_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46293_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C20035_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C57354_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C32774_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7644_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C76789_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C79165_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C48981_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C56761_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C48494_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C60920_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C46521_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C30056_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C60777_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C16736_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C52888_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C54502_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C50489_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C47228_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C9941_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C31678_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C60665_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C30265_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C8896_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C59056_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C15762_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C81324_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C59662_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C65802_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C55785_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C49240_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C7379_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C55308_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C28511_syndirella_input.csv...

 DISK  Writing cycle_01/syndirella/elabs/c01_elabs_C32763_syndirella_input.csv...

,,smiles,reaction_name_step1,reactant_step1,reactant2_step1,reactant3_step1,product_step11,hit1,hit2,hit3,hit4,template,compound_set
compound_id,pose_id,,,,,,,,,,,,
793,624,O=C(Nc1ccccc1I)[C@@H]1COCCO1,Sp3-sp2_Suzuki_coupling,O=C(O)c1sc(F)cc1Br,CC1(C)OB(CCC(=O)O)OC1(C)C,NaN,O=C(O)CCc1cc(F)sc1C(=O)O,7gnv-a,7goz-a,NaN,NaN,7gqd-a,C793
27587,2710,CN([C@H]1CCNC1)S(=O)(=O)CCc1ccncc1,Amidation,O=C(O)c1csc(N2CCCCC2)n1,CC(CN)[S+](C)[O-],NaN,CC(CNC(=O)c1csc(N2CCCCC2)n1)[S+](C)[O-],7gpo-a,7gp9-a,7gov-a,NaN,7go4-b,C27587
38140,6076,CC(C)(C)c1[nH]ncc1S(=O)(=O)NC[C@H](O)c1cncs1,Amidation,CCOC(=O)C1CCNC1,O=C(O)C(O)C1CCOCC1,NaN,CCOC(=O)C1CCN(C(=O)C(O)C2CCOCC2)C1,7gqc-a,7gpl-a,NaN,NaN,7go4-b,C38140
13421,7439,c1cn(CCNc2ccn3ccnc3n2)cn1,Amidation,Nc1cnn(CC(=O)O)c1,CC(CC(=O)O)n1cccn1,NaN,CC(CC(=O)Nc1cnn(CC(=O)O)c1)n1cccn1,7go4-b,7gq5-b,NaN,NaN,7go4-b,C13421
29828,8399,CS(=O)(=O)C[C@H](O)c1nc(C2CC2)cs1,Reductive_amination,NC(Cc1cnc[nH]1)C(=O)O,Cc1nc2ccccn2c1C=O,NaN,Cc1nc2ccccn2c1CNC(Cc1cnc[nH]1)C(=O)O,7gph-a,7gny-a,NaN,NaN,7go4-b,C29828
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49240,59209,C[C@H](O)C(=O)c1cnc2ncccn12,Amidation,O=C(O)c1cnc2n1CCS2,Nc1cccc2c1ccn2C(F)F,NaN,O=C(Nc1cccc2c1ccn2C(F)F)c1cnc2n1CCS2,7gph-a,7go4-a,NaN,NaN,7gpo-a,C49240
7379,60239,CCC(C)(C)CCS(=O)(=O)NC(=O)[C@@H]1CNCc2ccccc21,Formation_of_urea_from_two_amines,CC(C)S(=O)(=O)C1CCNC1,CC(N)c1cn[nH]c1,NaN,CC(NC(=O)N1CCC(S(=O)(=O)C(C)C)C1)c1cn[nH]c1,B0693a,7gph-a,7gp9-a,NaN,7gq3-a,C7379
55308,60754,CC(C)(CO)N(Cc1ccccc1)[C@@H]1CCC(=O)C1,Reductive_amination,CC(C)(C)c1nc2cc(N)ccc2o1,CC(=O)c1c[nH]cn1,NaN,CC(Nc1ccc2oc(C(C)(C)C)nc2c1)c1c[nH]cn1,7gpc-a,7gpg-a,NaN,NaN,7gq3-a,C55308
28511,60761,CC(C)(CO)NC[C@@H]1CCC(=O)N1,Formation_of_sulfonamide_from_halide_-_Shavnya...,NCc1cnc2nccn2c1,Clc1cccnc1,NaN,O=S(=O)(NCc1cnc2nccn2c1)c1cccnc1,7gpc-a,7gpg-a,NaN,NaN,7gq3-a,C28511
32763,60772,COc1ccccc1C[C@@](C)(CO)NC[C@@H]1CCC(=O)N1,Amidation,c1c[nH]c(N2CCNCC2)n1,O=C(O)CCc1ccc2ncsc2c1,NaN,O=C(CCc1ccc2ncsc2c1)N1CCN(c2ncc[nH]2)CC1,7gpc-a,7gpg-a,NaN,NaN,7gq3-a,C32763

## Queue elaboration

```

```