# OpenBind-HIPPO

- **Target: A71EV2A**
- **Cycle: 01**

## Imports

In [1]:
%load_ext autoreload
%autoreload 2
import hippo
import mrich
from mrich import print
from pathlib import Path
from os import environ
import shutil
import molparse as mp
import pandas as pd
import plotly.express as px

## Config

In [2]:
target_name = "A71EV2A"
target_dir = Path(environ["BULK"]) / "TARGETS" / target_name
cycle_name = "cycle_01"
cycle_dir = Path(cycle_name)
aligned_dir = target_dir / "aligned_files"

## Animal

In [3]:
animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")

 Creating HIPPO animal

name = A71EV2A

db_path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/A71EV2A.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/A71EV2A.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/A71EV2A.sqlite!

 Success  Initialised animal HIPPO("A71EV2A")!

## Queue BulkDock (re)placements

In [28]:
scaffold_poses = animal.poses(tag="openbind_a71ev2a_c1_scaffolds_chemok_bbok")
elaborated_scaffolds = scaffold_poses.compounds.elabs.scaffolds
elaborated_scaffold_poses = animal.poses[set(elaborated_scaffolds.poses.ids).intersection(set(scaffold_poses.ids))]
elaborated_scaffold_poses

{P × 165}

In [34]:
data = []
for i,pose in enumerate(elaborated_scaffold_poses):
    print(i, pose)
    compound = pose.compound
    elabs = compound.elabs
    reference = pose.reference
    inspirations = pose.inspirations

    inspiration_d = dict()
    for i, name in enumerate(inspirations.names):
        inspiration_d[f"hit{i+1}"] = name
    
    for elab in mrich.track(elabs):
        d = dict(smiles=elab.smiles)
        d.update(inspiration_d)
        data.append(d)

df = pd.DataFrame(data)
df.to_csv("cycle_01/syndirella/elabs/a71ev2a_c1_elab_bulkdock_input.csv", index=False)
df

0 C31471->P5840: "NDDWJXLQTNLSHN-UHFFFAOYSA-N"

Output()

1 C104497->P12401: "CEZUNCADWGOBSF-UHFFFAOYSA-N"

Output()

2 C18489->P20859: "SIMBRKSHCAHBTI-UHFFFAOYSA-N"

Output()

3 C124015->P21244: "JSISJDOIDMQNPL-UHFFFAOYSA-N"

Output()

4 C124652->P23665: "ISSCSRGHWYYCPW-UHFFFAOYSA-N"

Output()

5 C16361->P26924: "ZZPZYEPSKIPXIU-UHFFFAOYSA-N"

Output()

6 C141599->P34458: "VTHWZLJENYHQED-UHFFFAOYSA-N"

Output()

7 C204781->P45214: "GJSLUQQORYADDA-UHFFFAOYSA-N"

Output()

8 C107->P45216: "ONGQCMNCDUWDOR-UHFFFAOYSA-N"

Output()

9 C205067->P45427: "IUKJWGRXOODHIO-UHFFFAOYSA-N"

Output()

10 C205775->P48155: "GRQIJMFMPOTAPA-UHFFFAOYSA-N"

Output()

11 C266892->P54398: "UKWNMHGCUDXUJG-UHFFFAOYSA-N"

Output()

12 C195109->P58203: "NADGLDRSJLOBRP-UHFFFAOYSA-N"

Output()

13 C50277->P130605: "C50277-P616"

Output()

14 C1120->P131658: "C1120-P31"

Output()

15 C43009->P133793: "C43009-P543"

Output()

16 C114736->P138552: "C114736-P550"

Output()

17 C47059->P139075: "C47059-P440"

Output()

18 C13612->P139612: "C13612-P153"

Output()

19 C124499->P140512: "C124499-P141"

Output()

20 C48075->P159260: "C48075-P87"

Output()

21 C45999->P160679: "C45999-P441"

Output()

22 C45686->P163189: "C45686-P271"

Output()

23 C102808->P165073: "C102808-P9"

Output()

24 C47021->P170310: "C47021-P439"

Output()

25 C46596->P172717: "C46596-P257"

Output()

26 C4120->P177973: "C4120-P465"

Output()

27 C45979->P180750: "C45979-P228"

Output()

28 C46686->P184844: "C46686-P93"

Output()

29 C105126->P185670: "C105126-P273"

Output()

30 C2124->P198999: "C2124-P138"

Output()

31 C46492->P201694: "C46492-P557"

Output()

32 C124752->P208197: "C124752-P87"

Output()

33 C46019->P215801: "C46019-P439"

Output()

34 C21631->P219398: "C21631-P384"

Output()

35 C45868->P223853: "C45868-P363"

Output()

36 C48106->P224824: "C48106-P344"

Output()

37 C18492->P224978: "C18492-P7"

Output()

38 C48114->P227634: "C48114-P275"

Output()

39 C26549->P229720: "C26549-P87"

Output()

40 C12140->P230285: "C12140-P71"

Output()

41 C46745->P232053: "C46745-P151"

Output()

42 C45746->P232418: "C45746-P325"

Output()

43 C48099->P235406: "C48099-P265"

Output()

44 C28778->P243772: "C28778-P464"

Output()

45 C35473->P248992: "C35473-P248"

Output()

46 C45975->P255744: "C45975-P303"

Output()

47 C4100->P258510: "C4100-P87"

Output()

48 C48047->P264625: "C48047-P481"

Output()

49 C47450->P270555: "C47450-P255"

Output()

50 C45698->P276638: "C45698-P198"

Output()

51 C45621->P286979: "C45621-P423"

Output()

52 C3473->P287259: "C3473-P356"

Output()

53 C119126->P292336: "C119126-P296"

Output()

54 C45810->P295956: "C45810-P208"

Output()

55 C21091->P298844: "C21091-P489"

Output()

56 C47038->P301282: "C47038-P373"

Output()

57 C47019->P305573: "C47019-P328"

Output()

58 C104894->P307668: "C104894-P356"

Output()

59 C129593->P312537: "C129593-P51"

Output()

60 C107313->P315183: "C107313-P87"

Output()

61 C35612->P317958: "C35612-P128"

Output()

62 C47627->P325526: "C47627-P303"

Output()

63 C1613->P330608: "C1613-P198"

Output()

64 C13863->P331389: "C13863-P127"

Output()

65 C1719->P335507: "C1719-P144"

Output()

66 C15998->P335899: "C15998-P239"

Output()

67 C24648->P337816: "C24648-P145"

Output()

68 C39872->P338537: "C39872-P118"

Output()

69 C2418->P343349: "C2418-P339"

Output()

70 C15324->P343728: "C15324-P103"

Output()

71 C137292->P346274: "C137292-P58"

Output()

72 C16607->P347245: "C16607-P320"

Output()

73 C25407->P349206: "C25407-P78"

Output()

74 C20719->P352418: "C20719-P151"

Output()

75 C137594->P353637: "C137594-P9"

Output()

76 C13878->P354466: "C13878-P127"

Output()

77 C39011->P358167: "C39011-P115"

Output()

78 C20947->P370236: "C20947-P123"

Output()

79 C2306->P371085: "C2306-P51"

Output()

80 C1401->P371348: "C1401-P391"

Output()

81 C13648->P372624: "C13648-P2"

Output()

82 C2404->P375423: "C2404-P278"

Output()

83 C4560->P377032: "C4560-P564"

Output()

84 C17161->P377140: "C17161-P103"

Output()

85 C13635->P378090: "C13635-P338"

Output()

86 C31914->P378091: "C31914-P338"

Output()

87 C29365->P382349: "C29365-P115"

Output()

88 C23517->P383972: "C23517-P115"

Output()

89 C37776->P385263: "C37776-P273"

Output()

90 C34425->P386422: "C34425-P31"

Output()

91 C2081->P388144: "C2081-P363"

Output()

92 C12016->P388238: "C12016-P161"

Output()

93 C11989->P389951: "C11989-P134"

Output()

94 C12012->P389969: "C12012-P344"

Output()

95 C3782->P391136: "C3782-P487"

Output()

96 C3542->P395811: "C3542-P195"

Output()

97 C13624->P396849: "C13624-P161"

Output()

98 C10379->P397379: "C10379-P310"

Output()

99 C11248->P398262: "C11248-P103"

Output()

100 C1373->P401691: "C1373-P168"

Output()

101 C40319->P403450: "C40319-P113"

Output()

102 C1419->P406831: "C1419-P309"

Output()

103 C1603->P407074: "C1603-P183"

Output()

104 C31867->P407398: "C31867-P115"

Output()

105 C21294->P409402: "C21294-P9"

Output()

106 C9987->P410294: "C9987-P363"

Output()

107 C22847->P411246: "C22847-P54"

Output()

108 C15735->P411746: "C15735-P103"

Output()

109 C13636->P413601: "C13636-P494"

Output()

110 C4708->P415458: "C4708-P437"

Output()

111 C12411->P416044: "C12411-P219"

Output()

112 C7596->P421273: "C7596-P190"

Output()

113 C22220->P422808: "C22220-P145"

Output()

114 C32415->P422828: "C32415-P95"

Output()

115 C13629->P423431: "C13629-P136"

Output()

116 C10571->P423495: "C10571-P136"

Output()

117 C39794->P424174: "C39794-P38"

Output()

118 C23295->P429295: "C23295-P45"

Output()

119 C12352->P429416: "C12352-P183"

Output()

120 C13816->P432588: "C13816-P106"

Output()

121 C23130->P435267: "C23130-P37"

Output()

122 C25347->P437728: "C25347-P198"

Output()

123 C27189->P438429: "C27189-P16"

Output()

124 C27676->P438736: "C27676-P109"

Output()

125 C27907->P438995: "C27907-P259"

Output()

126 C28573->P439928: "C28573-P76"

Output()

127 C22223->P442475: "C22223-P136"

Output()

128 C29440->P443088: "C29440-P77"

Output()

129 C10549->P443770: "C10549-P176"

Output()

130 C20145->P448908: "C20145-P356"

Output()

131 C27893->P448914: "C27893-P356"

Output()

132 C13661->P450577: "C13661-P274"

Output()

133 C20940->P451909: "C20940-P248"

Output()

134 C20970->P451933: "C20970-P248"

Output()

135 C1418->P452795: "C1418-P183"

Output()

136 C29678->P454531: "C29678-P371"

Output()

137 C17988->P456545: "C17988-P145"

Output()

138 C18032->P456571: "C18032-P36"

Output()

139 C43172->P456823: "C43172-P115"

Output()

140 C29694->P456851: "C29694-P439"

Output()

141 C10567->P458751: "C10567-P182"

Output()

142 C20308->P458922: "C20308-P95"

Output()

143 C29671->P459884: "C29671-P492"

Output()

144 C4820->P460087: "C4820-P371"

Output()

145 C28323->P463188: "C28323-P198"

Output()

146 C38131->P464274: "C38131-P71"

Output()

147 C14078->P467135: "C14078-P135"

Output()

148 C1002->P474246: "C1002-P233"

Output()

149 C10333->P475236: "C10333-P564"

Output()

150 C10575->P478135: "C10575-P174"

Output()

151 C10535->P478249: "C10535-P183"

Output()

152 C1406->P479113: "C1406-P343"

Output()

153 C3842->P479383: "C3842-P87"

Output()

154 C3863->P479389: "C3863-P87"

Output()

155 C1399->P481610: "C1399-P296"

Output()

156 C4256->P482764: "C4256-P174"

Output()

157 C33613->P482901: "C33613-P137"

Output()

158 C1132->P483323: "C1132-P228"

Output()

159 C11987->P484432: "C11987-P343"

Output()

160 C15471->P485914: "C15471-P171"

Output()

161 C15476->P485919: "C15476-P171"

Output()

162 C15494->P485935: "C15494-P171"

Output()

163 C13918->P495248: "C13918-P135"

Output()

164 C1142->P496163: "C1142-P465"

Output()

                                                  smiles    hit1    hit2
0      CC(CC(=O)NCC1(F)CC2CCC(C1)N2C(=O)OC(C)(C)C)N1C...  A0528a  A4445b
1            CC(C)Cc1nnc2c(C(=O)OC(C)c3ccnc(Cl)c3)cccn12  A1293a  A3194a
2              CC(C)Cc1nnc2c(C(=O)OC(C)c3ccncc3Br)cccn12  A1293a  A3194a
3             Cc1cc(C(C)OC(=O)c2cccn3c(CC(C)C)nnc23)ccn1  A1293a  A3194a
4              CC(C)Cc1nnc2c(C(=O)OC(C)c3ccncc3Cl)cccn12  A1293a  A3194a
...                                                  ...     ...     ...
18455    Cc1ccc(CN2C(=O)CCC2C(=O)OCC(C)(C)n2cc(I)cn2)cc1  A2629a  A3956a
18456  CC(C)(COC(=O)C1CCC(=O)N1Cc1ccc(C(N)=O)cc1)n1cc...  A2629a  A3956a
18457  COc1ccc2c(c1)C(NC(=O)C1CCCCCN1C)CCN2C(=O)OC(C)...  A0586a  A4786a
18458  COc1ccc2c(c1)C(NC(=O)C1CCCCC(=O)N1)CCN2C(=O)OC...  A0586a  A4786a
18459  COc1ccc2c(c1)C(NC(=O)C13CC4CC(C(=O)N1)C3C4)CCN...  A0586a  A4786a

[18460 rows x 3 columns]

## Define chemspace

In [36]:
scaffolds = animal.compounds(tag="openbind_a71ev2a_c1_scaffolds_chemok_bbok")
scaffolds

compounds tagged openbind_a71ev2a_c1_scaffolds_chemok_bbok: {C × 558}

In [37]:
elabs = scaffolds.elabs
elabs

{C × 18454}

In [38]:
elaborated_scaffolds = elabs.scaffolds
elaborated_scaffolds

{C × 165}

In [50]:
# elab_poses = elabs.poses.filter(key="distance_score", value="2.0", operator="<=")
# elab_poses = elab_poses.filter(key="energy_score", value="0.0", operator="<=")
elab_poses = elabs.poses
elab_poses

{P × 36650}

In [51]:
posed_elabs = elab_poses.compounds
posed_elabs

{C × 17070}

In [52]:
posed_elabs.add_tag("openbind_a71ev2a_c1_elabs")

Tagged {C × 17070} w/ "openbind_a71ev2a_c1_elabs"

In [53]:
posed_elabs.scaffolds.add_tag("openbind_a71ev2a_c1_elaborated_scaffolds")

Tagged {C × 159} w/ "openbind_a71ev2a_c1_elaborated_scaffolds"

In [54]:
chemspace = posed_elabs + posed_elabs.scaffolds
chemspace

{C × 17229}

## Export chemspace

In [55]:
chemspace_poses = chemspace.best_placed_poses
chemspace_poses

{P × 17229}

In [61]:
chemspace_poses.to_fragalysis("cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace.sdf",
    method="openbind_a71ev2a_c1_elab_chemspace", 
    submitter_name="Max Winokan", 
    submitter_institution="DLS", 
    submitter_email="max.winokan@diamond.ac.uk",
    copy_reference_pdbs=True,
    metadata=False,
    tags=False,
    subsites=False,
)

DEBUG: 17229 poses in set

DEBUG: 17223 remaining after skipping null reference

DEBUG: 17223 remaining after skipping null inspirations

#poses = 17223

DEBUG: querying...

Output()

DEBUG: adding inspiration column(s)

out_path =
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace.sdf

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4445b.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3194a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0469a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0586a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0863a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0514a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A5594a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3665a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A5424b.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4994a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A5036a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4707a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3207a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3176a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0875a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4708a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4020b.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0486a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4706a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3986b.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4786a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3868a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0926a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4029a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3054a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A5079a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4509a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4445a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4274b.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4031b.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0428a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4368a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4012b.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4784a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4320a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3982a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3618a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4650a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4418a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4311a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3706b.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4855a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4461a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4374a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A2304a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A2293a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3181a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3920a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3181b.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A1293a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4237b.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A1105b.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0354a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4347a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0719b.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A1209a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4291a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A1776a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0239a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4298a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4035a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A5091a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4237a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3229a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A2513a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4846a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3612a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4333a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3306a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A1180a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3436a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0341a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4874a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4701a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3564a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A1068a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A2846a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0608a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0202a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A1140a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0310a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0514b.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A1146a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3990a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0717a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0719a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3392a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4031a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3956a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4456a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0309a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3435a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4873a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A2629a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3890a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3371a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A2972a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A4274a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A3581a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A2290a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0528a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A1778a.p
db...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace/A0525a.p
db...

 DISK  Writing openbind_a71ev2a_c1_elab_chemspace_refs.zip...

[09:33:52] Molecule does not have explicit Hs. Consider calling AddHs()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_elab_chemspace.sdf...

,HIPPO Pose ID,smiles,inchikey,alias,HIPPO Compound ID,ROMol,energy_score,distance_score,inspiration_score,name,ref_mols,ref_pdb,_Name
0,5840,O=C1CCCN1CCC(=O)N1[C@@H]2CC[C@H]1C[C@@H](F)C2,NDDWJXLQTNLSHN-UHFFFAOYSA-N,None,31471,<rdkit.Chem.rdchem.Mol object at 0x7f7e6c75bc90>,19.687705,1.853852,None,P5840,"A4445b,A0528a",A4445b,P5840
1,12401,CC(C)Cc1nnc2c(C(=O)O[C@@H](C)c3ccncc3)cccn12,CEZUNCADWGOBSF-UHFFFAOYSA-N,None,104497,<rdkit.Chem.rdchem.Mol object at 0x7f7e6c75bce0>,367.720342,4.959837,None,P12401,"A1293a,A3194a",A3194a,P12401
2,20859,O=C(CSc1nc2ccccc2s1)N1CCN(c2ccccn2)CC1,SIMBRKSHCAHBTI-UHFFFAOYSA-N,None,18489,<rdkit.Chem.rdchem.Mol object at 0x7f7e6c75bd80>,291.926851,3.549790,None,P20859,"A4031b,A0469a",A0469a,P20859
3,21244,CC(C)(NC(=O)[C@H]1CCNc2ccccc21)C1CCNCC1,JSISJDOIDMQNPL-UHFFFAOYSA-N,None,124015,<rdkit.Chem.rdchem.Mol object at 0x7f7e6c75bd30>,1058.821270,7.883489,None,P21244,"A0875a,A0586a",A0586a,P21244
4,23665,CCN(CC)C(=O)c1cccc(NC(=O)[C@H](C)N2CCc3ccccc32)c1,ISSCSRGHWYYCPW-UHFFFAOYSA-N,None,124652,<rdkit.Chem.rdchem.Mol object at 0x7f7e6c75be20>,435.571228,8.224200,None,P23665,"A1778a,A0863a",A0863a,P23665
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17218,534277,Cc1ccc(CN2C(=O)CCC2C(=O)OCC(C)(C)n2cc(I)cn2)cc1,YNPAUEIBABHEKE-UHFFFAOYSA-N,YNPAUEIBABHEKE-UHFFFAOYSA-N-P135-P135-P248-601519,291949,<rdkit.Chem.rdchem.Mol object at 0x7f7e63e40db0>,35.224866,2.763671,None,YNPAUEIBABHEKE-UHFFFAOYSA-N-P135-P135-P248-601519,"A3956a,A2629a",A0239a,YNPAUEIBABHEKE-UHFFFAOYSA-N-P135-P135-P248-601519
17219,534279,CC(C)(COC(=O)C1CCC(=O)N1Cc1ccc(C(N)=O)cc1)n1cc...,NEPCPUTWFPZLSP-UHFFFAOYSA-N,NEPCPUTWFPZLSP-UHFFFAOYSA-N-P135-P135-P248-601519,291950,<rdkit.Chem.rdchem.Mol object at 0x7f7e63e40e00>,263.115612,3.331551,None,NEPCPUTWFPZLSP-UHFFFAOYSA-N-P135-P135-P248-601519,"A3956a,A2629a",A0239a,NEPCPUTWFPZLSP-UHFFFAOYSA-N-P135-P135-P248-601519
17220,534281,COc1ccc2c(c1)C(NC(=O)C1CCCCCN1C)CCN2C(=O)OC(C)...,NJANJWBKTPXSEJ-UHFFFAOYSA-N,NJANJWBKTPXSEJ-UHFFFAOYSA-N-P31-P31-P465-601519,289625,<rdkit.Chem.rdchem.Mol object at 0x7f7e63e40e50>,1927.382741,5.904219,None,NJANJWBKTPXSEJ-UHFFFAOYSA-N-P31-P31-P465-601519,"A4786a,A0586a",A0239a,NJANJWBKTPXSEJ-UHFFFAOYSA-N-P31-P31-P465-601519
17221,534283,COc1ccc2c(c1)C(NC(=O)C1CCCCC(=O)N1)CCN2C(=O)OC...,POVSBNDSPBUDML-UHFFFAOYSA-N,POVSBNDSPBUDML-UHFFFAOYSA-N-P31-P31-P465-601519,289626,<rdkit.Chem.rdchem.Mol object at 0x7f7e63e40ea0>,1015.281526,5.741627,None,POVSBNDSPBUDML-UHFFFAOYSA-N-P31-P31-P465-601519,"A4786a,A0586a",A0239a,POVSBNDSPBUDML-UHFFFAOYSA-N-P31-P31-P465-601519
17222,534286,COc1ccc2c(c1)C(NC(=O)C13CC4CC(C(=O)N1)C3C4)CCN...,MWUSIYLUZPGHDX-UHFFFAOYSA-N,MWUSIYLUZPGHDX-UHFFFAOYSA-N-P465-P31-P465-601519,289627,<rdkit.Chem.rdchem.Mol object at 0x7f7e63e40ef0>,2423.814868,5.211644,None,MWUSIYLUZPGHDX-UHFFFAOYSA-N-P465-P31-P465-601519,"A4786a,A0586a",A0239a,MWUSIYLUZPGHDX-UHFFFAOYSA-N-P465-P31-P465-601519

In [62]:
mrich.success("Done")

 Success  Done!

## Add in-stock reactants